### ISSUE TITLE
Hi, can you upload wheel (whl) package ?

### ISSUE THREAD

**Issue by GunGunGun** [yifeikong/curl_cffi#1]
I'm on Windows 7 and I can't compile this package, can you provide whl package for easier installing and testing ? Thank you very much!

**Comment by yifeikong** [comment]
Sorry, this package is far from complete. In fact, I just learned the difference between a `sdist` and `bdist`. If you would like to use curl with cffi on Windows, please see the original package for now: https://github.com/multippt/python_curl_cffi

**Comment by yifeikong** [comment]
Hi, I just uploaded a version(0.2.4) with Windows binary included, you should be able to use it by simply `pip install -U curl_cffi`.
