### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by VCDEV1** [yifeikong/curl_cffi#10]
Hello there. First of all thank you for your amazing work! Nowadays many websites triggers captcha for normal python requests. But this works amazingly by bypassing all of it. I was searching for a thing like this. Thank you again.

What I wanted to ask were the following things.

1. As you have said in the to do list can you add the `requests.Session()` method. It will be a huge improvement and will be easy to implement with current projects too.
2. Can you add support for socks proxies as well. I don't know if it is already supported or not. But since requests and curl both supports socks proxies, I think it should be possible.
3. Can you say if this works like httpx currently? Does this send http2 requests currently? If not can you please add the support to specify an option to use http2 such as `http2=True`, like in the normal httpx package.

If these things could be added to this package it would be very easy to implement this in current projects without much work. Also if these could be added, I really don't see a reason why people would use normal requests anymore since it is easily detectable. This is really amazing. Thanks for your work again!

**Comment by yifeikong** [comment]
This project is a very **thin** wrapper around the `libcurl-impersonate` binary. For things like socks proxy or http2, it should work if `curl` and `curl-impersonate` support them. If the api is not exposed in `curl_cffi.requests`, you can look up the curl website and use `curl_cffi.Curl.setopt` function. You are welcome to submit a PR to fix those issues.

AFAIK, http2 is supported and http2 fingerprint impersonation is part of the `curl-impersonate` project.

```
In [7]: r = requests.get("https://kawayiyi.com/tls")

In [8]: r.json()["proto"]
Out[8]: 'HTTP/2'
```

For `requests.Session` like interface, it would take some time to implement. I'm quite busy on work these days, so stay tuned.

**Comment by yifeikong** [comment]
Session is supported in the latest version.

**Comment by VCDEV1** [comment]
@yifeikong Thank you for this! I confirm all the requests are http2 and socks proxies are supported too. I actually tested it and works very well! Thank you for your work and support! Also if you can could you please take a look at #13
