### ISSUE TITLE
example.py中的stream还是报错

### ISSUE THREAD

**Issue by chuanSir123** [yifeikong/curl_cffi#103]
example.py中的stream还是报错AsyncSession.request() got an unexpected keyword argument 'stream'，我看更新日志Support stream in asyncio mode，应该怎么正确使用stream呢
async def async_main():
    async with requests.AsyncSession() as s:
        r = await s.get("https://httpbin.org/headers")
        print(r.text)

        r = await s.get("https://httpbin.org/headers", stream=True)
        async for content in r.iter_content():
            print(content)

**Comment by yifeikong** [comment]
这个还没实现，很抱歉 example.py 给你造成了误导，有时间了会删掉这个错误的例子😂

**Comment by chuanSir123** [comment]
> 这个还没实现，很抱歉 example.py 给你造成了误导，有时间了会删掉这个错误的例子😂

噢，那更新日志中的Support stream in asyncio mode是什么意思呢，我想使用流回复有办法么

**Comment by yifeikong** [comment]
你在哪儿看到的……现在可以用回调的方式，看下 content_callback 参数
