### ISSUE TITLE
error setting certificate verify locations

### ISSUE THREAD

**Issue by rezochs** [yifeikong/curl_cffi#104]
我使用最新版本的 curl_cffi出现了这个问题 
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: xxx\venv\lib\site-packages\curl_cffi\cacert.pem CApath: none'
During handling of the above exception, another exception occurred:
我安装好这个包的时候他是有证书的 但是我请求任何网站都会报这个错误
from curl_cffi import requests

# Notice the impersonate parameter
r = requests.get("https://tls.browserleaks.com/json", impersonate="chrome101")

print(r.json())
这是我的代码 
然后我使用的版本是 
python3.8
pip 23.2.1 from F:\project\venv\lib\site-packages\pip (python 3.8)
Windows 11 专业版 22H2

**Comment by rezochs** [comment]
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77 具体信息 
![image](https://github.com/yifeikong/curl_cffi/assets/13915654/0ecdd92e-541f-49b4-9f5d-d26098be695f)
![image](https://github.com/yifeikong/curl_cffi/assets/13915654/2e2bc154-bebe-47ca-8b7f-8cce1a995bfe)
证书使用的是安装自带的

**Comment by yifeikong** [comment]
应该是某个老版本的问题，升级下：pip install curl_cffi==0.5.7

**Comment by rezochs** [comment]
![image](https://github.com/yifeikong/curl_cffi/assets/13915654/56a82308-9c9d-4db9-8c7c-e98e19bd491d)
可是他就是最新版本 有这个问题 很奇怪 我尝试替换过证书也会有这个问题

**Comment by rezochs** [comment]
在的 
![image](https://github.com/yifeikong/curl_cffi/assets/13915654/c5a5fc8b-1c92-49c7-a877-a9fec8593791)
你看奥 我装好这个包的时候他就在

**Comment by yifeikong** [comment]
卸载重装试试吧，感觉像是文件坏了。

**Comment by rezochs** [comment]
我卸载过重装过 替换文件过 他都报这个错误 很怪 我就差换python版本 我现在用的 venv虚拟环境

**Comment by rezochs** [comment]
更换python版本也好像不行

**Comment by rezochs** [comment]
from curl_cffi import Curl, CurlOpt
c = Curl()
c.setopt(CurlOpt.CAINFO, 'cacert.pem') 这个样子就不报错 怪了

**Comment by rezochs** [comment]
from curl_cffi import Curl, requests

curl = Curl(cacert="cacert.pem")
session = requests.Session(curl=curl)
r = session.get("https://tls.browserleaks.com/json", impersonate="chrome101")
print(r.json()) 这个样子不会报错 如果使用默认的那个会报错 就是 pip install 默认的哪个会报错

**Comment by yifeikong** [comment]
你确定下到底用的是哪个文件吧，应该是文件损坏了

**Comment by rezochs** [comment]
就是 pip安装之后不是会带一个证书么 带的那个证书报错 重现下的证书不报错

**Comment by yifeikong** [comment]
你安装包的路径中有中文吗?

**Comment by jjyyfff** [comment]
提示错误：curl_cffi.curl.CurlError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations: CAfile: C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\cacert.pem CApath: none'


claude的回答：根据错误信息,我的分析是:

在使用curl_cffi模块发起请求时,出现了CurlError异常,错误代码为77。

错误原因是在设置证书验证位置时发生错误,指定的CA证书文件路径为:

C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\curl_cffi\cacert.pem

但是设置的CA路径为none。

这意味着在发起请求时,curl试图使用指定的CA证书文件来验证SSL连接,但是设置的CA证书路径为空,导致无法找到CA证书而失败。

为了修复这个问题,需要确保CA证书文件的路径设置正确,CA文件存在且可读。同时也可以考虑不验证SSL证书。

总之,这个错误是因为设置的CA证书路径不正确,curl无法找到CA证书来验证SSL连接导致的。修复方法是检查CA证书文件路径的设置。
--------------------------------------------------------------------------------------------------------------------------------------------

基于以上，请教下，如何设置证书路径？谢谢

**Comment by resphinas** [comment]
亲测目录中文去掉就可以

**Comment by jjyyfff** [comment]
> 亲测目录中文去掉就可以

感谢感谢

**Comment by tahmid-23** [comment]
I'm having trouble with this issue on Linux, and I don't have duplicate paths

**Comment by resphinas** [comment]
> I'm having trouble with this issue on Linux, and I don't have Chinese characters in my paths

in detial

**Comment by yifeikong** [comment]
@tahmid-23 Here are a few steps you can try to locate and maybe solve this issue:

1. Which version are you running? some of the old versions contain a bug related to certs. Make sure you are using the latest version(0.5.7) or latest beta(0.5.9b4)
2. Not only Chinese characters, it seems that libcurl is unhappy with any non-alphanum chars for paths.
3. Check if the bundled cert file(e.g. xxx\venv\lib\site-packages\curl_cffi\cacert.pem) exists and is a valid pem file. Try to set it mannually with `setopt` as shown above comments.

If this error persists, plase post error messages here.

**Comment by tahmid-23** [comment]
1. 0.5.7
2. only letters and and _
3. the file exists, I've tried replacing it too. I'm using AsyncSession/AsyncCurl, which seems to provision its own Curl instances anyway so I don't think that would make a difference. Regardless, I tried setting the option and it didn't work.

`Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: /home/***/PycharmProjects/***/venv/lib/python3.11/site-packages/curl_cffi/cacert.pem CApath: none'` (omitted characters only contain a-z and _. This shouldn't be a problem, because "curl_cffi" contains _ anyway)

I found that this issue doesn't happen when I run it in PyCharm, or when I open a terminal in PyCharm. It happens only when I run through a regular terminal.

**Comment by yifeikong** [comment]
Weird. Do you see any difference between the PyCharm terminal and regular terminal when using the `env` command to dump environment variables? particularly for charsets and encoding.

**Comment by tahmid-23** [comment]
there's a few minor differences with gnome I think, but nothing related to encoding it seems.
`LANG` is set to `en_US.UTF-8`.

**Comment by Hanbaguiya** [comment]
> 你安装包的路径中有中文吗?

curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (77) error setting certificate verify locations:  CAfile: /etc/ssl/certs/ca-certificates.crt CApath: /etc/ssl/certs. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
不知道为什么一直报这个，系统不是乌邦图是centos
