### ISSUE TITLE
Remove cookie print from pip package

### ISSUE THREAD

**Issue by OEvans117** [yifeikong/curl_cffi#11]
Is this possible? I know it's updated in the repo but I cannot build it right now

**Comment by zidokobik** [comment]
We need to nudge @yifeikong to update it on Pypi. It's already been fixed in [this PR](https://github.com/yifeikong/curl_cffi/pull/3#issue-1563223984).

**Comment by yifeikong** [comment]
Sorry for the delay, fixed in v0.2.5

    pip install -U curl_cffi

should work.
