### ISSUE TITLE
0.5.9b3 - `curl.getinfo()` not working after error (works in 0.5.7)

### ISSUE THREAD

**Issue by coletdjnz** [yifeikong/curl_cffi#110]
In 0.5.7, it was possible to use `curl.getinfo()` after an error to try get information about the failed request/response. However in 0.5.9b1+ (possibly earlier, not tested), it appears to not work and return empty/unavailable values.

Quick test that works with 0.5.7:

```py
# pytest test.py
import http.server
import threading
import curl_cffi.requests
import curl_cffi.const
import pytest


class HTTPTestRequestHandler(http.server.BaseHTTPRequestHandler):
    protocol_version = 'HTTP/1.1'
    default_request_version = 'HTTP/1.1'

    def do_GET(self):
        if self.path.startswith('/redirect_loop'):
            self.send_response(301)
            self.send_header('Location', self.path)
            self.send_header('Content-Length', '0')
            self.end_headers()


class TestCurl:
    @classmethod
    def setup_class(cls):
        cls.http_httpd = http.server.ThreadingHTTPServer(
            ('127.0.0.1', 0), HTTPTestRequestHandler)
        cls.http_port = cls.http_httpd.socket.getsockname()[1]
        cls.http_server_thread = threading.Thread(target=cls.http_httpd.serve_forever)
        cls.http_server_thread.daemon = True
        cls.http_server_thread.start()

    def test_redirect_loop(self):
        session = curl_cffi.requests.Session()
        try:
            session.get(f'http://127.0.0.1:{self.http_port}/redirect_loop', max_redirects=3)
        except curl_cffi.requests.errors.RequestsError as e:
            status = session.curl.getinfo(curl_cffi.const.CurlInfo.RESPONSE_CODE)
            assert status == 301  # returns 0 in 0.5.9b3
```

This may not be an intended use-case and isn't super critical, so no worries if it's not viable to fix.

**Comment by yifeikong** [comment]
I intentionally reset the curl instance [here](https://github.com/yifeikong/curl_cffi/blob/master/curl_cffi/requests/session.py#L554-L555). Previously, without the `finally` clause, the `reset` line will not be reached when error occurs, which can be a potential cause of bugs, since some of the options may not be overriden in the next request.

Unfortunately, `reset` does not reset options only, it resets `info`s, too. Perhaps, I should rethink the order of execution here.

**Comment by coletdjnz** [comment]
Hmm, I see. A response could work in some cases, but that may not contain everything someone may want to access (e.g. SIZE_DOWNLOAD etc.).

Could this also cause problems when/if you implement streaming?

**Comment by yifeikong** [comment]
Good points. The better solution is to reset the options we touched to default values. I was just too lazy to write down each one of them before.

```py
class Session:

    def _reset_options(self, curl: Curl):
        c = curl
        c.setopt(CurlOpt.POST, 0)
        c.setopt(CurlOpt.CUSTOMREQUEST, ffi.NULL)
        c.setopt(CurlOpt.URL, "")
        c.setopt(CurlOpt.POSTFIELDS, ffi.NULL)
        c.setopt(CurlOpt.POSTFIELDSIZE, -1)
        c.setopt(CurlOpt.HTTPHEADER, [])
        c.setopt(CurlOpt.USERNAME, "")  # XXX: null or empty?
        c.setopt(CurlOpt.PASSWORD, "")
        c.setopt(CurlOpt.CONNECTTIMEOUT_MS, 300000)
        c.setopt(CurlOpt.TIMEOUT_MS, 0)
        c.setopt(CurlOpt.FOLLOWLOCATION, 0)
        c.setopt(CurlOpt.MAXREDIRS, -1)  # unlimited in curl 7.84.0
        c.setopt(CurlOpt.PROXY, ffi.NULL)
        c.setopt(CurlOpt.HTTPPROXYTUNNEL, 0)
        c.setopt(CurlOpt.SSL_VERIFYPEER, 1)
        c.setopt(CurlOpt.SSL_VERIFYHOST, 1)
        # c.setopt(CurlOpt.CAINFO, )  # not sure about this one
        c.setopt(CurlOpt.REFERER, ffi.NULL)
        c.setopt(CurlOpt.ACCEPT_ENCODING, ffi.NULL)
        c.setopt(CurlOpt.HTTP_VERSION, CurlHttpVersion.V2TLS)
        # unlikely to reset to default, but should be OK.
        # c.setopt(CurlOpt.WRITEDATA, )
        # c.setopt(CurlOpt.WRITEFUNCTION, )
        # c.setopt(CurlOpt.HEADERDATA, )
        c.setopt(CurlOpt.NOBODY, 0)
        c.setopt(CurlOpt.INTERFACE, ffi.NULL)

   def reqeust(...):
       ...
       finally:
           # self.curl.reset()
           self._reset_options()
```

This way, you can read whatever you want from curl after `perform`, nothing is being removed.

As for stream, the only we I can think of, to convert callback style to iterator, is to request in another thread and queue the chunks to main thread, which should not be affected by `reset`.

**Comment by coletdjnz** [comment]
Hmm, perhaps. Though I'd worry that could be hard to maintain.

Maybe the current behaviour is fine - consider it internal. Instead it might be better to focus on extracting useful information internally into exceptions (incomplete read etc.) and as you suggest, a parsed response? At least, that was my only use case for this.

**Comment by yifeikong** [comment]
I added response attribute for exception in 0.5.9b4, from which you can read `e.response.status_code`, which is `CURLINFO_RESPONSE_CODE` and `e.response.url`, which is `CURLINFO_EFFECTIVE_URL`.

It should be OK to move `reset` to the beginning of a request. However, some user may choose to addd their own curl option before `Session.request`, by moving it, the cusomized options are lost.

**Comment by coletdjnz** [comment]
> I added response attribute for exception in 0.5.9b4, from which you can read `e.response.status_code`, which is `CURLINFO_RESPONSE_CODE` and `e.response.url`, which is `CURLINFO_EFFECTIVE_URL`.

Looks good, that could work. And over time more information can be extracted into exceptions etc. I suppose.

> It should be OK to move `reset` to the beginning of a request. However, some user may choose to addd their own curl option before `Session.request`, by moving it, the cusomized options are lost.

Ah, right. That would break a lot of things :sweat_smile:
