### ISSUE TITLE
AsyncSession with timeouts hanging after a while

### ISSUE THREAD

**Issue by Ceteex** [yifeikong/curl_cffi#113]
I'm running curl_cffi 0.5.7. I'm using AsyncSession with this code:

```python
async def load_url(url: str, session: AsyncSession):
  try:
    ans = await session.get(url, proxies={proxieshere}, headers={headershere}, impersonate="chrome110", timeout=5)
    # ...
  except Exception as exc:
    print("Exception: {}".format(str(exc)))

async def setup():
    while 1:
        async with AsyncSession(max_clients=5) as session:
            tasks = []
            for url in urls:
                task = load_url(url=url, session=session)
                tasks.append(task)
            await gather(*tasks,return_exceptions=True)
```

It works as it should in the beginning, but after a while it starts slowing down, and timeouts begin becoming more frequent
Timeout Error:
```Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 5005 milliseconds with 41047 bytes received'```.

Soon enough, these would cause the threads to hang. I fixed it by changing session.py from:

```python
try:
    # curl.debug()
    await self.acurl.add_handle(curl)
    # print(curl.getinfo(CurlInfo.CAINFO))
    curl.clean_after_perform()
except CurlError as e:
    curl.reset()
    self.push_curl(curl)
    raise RequestsError(e)
rsp = self._parse_response(curl, req, buffer, header_buffer)
curl.reset()
self.push_curl(curl)
return rsp
```

to:

```python
try:
    # curl.debug()
    await self.acurl.add_handle(curl)
    # print(curl.getinfo(CurlInfo.CAINFO))
except CurlError as e:
    raise RequestsError(e)
else:
    rsp = self._parse_response(curl, req, buffer, header_buffer)
    return rsp
finally:
    curl.reset()
    self.push_curl(curl)
```

It doesn't cause the threads to freeze anymore, but instead, once it starts slowing down after a while for no reason, only timeouts begin to happen for sometimes several minutes before it starts working as normal again, and then timeouts start to happen again. If I restart the program, it starts working again so there's no problem with my proxies.

**Comment by yifeikong** [comment]
A few questions to ask:

- Does it work if you connect directly without proxies?
- If not, could you please provide the url so I can try to reproduce it?
- If urls are not available, can you add more logs to see where did the script stuck?

**Comment by Ceteex** [comment]
It seems to work if I don't use proxies. I'm not sure where to set the logs for curl_cffi, though.

**Comment by Ceteex** [comment]
I have found out that if I unplug my ethernet for a few seconds, the timeouts show up (as expected), but they don't stop.

It seems like `_force_timeout` in `aio.py` runs unusually often whenever the timeouts start.

**Comment by yifeikong** [comment]
From you two comments, it seems that on a bad network condition, e.g. with proxies, once the timeouts started, there will be a domino effect that brings down the whole script. I will try to reproduce this. If you have any more details, please continue to post them here.

**Comment by Ceteex** [comment]
Hey! After several days of troubleshooting, I think I've managed to find a solution that could fix the issue. In the `request` function in `AsyncSession`, I have added the following two lines to the except part of the try except block:

```py
self.close()
self.acurl = AsyncCurl(loop=self.loop)
```

Although I'm not 100% certain if this is the best way to do it, more tests would have to be made to make sure that there are no memory leaks or slow downs caused by this.

Would you be able to confirm if this is safe to do?

**Comment by yifeikong** [comment]
I'm not sure it's safe to do this. By closing the whole session, i.e. the underlying curl_multi handle, all other running requests will be canceled.

**Comment by Ceteex** [comment]
I see. I did notice that too, so doing so does not seem safe. It raised exceptions in other threads that had requests already running. Would you have any other ideas in mind that could work?

**Comment by Ceteex** [comment]
Hey, just wanted to add that it seems like a memory leak might be the cause of the speeds slowing down more and more with time. My script starts with about 33 mb memory usage, but it rises steadily with about 1 mb every few seconds. It does not seem to be caused by my script, since I've never had this issue before until after I've switched to curl_cffi.

**Comment by yifeikong** [comment]
Close as stale. Please try the latest version, 0.5.9 as of Nov 2023.
