### ISSUE TITLE
Add WebSocket Support

### ISSUE THREAD

**Issue by glira** [yifeikong/curl_cffi#114]
you are doing an excellent job congratulations with all my heart you saved part of a business I have here please provide a crypto wallet so I can repay your favor with a donation, I would like to know if it is possible to use websocket.WebSocketApp together with your code

**Comment by yifeikong** [comment]
Thank you for your kind words.

If you are referring to websocket support, it has to be implemented in the upstream project first, see lwthiker/curl-impersonate#157 for more details.

**Comment by dolfies** [comment]
> Thank you for your kind words.
> 
> If you are referring to websocket support, it has to be implemented in the upstream project first, see lwthiker/curl-impersonate#157 for more details.

Hello, looks like upstream support has been added. Any update on this? Love the project btw

**Comment by yifeikong** [comment]
Prelimiary support for websocket can be found [here](https://github.com/yifeikong/curl_cffi/actions/runs/6378753897), download and install the wheels. No tests has been added yet, bugs expected.

```py
import asyncio
from curl_cffi import requests

with requests.Session() as s:
    w = s.connect("ws://localhost:8765")
    w.send(b"Foo")
    reply = w.recv()
    print(reply)
    assert reply == b"Hello Foo!"


async def async_examples():
    async with requests.AsyncSession() as s:
        w = await s.connect("ws://localhost:8765")
        await w.asend(b"Bar")
        reply = await w.arecv()
        print(reply)
        assert reply == b"Hello Bar!"


asyncio.run(async_examples())
```

**Comment by yifeikong** [comment]
Experimental websockets support has been added since 0.6.0b7, see the examples folder for more details.
