### ISSUE TITLE
 Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: D:\学习\python\爬虫\venv\lib\site-packages\curl_cffi\cacert.pem CApath: none

### ISSUE THREAD

**Issue by StarDreamAndFeng** [yifeikong/curl_cffi#115]
报错内容：
```
 Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: D:\学习\python\爬虫\venv\lib\site-packages\curl_cffi\cacert.pem CApath: none
```

代码内容：
```
from curl_cffi import requests
r = requests.get("https://tls.browserleaks.com/json", impersonate="chrome110")
print(r.json())
```

pip 安装依赖：
Package    Version
---------- -------
cffi       1.15.1
curl-cffi  0.5.7
pip        23.2.1
pycparser  2.21
setuptools 58.1.0

操作系统信息：
版本	Windows 11 家庭中文版
版本	23H2
安装日期	‎2022/‎10/‎9
操作系统版本	22631.2199
体验	Windows Feature Experience Pack 1000.22672.1000.0

希望各位大佬能够帮帮我，请求一个网页都做不了

**Comment by yifeikong** [comment]
换个没中文的路径可以吗？

来自手机回复


StarDreamAndFeng ***@***.***>于2023年8月30日 周三19:25写道：

**Comment by tahmid-23** [comment]
I'm having trouble with this error on Linux, and I don't have any chinese characters in my paths

**Comment by roaringmyshallowwater** [comment]
cacert.pem的问题，网上有很多解决方法，去官网下一个放在对应的路径里
