### ISSUE TITLE
CurlOpt.IGNORE_CONTENT_LENGTH

### ISSUE THREAD

**Issue by iiLaurens** [yifeikong/curl_cffi#116]
I cannot get the IGNORE_CONTENT_LENGTH option to be working for a server that delivers a wrong chunked content header. Do you have an example?

I have tried something like this:
```python
session = Session(impersonate="chrome110")
session.curl.setopt(curl_cffi.CurlOpt.IGNORE_CONTENT_LENGTH, 1)
res = session.get(url)
```

Could it be that the IGNORE_CONTENT_LENGTH option [requires a long type](https://curl.se/libcurl/c/CURLOPT_IGNORE_CONTENT_LENGTH.html)? When I look at the `setopt` function, it doesn't consider long types as a input option. The value of 1 seems to be converted to an int. Could this be why it is not working?

**Comment by yifeikong** [comment]
`int` should not be the issue here, could you be more specific about the unexpected behavior?

**Comment by yifeikong** [comment]
Close as stale, feel free to reopen it
