### ISSUE TITLE
Cookies lost in some situation

### ISSUE THREAD

**Issue by WhZzi** [yifeikong/curl_cffi#119]
version: 0.5.9b4

```
from curl_cffi import requests

req = requests.Session(impersonate="chrome110")
headers = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36',
}
# problem occur when have host header
problem_headers={
    'Host': '127.0.0.1',
}
req.cookies.set("test", "test")
req.cookies.set("test", "test",domain=".baidu.com")
req.cookies.set("test", "test",domain="127.0.0.1")
# have cookies
res = req.get("https://www.baidu.com", headers=headers, verify=False)
# have cookies
res = req.get("http://127.0.0.1:5000", headers=problem_headers, verify=False)

# requests dont have cookies but req.cookies have
res = req.get("https://www.baidu.com", headers=headers, verify=False)
```

A total of three requests were executed in the code. 
The second request can be any empty page, and there will be an exception in the third request: no cookies will be brought, even if they exist in req.cookies. The problem currently discovered is caused by specifying the host in the headers. 

![1](https://github.com/yifeikong/curl_cffi/assets/41277500/21307afb-8b49-48b6-8701-f51795c3ebd1)
![2](https://github.com/yifeikong/curl_cffi/assets/41277500/798d5d01-6d5b-46a8-bfe4-c8d802eab4a1)
![3](https://github.com/yifeikong/curl_cffi/assets/41277500/8f88d069-7077-43e2-86f2-c204f6d03e7e)

**Comment by WhZzi** [comment]
And one more problem, curl_cffi will change the names of all specified headers to lowercase, like the example from above, the first requests and thrid requests' headers user-agent is lowercase

**Comment by yifeikong** [comment]
Thanks for reporting. However, this bug is tricky to deal with. From the [comments in curl's source code](https://github.com/curl/curl/blob/2683de3078eadc86d9b182e7417f4ee75a247e2c/lib/http.c#L2200-L2205):

```c
/* If we have a given custom Host: header, we extract the host name in
       order to possibly use it for cookie reasons later on. We only allow the
       custom Host: header if this is NOT a redirect, as setting Host: in the
       redirected request is being out on thin ice. Except if the host name
       is the same as the first one! */
    char *cookiehost = Curl_copy_header_value(ptr);
    ...
    aptr->cookiehost = cookiehost;
```

and the cookie host selection [here](https://github.com/curl/curl/blob/2683de3078eadc86d9b182e7417f4ee75a247e2c/lib/http.c#L2841-L2842).

```c
const char *host = data->state.aptr.cookiehost ?
       data->state.aptr.cookiehost : conn->host.name;
```

Although I havn't read through the codebase, my guess is that curl will copy the `Host` to its internal state if it was set. Since we are resuing curl instance for all requests, once you set the `Host` header in the second requset, it's still used in the third request to match cookies, thus none matched.

The solution is simple, either you add `Host` for all or none of your header dicts.

From my experience, I never encountered a situation where I need to add `Host` headers explicitly, the `Host` header would always be added automatically by curl.

**Comment by WhZzi** [comment]
Thank you for your patient reply, this is also a small problem that discovered by accident.
As you said, usually the host is automatically added by the host, so this will not affect normal use.
Thanks again for your reply!

**Comment by yifeikong** [comment]
The `Host` header will be removed if it matches the url, which would bypass this issue for most cases. Try `0.5.9b5` and see if it fixes your problem.

**Comment by WhZzi** [comment]
> The `Host` header will be removed if it matches the url, which would bypass this issue for most cases. Try `0.5.9b5` and see if it fixes your problem.

Everything working good in 0.5.9b5 version

**Comment by WhZzi** [comment]
During the redirection process, this issue reoccurred. Even session.cookies contain the target domain name's cookies, but it will not be carried during the 302 redirect process.   
a.com ->302 ->b.com -> 302 -> c.com
Though b.com and c.com have cookies, but dont carried

**Comment by yifeikong** [comment]
You mannually set cookies for all 3 domains first, then send a request to a.com, which is redirected to b.com, then c.com, but cookies for b.com and c.com were not used in headers, is it so?

**Comment by WhZzi** [comment]
> , verify=False

Yes, the problem can be reproduce as work you said. Following is test code:

flask code:
`from flask import Flask, make_response, redirect

app = Flask(__name__)

@app.route('/set_cookie')
def set_cookie():
    resp = make_response('Cookie set successfully')
    resp.set_cookie('abc', 'abc')
    return resp

# 设置一个重定向的测试路由
@app.route('/redirect_test')
def redirect_test():
    # make_response('redirect successfully')
    return redirect('http://www.baidu.com')

if __name__ == '__main__':
    app.run()
`

reproduce code:
`
from curl_cffi import requests

session= requests.Session(impersonate="chrome110")
session.cookies.set("test", "test")
session.cookies.set("test", "test",domain=".baidu.com")
session.cookies.set("test", "test",domain="127.0.0.1")
proxy_ip="http://127.0.0.1:8888"
session.get("http://127.0.0.1:5000/set_cookie", verify=False,proxies={"http":proxy_ip,"https":proxy_ip})
session.get("https://www.baidu.com", verify=False,proxies={"http":proxy_ip,"https":proxy_ip})
session.get("http://127.0.0.1:5000/redirect_test", verify=False,proxies={"http":proxy_ip,"https":proxy_ip})`

behavior screenshot:
![1](https://github.com/yifeikong/curl_cffi/assets/41277500/d3084d74-307e-4189-bd27-069cc0c93e88)
![2](https://github.com/yifeikong/curl_cffi/assets/41277500/507f0a85-4cb2-4f24-aebf-d72cd0c4b5c0)
![3](https://github.com/yifeikong/curl_cffi/assets/41277500/e79dc172-a5aa-4a44-9575-07ddfa0fadee)

sorry for waiting reply.

**Comment by yifeikong** [comment]
It should be resovled in 0.5.9b6. However, cookies without domains are sent only to the first domain encountered in a redirect chain, they will not be added in the following headers. It's advised that you add domains for every cookie if you want no surprises.

**Comment by WhZzi** [comment]
Thanks for fixing!
