### ISSUE TITLE
Couldn't parse CURLOPT_RESOLVE

### ISSUE THREAD

**Issue by benbut** [yifeikong/curl_cffi#120]
curl_cffi >= 0.5.7

session.curl.setopt(
        option=CurlOpt.RESOLVE,
        value="example.com:443:192.168.243.96"
)

curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 49, Reason: 'Couldn't parse CURLOPT_RESOLVE entry '''. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

**Comment by yifeikong** [comment]
Fixed in `0.5.9b`, a beta version, you can try it with: `pip install curl_cffi==0.5.9b5`
