### ISSUE TITLE
Only version 0.1.5 can be installed

### ISSUE THREAD

**Issue by crazyxw** [yifeikong/curl_cffi#125]
python:3.6.8
os: Linux ecom-darwin-eip 5.4.119-1-tlinux4-0009-eks #1 SMP Sat Apr 15 20:30:49 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
By default, only this version can be installed. Installing a higher version is abnormal。
<img width="941" alt="image" src="https://github.com/yifeikong/curl_cffi/assets/29711470/37669a14-f121-44fb-be54-721af3936437">

**Comment by yifeikong** [comment]
Python 3.6 has been [deprecated](https://devguide.python.org/versions/), the minimal supported version is 3.7.
