### ISSUE TITLE
Why AsyncCurl.process_data takes a long time sometimes?

### ISSUE THREAD

**Issue by r00t-Taurus** [yifeikong/curl_cffi#127]
I create a session via` async with requests.AsyncSession(max_clients=10000) as sess:`
I run my script via` -X dev `flag and sometimes I get Executing <TimerHandle AsyncCurl.process_data created at /usr/local/lib/python3.11/site-packages/curl_cffi/aio.py:42> took 0.847 seconds these are the notifications, sometimes the time can be 1.5s and sometimes 0.2s, what does it depend on and does it block event loop? I also wanted to know if the library has any limitations?

**Comment by yifeikong** [comment]
`max_clients=10000` is kind of a big number here. Do you really need that kind of parallelism?

Under the hood, AsyncSession uses a LifoQueue to track curl instances in flight. By setting `max_clients` to 10k, you are basically having up to 10k requests at the same time.

`process_data` should CPU-bound, it reads message queued by the curl_multi handle until there are no more. If it costs a long time, there must be a lot of contents downloaded and queued.

There is no preset limitation, but I am thinking you might reach a hardware upbound here. Do you see this error **less often** when you set `max_clients` to a lower value?
