### ISSUE TITLE
Chrome 107/110 and firefox 109 support.

### ISSUE THREAD

**Issue by VCDEV1** [yifeikong/curl_cffi#13]
A new release is available at https://github.com/lwthiker/curl-impersonate/releases/tag/v0.5.4 It has the precompiled binaries available! Can you please check and add it? Thank you.

**Comment by VCDEV1** [comment]
Hello. I see the commit https://github.com/yifeikong/curl_cffi/commit/986f3dce737b588eeb71d608004c76033de6cf30 but it shows the status failed for some reason. Can I know if chrome 110 is supported now and working or not? Also if this is added or not in pip?

**Comment by yifeikong** [comment]
There are some build errors for the Windows wheel, so the pypi packages are still not updated for all. It should be fixed soon.

**Comment by yifeikong** [comment]
I have updated the Linux and macOS wheels on PyPI. If you are on these platforms, it's ready to use. I'm still having some issues since building the Windows wheel.

For firefox versions, since they are in separate .so/dll files, it's unlikely to be supported in the near future.

**Comment by yifeikong** [comment]
Windows wheel built.
