### ISSUE TITLE
Plan to support curl-impersonate v0.6.0?

### ISSUE THREAD

**Issue by bratao** [yifeikong/curl_cffi#130]
Hello,
Thank you for this great project @yifeikong. I´m just wondering, and to maybe let you know if you don´t yet, if you do plan to support curl-impersonate v0.6?

It support chrome 116 now

**Comment by yifeikong** [comment]
It seems that the official version has not been released, let's wait for that.

**Comment by yifeikong** [comment]
See updates on #53
