### ISSUE TITLE
[FEATURE] Stream

### ISSUE THREAD

**Issue by hlohaus** [yifeikong/curl_cffi#133]
I created streaming in curl_cffi:

https://github.com/xtekky/gpt4free/blob/main/g4f/requests.py

```py
        async with AsyncSession(impersonate="chrome110", verify=False) as session:
...
            async with session.post(f"{url}/api/chat-process", json=data, headers=headers) as response:
                response.raise_for_status()
                async for line in response.content:
                    print(line)
```

Should it added to the project?

**Comment by yifeikong** [comment]
Hi, I just uploaded a beta version `0.5.10b1` with stream support, details can be found in previous issue #26, closing this as duplicate.
