### ISSUE TITLE
get need Url ,return is   ”Just a moment...“

### ISSUE THREAD

**Issue by MCJace** [yifeikong/curl_cffi#136]
Python Version 3.10
OS: WINDOWS 10

CloudF Ddos dun

```py
import curl_cffi.requests
clink = "https://tls.browserleaks.com/json"
borwtype=['chrome99','chrome100','chrome101','chrome104','chrome107','chrome110','edge99','edge101','safari15_3','safari15_5']
response = curl_cffi.requests.get(clink,impersonate=borwtype[random.randint(1, len(borwtype) - 1)])
print(response .text)

"
{
  "ja3_hash": "cd08e31494f9531f560d64c695473da9",
  "ja3_text": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-23-65281-10-11-35-16-5-13-18-51-45-43-27-17513-21,29-23-24,0",
  "ja3n_hash": "aa56c057ad164ec4fdcb7a5a283be9fc",
  "ja3n_text": "771,4865-4866-4867-49195-49199-49196-49200-52393-52392-49171-49172-156-157-47-53,0-5-10-11-13-16-18-21-23-27-35-43-45-51-17513-65281,29-23-24,0",
  "akamai_hash": "4f04edce68a7ecbe689edce7bf5f23f3",
  "akamai_text": "1:65536;3:1000;4:6291456;6:262144|15663105|0|m,a,s,p"
}
"
```

problem 1:
But I get need Url ,return is :
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title>.................

problem 2:

I am need random,
ja3_hash,ja3_text,ja3n_hash,ja3n_text,akamai_hash,akamai_text

can be adjusted anywhere.

Please help!

**Comment by yifeikong** [comment]
TLS is only one factor of Cloudflare protection, it's not guaranteed to work by simply impersonating the browser fingerprints. Other factors include IP, request rate, etc.

If you need random fingerprints, use the curl option: [`SSL_CIPHER_LIST`](https://curl.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html). But I doubt that you will need it, since most websites uses a allowlist, not a blocklist of fingerprints.

**Comment by MCJace** [comment]
yes , i setting random IP,but Same mistake.     
The problem I suspect is：  
                      Provided browser fingerprints already Cloudflare geted.

**Comment by MCJace** [comment]
> TLS is only one factor of Cloudflare protection, it's not guaranteed to work by simply impersonating the browser fingerprints. Other factors include IP, request rate, etc.
> 
> If you need random fingerprints, use the curl option: [`SSL_CIPHER_LIST`](https://curl.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html). But I doubt that you will need it, since most websites use an allowlist, not a blocklist of fingerprints.

     Is there any better way?

**Comment by yifeikong** [comment]
Search GitHub for "Cloudflare Scrape", there are plenty of tools available.

**Comment by MCJace** [comment]
ok, The mechanism has changed and it seems that serious content is passed through JS. I was doing a test, but found that the request from the source still couldn't go through. The "Cloudflare Scrape" you mentioned doesn't seem to work. Many have been included

**Comment by yifeikong** [comment]
Close as off topic.
