### ISSUE TITLE
[BUG] An error occurs when I use virtual environment packaging

### ISSUE THREAD

**Issue by kalan923** [yifeikong/curl_cffi#137]
My system is Windows 10

The following error occurs when I use the venv virtual environment pip install curl_cffi.

------------------------------------
Using cached cffi-1.16.0-cp39-cp39-win32.whl (172 kB)
Building wheels for collected packages: curl_cffi
  Building wheel for curl_cffi (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for curl_cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [89 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-39
      creating build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\aio.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\build.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\const.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\curl.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\__init__.py -> build\lib.win32-cpython-39\curl_cffi
      creating build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\cookies.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\errors.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\headers.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\models.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\session.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\__init__.py -> build\lib.win32-cpython-39\curl_cffi\requests
      running egg_info
      writing curl_cffi.egg-info\PKG-INFO
      writing dependency_links to curl_cffi.egg-info\dependency_links.txt
      writing requirements to curl_cffi.egg-info\requires.txt
      writing top-level names to curl_cffi.egg-info\top_level.txt
      reading manifest file 'curl_cffi.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'curl_cffi\cacert.pem'
      warning: no files found matching 'curl_cffi\_wrapper.*'
      warning: no files found matching 'curl_cffi\include\curl\*'
      adding license file 'LICENSE'
      writing manifest file 'curl_cffi.egg-info\SOURCES.txt'
\setuptools\command\build_py.py:204: _Warning: Package 'curl_cffi.ffi' is absent from the `packages` configuration.
      !!

              ********************************************************************************
              ############################
              # Package would be ignored #
              ############################
              Python recognizes 'curl_cffi.ffi' as an importable package[^1],
              but it is absent from setuptools' `packages` configuration.

              This leads to an ambiguous overall configuration. If you want to distribute this
              package, please make sure that 'curl_cffi.ffi' is explicitly added
              to the `packages` configuration field.

              Alternatively, you can also rely on setuptools' discovery methods
              (for example by using `find_namespace_packages(...)`/`find_namespace:`
              instead of `find_packages(...)`/`find:`).

              You can read more about "package discovery" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/package_discovery.html

              If you don't want 'curl_cffi.ffi' to be distributed and are
              already explicitly excluding 'curl_cffi.ffi' via
              `find_namespace_packages(...)/find_namespace` or `find_packages(...)/find`,
              you can try to use `exclude_package_data`, or `include-package-data=False` in
              combination with a more fine grained `package-data` configuration.

              You can read more about "package data files" on setuptools documentation page:

              - https://setuptools.pypa.io/en/latest/userguide/datafiles.html

              [^1]: For Python, any directory (with suitable naming) can be imported,
                    even if it does not contain any `.py` files.
                    On the other hand, currently there is no concept of package data
                    directory, all directories are treated like packages.
              ********************************************************************************

      !!
        check.warn(importable)
      creating build\lib.win32-cpython-39\curl_cffi\ffi
      copying curl_cffi\ffi\cdef.c -> build\lib.win32-cpython-39\curl_cffi\ffi
      copying curl_cffi\ffi\shim.c -> build\lib.win32-cpython-39\curl_cffi\ffi
      copying curl_cffi\ffi\shim.h -> build\lib.win32-cpython-39\curl_cffi\ffi
      running build_ext
      generating cffi module 'build\\temp.win32-cpython-39\\Release\\curl_cffi._wrapper.c'
      creating build\temp.win32-cpython-39
      creating build\temp.win32-cpython-39\Release
      building 'curl_cffi._wrapper' extension
      creating build\temp.win32-cpython-39\Release\build
      creating build\temp.win32-cpython-39\Release\build\temp.win32-cpython-39
      creating build\temp.win32-cpython-39\Release\build\temp.win32-cpython-39\Release
      creating build\temp.win32-cpython-39\Release\curl_cffi
      creating build\temp.win32-cpython-39\Release\curl_cffi\ffi
url_cffi._wrapper.c
      curl_cffi\ffi\shim.h(5): fatal error C1083: 无法打开包括文件: “curl/curl.h”: No such file or directory
      error: command 'E:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\BuildTools\\VC\\Tools\\MSVC\\14.29.30133\\bin\\HostX86\\x86\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for curl_cffi
Failed to build curl_cffi
ERROR: Could not build wheels for curl_cffi, which is required to install pyproject.toml-based projects

**Comment by yifeikong** [comment]
Win32 is not currently supported, use a win64 machine, please.

**Comment by kalan923** [comment]
My python：
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
I just used the virtual environment, the normal environment installation is already working fine. But I want to use a virtual environment

**Comment by kalan923** [comment]
I put the curl program into the virtual environment, and it got the following error again.
Using cached cffi-1.16.0-cp39-cp39-win32.whl (172 kB)
Building wheels for collected packages: curl_cffi
  Building wheel for curl_cffi (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for curl_cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [93 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-39
      creating build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\aio.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\build.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\const.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\curl.py -> build\lib.win32-cpython-39\curl_cffi
      copying curl_cffi\__init__.py -> build\lib.win32-cpython-39\curl_cffi
      creating build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\cookies.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\errors.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\headers.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\models.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\session.py -> build\lib.win32-cpython-39\curl_cffi\requests
      copying curl_cffi\requests\__init__.py -> build\lib.win32-cpython-39\curl_cffi\requests
      
------------------------------
curl_cffi._wrapper.c
      build\temp.win32-cpython-39\Release\curl_cffi._wrapper.c(888): warning C4013: “curl_easy_impersonate”未定义；假设外部返回 int.LINK : fatal error LNK1181: 无法打开输入文件“libcurl.lib”

**Comment by yifeikong** [comment]
`pip freeze` in both your none-venv environment and venv environment, and check the diff. There should be some missing packages like `wheel` or `build` or `setuptools`. `curl_cffi` is distributed as binary wheels, your `pip` is compiling it on your machine, which is caused by missing bdist related packages like `wheel`, etc.
