### ISSUE TITLE
当post的data过长时 data超出部分会消失

### ISSUE THREAD

**Issue by Kise1223** [yifeikong/curl_cffi#139]
版本0.5.9 
请求data长度为5000左右 然后fd抓包只会收到4900左右 超出部分会自动被截断，使用原生requests post发送则是正常发出
我用'1111'伪造5000+长度也尝试过了 一样收到的不全

**Comment by yifeikong** [comment]
能贴下代码和目标网站吗？我测试了下本地没问题

**Comment by Kise1223** [comment]
我检查了一下是我这的问题 headers中设置了content length=4900 导致后续的data会按照headers的数量限制自动裁剪，用原生的习惯了 会自己按照提交data长度重新修改content length的值
