### ISSUE TITLE
proxies don't rotate

### ISSUE THREAD

**Issue by mobti100** [yifeikong/curl_cffi#140]
In the documentation, I noticed that proxies should rotate after every request. However, I've been unable to replicate this behavior with my current code

```python
from curl_cffi import requests


session = requests.Session(impersonate='chrome110')


with open('proxies.txt') as f:
    content = f.readlines()
    proxies = {
        "https": f"http://{line.strip().split(':')[2]}:{line.strip().split(':')[3]}@{line.strip().split(':')[0]}:{line.strip().split(':')[1]}"
        for line in content
    }

session.proxies = proxies

for _ in range(4):
    resp = session.get('https://httpbin.org/ip')
    used_proxy = session.proxies.get('https')
    print(f"Used proxy: {used_proxy}")
   ```

**Comment by yifeikong** [comment]
It seems that the error lies in the loading part of your script. What you are trying to do is to load multiple proxies from the text file. But what your code did is simply loading the last proxy. Check `len(proxies)` and you will see.
