### ISSUE TITLE
[BUG] Gets stuck forever in various scenarios with `stream=True`

### ISSUE THREAD

**Issue by coletdjnz** [yifeikong/curl_cffi#141]
**Describe the bug**

Running our project's test suite against `curl_cffi@0.5.10b2` using streaming in sync mode, we encountered many tests getting stuck.

From this I've put together some test cases covering some various conditions where it gets stuck:
https://gist.github.com/coletdjnz/034729c002e39fd97ba8199abf03dff4

One of the common issues appears that in the `perform()` function, the errors raised by curl appear to not be re-raised in the main thread https://github.com/yifeikong/curl_cffi/blob/c0e6fa0df34ea3d0278597279bc2c0744cd70187/curl_cffi/requests/session.py#L596

So if curl errors on request, it gets stuck on
```
            # Wait for the first chunk
            header_recved.wait()  # type: ignore
```
as there would not be any data being sent from curl.

Similarly goes for reading with iter_content, it gets stuck on the queue.get() as no data would be received from curl.

Additionally check out `test_multiple_session_req` and `test_multiple_session_req_read`.
 For some reason, when making multiple subsequent requests with the same session, curl is throwing `Failed to perform, ErrCode: 3, Reason: 'No URL set'.` on these (hence them getting stuck). 

Note that when you run `test_multiple_session_req_read`, it *sometimes* does not get stuck and passes, suggesting there may be a race-condition somewhere?

**Expected behavior**

**Versions**

OS: Linux x64
curl_cffi 0.5.10b2

```
cffi==1.15.1
curl-cffi==0.5.10b2
iniconfig==2.0.0
packaging==23.1
pluggy==1.2.0
pycparser==2.21
pytest==7.4.0
```

**Additional context**
Which session are you using? async or sync? Which loop implementation are you using

Sync

**Comment by yifeikong** [comment]
For the first issue, I guess a `finally` clause is needed to resume running, something like this [c50ec8f](https://github.com/yifeikong/curl_cffi/commit/c50ec8f99ef981a0ee30def923d630fc27568b1c).

For the second issue, you need to **close** the response before the next request. Otherwise, it's indeed a race condition. For convenience, use the `with` statement. See the examples [here](https://github.com/yifeikong/curl_cffi/blob/bugfix/stream-hangs/examples/stream.py).

```py
    with s.stream("GET", URL) as r:
        print("Status: ", r.status_code)
        for chunk in r.iter_content():
            assert r.status_code == 200
            print("CHUNK", chunk)
```

**Comment by coletdjnz** [comment]
Hmm, yes I should've been closing the response in those tests, at least at the end. 
However, I'm under the impression that you should be able to have multiple open responses at once (which requests, etc. allows you to iirc)?

**Comment by yifeikong** [comment]
The problem lies in the fact that the two concurrent requests are sharing the same curl instance. It's not a big change to use seperate curl instances for different ongoing requests, which is how it's implemented in the `AsyncSession`.

However, another behavior needs to be noticed is that the data starts to be buffered in the memory once you fire off the requests. Current implementation is a workaround of the blocking `perform`, by putting which in `ThreadPoolExecutor.submit` to run in a background thread and receiving queued chunks in the main thread.

Thus, if you create two streaming requests at once and only consume from one, the other one might be completely buffered in the memory, which is unlike how `requests/httpx` behaved, where you have control over the rate, and probably not what you presume.

**Comment by coletdjnz** [comment]
Right, I see. That indeed makes it tricky :pensive:

Perhaps for the meantime, how feasible would it be to raise an error in this scenario rather than get stuck? Just thinking of unsuspecting users coming across this and getting confused with it getting stuck.

**Comment by coletdjnz** [comment]
Hmm :thinking:, even with closing the response after each request, I sometimes run into it getting stuck. 

For example, if I change my test to:

```py
    def test_multiple_session_req_read(self):
        # send a second request in a session, reading content of both. Sometimes gets stuck.
        session = curl_cffi.requests.Session()
        r = session.get(f'http://127.0.0.1:{self.http_port}/200', stream=True)
        for _ in r.iter_content():
            continue
        r.close()
        r2 = session.get(f'http://127.0.0.1:{self.http_port}/200', stream=True)
        for _ in r2.iter_content():
            continue
        r2.close()
```
Then sometimes it gets stuck.

I think this may have something to do with the response returning very quickly. For example, I can't reproduce it when requesting an external webpage (such as with your stream tests).

However, if I make curl request a local file (or in my test above, local server), I can.

```py
from curl_cffi import requests
import tempfile

with tempfile.NamedTemporaryFile(delete=False) as f:
    f.write(b"Hello World\n")
    f.close()
    with requests.Session() as s:
        print("\n=====================================================================")
        print("Iterating on a content basis")
        print("=====================================================================\n")
        for i in range(10):
            r = s.get(f'file://{f.name}', stream=True)
            for content in r.iter_content():
                print(f"{i}:CONTENT:{content.decode()}")
            r.close()
```
```
=====================================================================
Iterating on a content basis
=====================================================================

0:CONTENT:Hello World

1:CONTENT:Hello World

2:CONTENT:Hello World

<stuck>
```
That, or I'm overlooking something again :sweat_smile:

**Comment by yifeikong** [comment]
> Hmm 🤔, even with closing the response after each request, I sometimes run into it getting stuck.

If you and the `finally` clause like [here](https://github.com/yifeikong/curl_cffi/commit/c50ec8f99ef981a0ee30def923d630fc27568b1c), does it work?

**Comment by coletdjnz** [comment]
Hmm, sort of. Seems like curl is also raising an error in that case, and it's that no URL set one again :upside_down_face::

```
=====================================================================
Iterating on a content basis
=====================================================================

0:CONTENT:Hello World

Traceback (most recent call last):
  File "/home/coletdjnz/Development/Temporary/curl_cffi_testing/env/c.py", line 15, in <module>
    r.close()
  File "/home/coletdjnz/Development/Temporary/curl_cffi_testing/env/lib/python3.11/site-packages/curl_cffi/requests/models.py", line 115, in close
    self.stream_task.result()  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/coletdjnz/Development/Temporary/curl_cffi_testing/env/lib/python3.11/site-packages/curl_cffi/requests/session.py", line 598, in perform
    c.perform()
  File "/home/coletdjnz/Development/Temporary/curl_cffi_testing/env/lib/python3.11/site-packages/curl_cffi/curl.py", line 251, in perform
    self._check_error(ret, action="perform")
  File "/home/coletdjnz/Development/Temporary/curl_cffi_testing/env/lib/python3.11/site-packages/curl_cffi/curl.py", line 106, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 3, Reason: 'No URL set'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

**Comment by yifeikong** [comment]
Just uploaded a new version `0.5.10b3` with tests [here](https://github.com/yifeikong/curl_cffi/blob/master/tests/unittest/test_requests.py#L481), could you please check if it resolves your issues?

**Comment by coletdjnz** [comment]
> Just uploaded a new version `0.5.10b3` with tests [here](https://github.com/yifeikong/curl_cffi/blob/master/tests/unittest/test_requests.py#L481), could you please check if it resolves your issues?

Sort of.. It's no longer getting stuck which is great. However I'm running into issues with it returning HTTP Status 0 when it some scenarios where it should succeed, or fail with an exception. Let me investigate a bit more

**Comment by coletdjnz** [comment]
For redirect loop test, it appears curl_cffi is only raising the redirect loop error once you start reading the content. If you change your test so it doesn't it fails:

```
def test_stream_redirect_loop(server):
    s = requests.Session()

    url = str(server.url.copy_with(path="/redirect_loop"))
    with pytest.raises(requests.RequestsError) as e:
        s.request("GET", url, max_redirects=5, stream=True)
    assert e.value.code == CurlECode.TOO_MANY_REDIRECTS
    assert e.value.response.status_code == 301  # type: ignore

```

(removing stream=True it works)

**Comment by yifeikong** [comment]
You need to close the response to let the exception be raised, or use the `with` statement.

```diff
def test_stream_redirect_loop(server):
    s = requests.Session()

    url = str(server.url.copy_with(path="/redirect_loop"))
    with pytest.raises(requests.RequestsError) as e:
-       s.request("GET", url, max_redirects=5, stream=True)
+       r = s.request("GET", url, max_redirects=5, stream=True)
+       r.close()
    assert e.value.code == CurlECode.TOO_MANY_REDIRECTS
    assert e.value.response.status_code == 301  # type: ignore
```

**Comment by coletdjnz** [comment]
> You need to close the response to let the exception be raised, or use the `with` statement.
> 
> ```diff
> def test_stream_redirect_loop(server):
>     s = requests.Session()
> 
>     url = str(server.url.copy_with(path="/redirect_loop"))
>     with pytest.raises(requests.RequestsError) as e:
> -       s.request("GET", url, max_redirects=5, stream=True)
> +       r = s.request("GET", url, max_redirects=5, stream=True)
> +       r.close()
>     assert e.value.code == CurlECode.TOO_MANY_REDIRECTS
>     assert e.value.response.status_code == 301  # type: ignore
> ```

Is it feasible for curl_cffi to do that internally when it gets an error (since the response is a dud in this situation)?

That seems like vastly different behaviour then one would expect - can only get the request error (e.g. SSLError) if you close or read the response. On a HEAD request you wouldn't think to read it, and if you want to get response properties (e.g. headers) you can't tell if they are valid or not till you close it.

**Comment by yifeikong** [comment]
I will keep thinking, I'm not satisfied with the behavior, too.

**Comment by yifeikong** [comment]
I tried to raise the exceptions as soon as possible, can you quickly go through [these tests](https://github.com/yifeikong/curl_cffi/blob/master/tests/unittest/test_requests.py#L481-L569) and see if they are aligned with your expected behaviors?

The known issue is that the data transfer still starts once you send a request.

**Comment by coletdjnz** [comment]
> I tried to raise the exceptions as soon as possible, can you quickly go through [these tests](https://github.com/yifeikong/curl_cffi/blob/master/tests/unittest/test_requests.py#L481-L569) and see if they are aligned with your expected behaviors?
> 
> The known issue is that the data transfer still starts once you send a request.

Nice! I think those look fine. 

It might also be worth testing an error that occurs before the request is made e.g. invalid url or option perhaps?

**Comment by yifeikong** [comment]
You mean this?

```py
>>> from curl_cffi import requests
>>> s = requests.Session()
>>> s.get("not valid", stream=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yifei/repos/curl_cffi/curl_cffi/requests/session.py", line 650, in request
    raise first_element
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 3, Reason: ''. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
>>> 
>>> from curl_cffi import CurlOpt
>>> s.curl.setopt(CurlOpt.MAXREDIRS, "three")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yifei/repos/curl_cffi/curl_cffi/curl.py", line 139, in setopt
    c_value = ffi.new("int*", value)
TypeError: an integer is required
```

**Comment by coletdjnz** [comment]
> You mean this?
> 
> ```python
> >>> from curl_cffi import requests
> >>> s = requests.Session()
> >>> s.get("not valid", stream=True)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/yifei/repos/curl_cffi/curl_cffi/requests/session.py", line 650, in request
>     raise first_element
> curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 3, Reason: ''. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
> >>> 
> >>> from curl_cffi import CurlOpt
> >>> s.curl.setopt(CurlOpt.MAXREDIRS, "three")
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/Users/yifei/repos/curl_cffi/curl_cffi/curl.py", line 139, in setopt
>     c_value = ffi.new("int*", value)
> TypeError: an integer is required
> ```

Yeah, well suppose the first one (CURLE_URL_MALFORMAT). By option I was thinking of triggering CURLE_UNKNOWN_OPTION. But, I think that would be redundant if you are testing CURLE_URL_MALFORMAT.

**Comment by yifeikong** [comment]
Available as `0.5.10b4`, except for macOS M1, for which I have to build the wheels manually due to lack of github action instance.

**Comment by coletdjnz** [comment]
This seems to have fixed the issues I was facing. Great work, thanks! :rocket: 

One minor issue I notice is that when making a request for a large resource, even if you don't read any of it, you can't seem to close the response until it has downloaded all of it. Is there a way to make it so when you call close() (or some other opt/method), it will stop the download immediately and close the response?

**Comment by yifeikong** [comment]
Yes, we should be able to do that, signal the `perform` thread to quit when `close` is called.

**Comment by coletdjnz** [comment]
Was looking through https://curl.se/libcurl/c/CURLOPT_WRITEFUNCTION.html

> You can also abort the transfer by returning CURL_WRITEFUNC_ERROR (added in 7.87.0), which makes CURLE_WRITE_ERROR get returned. 

Perhaps this could be useful? (if you are not already using it)


I also notice there is a way to pause a transfer
> If the callback function returns CURL_WRITEFUNC_PAUSE it pauses this transfer. See curl_easy_pause for further details. 

Could this perhaps be used to pause the transfer if nothing is being read? (i.e so it doesn't download the entire response content even if you don't read it or only read a small amount)

**Comment by yifeikong** [comment]
> > You can also abort the transfer by returning CURL_WRITEFUNC_ERROR (added in 7.87.0), which makes CURLE_WRITE_ERROR get returned.

This goes back to the question of upgrading curl version in #53, the current base version is 7.84 if I remember correctly.

> Could this perhaps be used to pause the transfer if nothing is being read? (i.e so it doesn't download the entire response content if you don't read it or only read/iter chunks by a small amount)

`pause` seems to be promising.

**Comment by yifeikong** [comment]
Returning `CURL_WRITEFUNC_PAUSE` causes the `perform` function in the worker thread to freeze  forever, which is not what we want. 😂 

In an ideal world, there should be an option called `CURL_WRITEFUNC_ABORT`, but unfortunately, there is none. The author [recommends](https://curl.se/mail/lib-2008-09/0300.html) returning an error value, which is basically the same as `CURL_WRITEFUNC_ERROR`.

Returning `CURL_WRITEFUNC_ERROR` can do the trick, and yes, it will throw an exception with error code `CURLE_WRITE_ERROR`. Hopefully, you do not need to read any information about the request after you called `close`, do you?

**Comment by coletdjnz** [comment]
> Returning `CURL_WRITEFUNC_PAUSE` causes the `perform` function in the worker thread to freeze forever, which is not what we want. 😂
> 
> In an ideal world, there should be an option called `CURL_WRITEFUNC_ABORT`, but unfortunately, there is none. The author [recommends](https://curl.se/mail/lib-2008-09/0300.html) returning an error value, which is basically the same as `CURL_WRITEFUNC_ERROR`.
> 
> Returning `CURL_WRITEFUNC_ERROR` can do the trick, and yes, it will throw an exception with error code `CURLE_WRITE_ERROR`. Hopefully, you do not need to read any information about the request after you called `close`, do you?

Interesting :thinking: 
> Hopefully, you do not need to read any information about the request after you called close, do you?

Yeah, I think it would be safe to say that after the response is closed you don't need to read anything from curl.

**Comment by yifeikong** [comment]
> Could this perhaps be used to pause the transfer if nothing is being read? (i.e so it doesn't download the entire response content if you don't read it or only read/iter chunks by a small amount)

Download will be aborted as of 0.5.10b5, but I'm not sure it actually works, since the test is very tricky.

https://github.com/yifeikong/curl_cffi/blob/72ff9be839bd75d3276461846ad60ab380c6bbe0/tests/unittest/test_requests.py#L573-L587

**Comment by coletdjnz** [comment]
Appears to be working on our end, great work thanks :smile:

**Comment by yifeikong** [comment]
If there are no other issues, I will release 0.5.10, and move on to new browser support.

**Comment by coletdjnz** [comment]
Sounds good, no issues yet :smiley: . I think this can be closed now and if I run into any more issues will open new issue.
