### ISSUE TITLE
[BUG]使用headers自定义User Agent时，会自动转为小写。

### ISSUE THREAD

**Issue by AboutDark** [yifeikong/curl_cffi#144]
**Describe the bug**
你好，我不清楚这是不是需求导致的问题，我通过headers修改UserAgent时，curl_cffi会自动将我的User Agent转换为小写，导致我访问网站的时候被拦截。希望能够得到解决方案，谢谢。

curl_cffi/requests/headers.py:81行

```py
self._list = [
                (
                    normalize_header_key(k, lower=False, encoding=encoding),
                    normalize_header_key(k, lower=True, encoding=encoding),
                    normalize_header_value(v, encoding),
                )
                for k, v in headers.items()
            ]
```
这里会生成大小写的headers

curl_cffi/requests/headers.py:147行
```py
{key.decode(self.encoding): None for _, key, _ in self._list}.keys()
```
这段代码会自动选择小写的key作为传入值

**Versions**
 - OS: [e.g. windows 10]
 - curl_cffi version [0.5.9]

**Comment by yifeikong** [comment]
这个是从 httpx 抄过来的，确实不太好，下个版本会改掉。

**Comment by AboutDark** [comment]
感谢你的回复，希望能尽快用到新的版本。

**Comment by yifeikong** [comment]
Fixed in 0.5.10b3
