### ISSUE TITLE
重定向时cookie丢失的问题

### ISSUE THREAD

**Issue by johnjgh** [yifeikong/curl_cffi#146]
原生的requests可以传入cookie参数，重定向时会自动带上cookie，但是curl_cffi中的requests传入cookie参数时重定向会丢失cookie，请问这个是什么原因？或者能否解决这一问题

**Comment by yifeikong** [comment]
0.5.9 应该解决这个问题了，你试下

**Comment by johnjgh** [comment]
我刚刚试了一下，好像还是不行，换成原生的requests包是可以的

**Comment by yifeikong** [comment]
你按 issue 模板里的填一下基本信息吧，不然我也不知道哪块的问题

**Comment by yifeikong** [comment]
Close as unclear, feel free to reopen if you have more details to provide.
