### ISSUE TITLE
[BUG] UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position

### ISSUE THREAD

**Issue by lyy077** [yifeikong/curl_cffi#147]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position

Here is my code:

```python
from curl_cffi import requests
resp = requests.get('https://cupoworld.es/tiendas/R')
print(resp.text)
```

I use requests lib can get correct answer, but use curl-cffi get encoding error.

**Comment by yifeikong** [comment]
requests [ignores the decode error](https://github.com/psf/requests/blob/839a8edec37c81a18ac8332cfbd44f44e1ae6206/src/requests/models.py#L930C13-L930C68)

```py
content = str(self.content, encoding, errors="replace")
```

while curl_cffi does not.

The behavior will be changed to the same as requests in the next version. In the meanwhile, you can `decode` by your self.

**Comment by dur3x** [comment]
Can you please give an example for it, I tried to fix it with decode but without success.

**Comment by yifeikong** [comment]
```
r = requests.get("https://example.com")
text = r.content.decode("utf-8", errors="replace")
```
