### ISSUE TITLE
Is it possible to customize timeouts the same way as in aiohttp?

### ISSUE THREAD

**Issue by r00t-Taurus** [yifeikong/curl_cffi#148]
Is it possible to customize timeouts the same way as in aiohttp? Like timeout = aiohttp.ClientTimeout(total=10, connect=2, sock_connect=2)

I noticed that if I use session in both aiohttp and curl-cffii, if there are many proxies with long timeout, then all subsequent requests start to get more time to execute and I would like to weed out such slow proxies immediately as in aiohttp, how can I do it in curl-cffii?

**Comment by yifeikong** [comment]
Actually, you can set separate connect_timeout and read_timeout just like original requests.

```py
from curl_cffi import requests
requests.get("https://example.com", timeout=(1, 3))
```

These two values use libcurl's `CURLOPT_CONNECT_TIMEOUT_MS` and `CURLOPT_TIMEOUT_MS` respectively.

**Comment by r00t-Taurus** [comment]
What about in an asynchronous session?

**Comment by yifeikong** [comment]
The same.


r00t-Taurus ***@***.***>于2023年10月27日 周五17:31写道：

**Comment by r00t-Taurus** [comment]
it doesn't work for me, the timeout error doesn't pop up if you specify through ()

**Comment by yifeikong** [comment]
Can you describe you use case in aiohttp and what you are expecting for curl_cffi in a few lines of code?

**Comment by r00t-Taurus** [comment]
```
async def main():
    async with requests.AsyncSession() as session:
        t1_start = time.perf_counter()
        req = await session.get(
            "https://www.google.com/",
            headers=headers,
            proxies={"https": "http://proxy"},
            impersonate="safari15_5",
            timeout=0.3,
        )
        print(time.perf_counter() - t1_start)


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
```

if you do this, the timeout error is shown

if changed `timeout` to `timeout=(0.3, 0.3)`,then the timeout error does not appear for 0.3s

**Comment by yifeikong** [comment]
Hmm, I'm not getting you point here.

If I use `timeout=1`, the error is:

```
'Failed to connect to proxy port 1080 after 754 ms: Operation timed out'.
```

If I use `timeout=(0.3,1)`, the error is:

```
'Failed to connect to proxy port 1080 after 228 ms: Operation timed out'
```

which aligns with the timeouts given.

**Comment by r00t-Taurus** [comment]
yes, sorry, everything works, it was about the proxy and the fact that I mixed up the parameters in places
