### ISSUE TITLE
I get so many timeout and 403 errors.

### ISSUE THREAD

**Issue by mobti100** [yifeikong/curl_cffi#149]
I get a timeout error in like every four requests
```Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 1 was not closed cleanly before end of the underlying stream'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.```. I also get a lot of ```ERROR 403```, is this an issue of curl_cffi or curl-impersonate?

**Comment by mobti100** [comment]
it doesn't work with `AsyncSession`, right?
`TypeError: AsyncSession.request() got an unexpected keyword argument 'curl_options'`

**Comment by mobti100** [comment]
Some of the errors I keep getting while continually making requests:
`Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 5000 milliseconds with 0 bytes received'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

`Failed to perform, ErrCode: 28, Reason: 'BoringSSL SSL_read: error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER, errno 0'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

`Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 3 was not closed cleanly before end of the underlying stream'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

First 5 min into scraping everything seems fine but then I start to get these errors.

**Comment by yifeikong** [comment]
For asyncio

```py
s = AsyncSession(curl_options=...)
await s.request(...)
```
