### ISSUE TITLE
Custom impersonate profile

### ISSUE THREAD

**Issue by MortonPNZ** [yifeikong/curl_cffi#15]
I have worked with curl impersonate before and for my solution i made some changes in 'curl_chrome104' (https://github.com/lwthiker/curl-impersonate/blob/main/chrome/curl_chrome104) file like i needed (few fixes in headers and ciphers).
Where i can do same changes here? (Or how i can recompile it with my own impersonate file)
My OS now is Win64

**Comment by yifeikong** [comment]
For the cipher list, you can use the `Curl.setopt(CurlOpt.SSL_CIPHER_LIST, your_list)` interface, see the curl docs [here](https://curl.se/libcurl/c/CURLOPT_SSL_CIPHER_LIST.html).
For headers, just set them using `Curl.setopt(CurlOpt.HTTPHEADER)` or `requests.get(headers=your_headers)`.

The wrapper scripts of curl-impersonate contains only regular curl options, they all have corresponding options in `libcurl`, thus in this project.
