### ISSUE TITLE
[BUG] ValueError: not enough values to unpack (expected 2, got 1)

### ISSUE THREAD

**Issue by aremili** [yifeikong/curl_cffi#150]
**Description**
occurs for some URLs when making a simple request

**To Reproduce**
```
response = cffi_requests.head("https://www.verder-online.nl")
```

**Versions**
 - OS: Debian bullseye
 - curl_cffi version 0.5.9

**Comment by yifeikong** [comment]
It turns out the site you mentioned returns a multi-line header, which is something that I was not aware of. It should be fixed in the next release.

**Comment by yifeikong** [comment]
Resolve in 0.5.10b4
