### ISSUE TITLE
How can I impersonate other browsers?

### ISSUE THREAD

**Issue by lxntagram** [yifeikong/curl_cffi#151]
I need to impersonate firefox and other browsers. How can I do that?

**Comment by novitae** [comment]
I might be wrong but, I think you might have to create a file looking like the following, with the properties of the wanted browser, and then you have to add it to your fork of curl-impersonate, and then to the `BrowserType` in `curl_cffi/requests/session.py`.

https://github.com/lwthiker/curl-impersonate/blob/main/chrome/curl_safari15_5

**Comment by yifeikong** [comment]
Duplicate of #59 , let's track the issue there.
