### ISSUE TITLE
`timeout` setting `CURLOPT_TIMEOUT_MS`

### ISSUE THREAD

**Issue by coletdjnz** [yifeikong/curl_cffi#156]
Currently it looks like the `timeout` parameter has two options:

1. single integer to set CURLOPT_TIMEOUT_MS 
2. tuple of (connect timeout to set CURLOPT_CONNECTTIMEOUT_MS, and a value that is added to the connect timeout to set CURLOPT_TIMEOUT_MS)

The parameter is defined as:
>  how many seconds to wait before giving up. 

I would think timeout in this context is to deal with network and server issues (i.e., the connect phase taking to long or the server not responding with any data for an http request in time).

https://github.com/yifeikong/curl_cffi/blob/d0c6c9c08ecf4ab6a1a9e0bd7ea6ff80e562385b/curl_cffi/requests/session.py#L304-L311

I'm opening this as I'm not sure if setting `CURLOPT_TIMEOUT_MS` is the best action - or at least forcing it when wanting to set a connect timeout.

What `CURLOPT_TIMEOUT_MS` appears to do is timeout the entire request and transfer, **even if data is successfully being received from the server**. This is particularly noticeable when using streaming, as you can be processing data coming in and it throws a timeout error just because the transfer is taking too long?

- https://curl.se/libcurl/c/CURLOPT_TIMEOUT.html

Perhaps it may be better to set `CURLOPT_CONNECTTIMEOUT_MS` (and maybe  `CURLOPT_SERVER_RESPONSE_TIMEOUT` if its not a general transfer timeout?)  by default instead? I'll need to double check this, but I believe that is similar behavior to what libraries such as requests do. 

Alternatively, could there be a way of setting the above two while not setting  `CURLOPT_TIMEOUT_MS` with the timeout option?

**Versions**
 - OS: linux 64bit
 - curl_cffi version 0.5.10b4

**Additional context**
Which session are you using? async or sync? Which loop implementation are you using

sync

**Comment by yifeikong** [comment]
I see. You are right, it should be read_timeout instead of overall_timeout, which would also be consistent with requests' behavior.

**Comment by yifeikong** [comment]
One caveat of `CURLOPT_SERVER_RESPONSE_TIMEOUT` is that it can only be set in seconds, not milliseconds.

**Comment by yifeikong** [comment]
I tried to use `CURLOPT_SERVER_RESPONSE_TIMEOUT` and it's not working. It turns out that this option is for FTP and not HTTP, thus not useful here.

**Comment by coletdjnz** [comment]
Darn. In that case I'm not sure if curl has an equivalent read timeout :pensive: 

I suppose what you have done [here](https://github.com/yifeikong/curl_cffi/commit/6116e735cc2e49c76252c8bfd7723f3133bbdf2f) is fine

I did find this workaround: https://unix.stackexchange.com/a/305311

**Comment by yifeikong** [comment]
I started [a thread in the curl mail list](https://curl.se/mail/lib-2023-11/0023.html), it seems that they do not intend to implement it.

**Comment by coletdjnz** [comment]
Interesting, thanks for linking.

I take note of this reply from one of the devs:

> For HTTP we already provide:

>  CURLOPT_CONNECTTIMEOUT
>  CURLOPT_TIMEOUT
>  CURLOPT_LOW_SPEED_LIMIT + CURLOPT_LOW_SPEED_TIME

I think the latter here, which I believe is also what the stackoverflow comment suggests, is perhaps what we want for a read timeout similar to requests? Seems like that might be intended, though slightly annoying it's not super obvious. 

From https://requests.readthedocs.io/en/latest/user/advanced/#timeouts:

> Once your client has connected to the server and sent the HTTP request, the read timeout is the number of seconds the client will wait for the server to send a response. **(Specifically, it’s the number of seconds that the client will wait between bytes sent from the server. In 99.9% of cases, this is the time before the server sends the first byte)**.'

So perhaps set CURLOPT_LOW_SPEED_LIMIT to 1 byte/s or something really low, then the timeout value can set CURLOPT_LOW_SPEED_TIME?

Though, it doesn't support ms values..

**Comment by coletdjnz** [comment]
Works better now, thanks!. I've set CURLOPT_LOW_SPEED_LIMIT and  CURLOPT_LOW_SPEED_TIME my end and that seems to work well for a read timeout too.
