### ISSUE TITLE
tcp/ip request

### ISSUE THREAD

**Issue by havenotdrugs** [yifeikong/curl_cffi#157]
hello. I'm facing a problem. I work with a proxy that has a limit on the number of tcp/ip connections. I use Connection : close headers and also close the session.close(), but it still doesn't help, connections still remain in tcpview Time Wait. If someone has encountered this-I will be glad of your help, thank you!

**Comment by yifeikong** [comment]
TimeWait is the state you would expect when closing a connection, to quote the apache wiki:

> The TIME_WAIT state is a protection mechanism in TCP. The side that closes a socket connection orderly will keep the connection in state TIME_WAIT for some time, typically between 1 and 4 minutes. This happens after the connection is closed. It does not indicate a cleanup problem.

It's really up to the kernel to manage the connection state, not the application. To limit the connection number, it's better to keep using the same connection rather than closing the old connection.
