### ISSUE TITLE
Can't retrieve PRIMARY_IP

### ISSUE THREAD

**Issue by rubmed90** [yifeikong/curl_cffi#158]
`response.curl.getinfo(CurlInfo.PRIMARY_IP)` returns `b''` when using `AsyncSession`.

**Comment by yifeikong** [comment]
The curl handle would be reset once the request was done. I'll add a parameter to specify which extra `info`s you want to collect.

**Comment by yifeikong** [comment]
Fixed in `0.5.10b5`, example:


https://github.com/yifeikong/curl_cffi/blob/72ff9be839bd75d3276461846ad60ab380c6bbe0/tests/unittest/test_requests.py#L603-L608
