### ISSUE TITLE
[BUG] CAN'T PIP INSTALL curl_cffi -> Could not build wheels for curl_cffi

### ISSUE THREAD

**Issue by antonmk4** [yifeikong/curl_cffi#160]
**Describe the bug**
Could not build wheels for curl_cffi error throws once i use pip install curl_cffi.
I've tried googeling and found some general fixxes but none of them worked.

**To Reproduce**
```
pip install curl_cffi
```
Screenshot from terminal:
![UNyGgdTIv3](https://github.com/yifeikong/curl_cffi/assets/69966869/5dd28d7f-f652-4a21-9900-bc6fc92fd2c3)

**Comment by yifeikong** [comment]
Win32 or Python 32-bit on Win64 are not supported. Make sure you are using 64-bit Python on 64-bit Windows.
