### ISSUE TITLE
Expose a curl_cffi `version` constant

### ISSUE THREAD

**Issue by coletdjnz** [yifeikong/curl_cffi#162]
Would it be possible to add and expose a variable somewhere that contains the curl_cffi version?

This would be useful for debugging when curl_cffi is embedded within applications.

E.g. 
- https://github.com/psf/requests/blob/main/src/requests/__version__.py
- https://github.com/urllib3/urllib3/blob/main/src/urllib3/__init__.py#L49
- https://github.com/encode/httpx/blob/master/httpx/__init__.py#L1

**Versions**
 - OS: linux 64 bit
 - curl_cffi version 0.5.10b5
 - `pip freeze` dump

**Additional context**
Which session are you using? async or sync? Which loop implementation are you using

**Comment by yifeikong** [comment]
Here

https://github.com/yifeikong/curl_cffi/blob/c6916b828942d287b17fb19d549c732f663285f5/curl_cffi/__version__.py#L1-L11

**Comment by coletdjnz** [comment]
> Here
> 
> https://github.com/yifeikong/curl_cffi/blob/c6916b828942d287b17fb19d549c732f663285f5/curl_cffi/__version__.py#L1-L11

perfect, thanks!
