### ISSUE TITLE
[BUG] AsyncCurl TimerHandle leaks

### ISSUE THREAD

**Issue by chengjinluo** [yifeikong/curl_cffi#164]
**Describe the bug**
`AsyncCurl` holds `TimerHandle` of `call_later` task invoked by libcurl's timer function and it is not released after the delay function is called.

**To Reproduce**
```
import asyncio
from curl_cffi.requests import AsyncSession

async def main():
    async with AsyncSession() as sess:
        for _ in range(3):
            print('before', len(sess.acurl._timers))
            try:
                await sess.get('http://httpstat.us/200?sleep=5000', timeout=1)
            except:
                pass
            print('after', len(sess.acurl._timers))
        
if __name__ == '__main__':
    asyncio.run(main())
```
Output
```
before 0
after 7
before 7
after 10
before 10
after 14
```

**Expected behavior**
Saved `TimerHandle` should be released after the delay function is called.

**Versions**
 - OS: Ubuntu 20.04 x64
 - curl_cffi version 0.5.9 / 0.5.10
 - `pip freeze` dump

**Additional context**
It seems using a `WeakSet` instead of list for `acurl._timers` could solve this problem.

**Comment by yifeikong** [comment]
Thanks, this might be the same problem as #113, this is a perfect bug report.

**Comment by yifeikong** [comment]
It should've been fixed in 0.6.0b7, feel free to reopen if the leak is not resolved.

**Comment by WendyDReid1901** [comment]
The leaks issue was still there,please help!

**Comment by perklet** [comment]
> The leaks issue was still there,please help!

Can you elaborate on your observations? Thanks.
