### ISSUE TITLE
[BUG] Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'. 

### ISSUE THREAD

**Issue by airplane03** [yifeikong/curl_cffi#165]
It seems like a libcurl Error or a server Error

**To Reproduce**
```
from curl_cffi import requests

url = 'https://booking.jetstar.com/cn/zh/booking/select-flights'
sess = requests.Session()
req = requests.get(url, impersonate="chrome110")
print(req.text)

```
**Expected behavior**

```565     rsp = self._parse_response(c, buffer, header_buffer)
    566     rsp.request = req
--> 567     raise RequestsError(str(e), e.code, rsp) from e
    568 else:
    569     rsp = self._parse_response(c, buffer, header_buffer)

RequestsError: Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 0 was not closed cleanly: INTERNAL_ERROR (err 2)'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

**Comment by coletdjnz** [comment]
I can also reproduce on 0.5.10 (stream, sync). What version are you running?

I was getting this error too the other day with stream=True, sync, 0.5.10b5 on an internal resource. I couldn't repro on any other site so assumed it was a server issue. :thinking:

**Comment by yifeikong** [comment]
The url does not work in my browser, too. So I guess it's a server error.

This error(http/2 stream 0) has been reported many times ever since curl_cffi was published, but I stil can not find a reproducible way to trigger it. Given that the majority users are behind proxies, the situation is even more difficult to deal with. I'm even not sure it's a bug introduced in libcurl, curl-impersonate or curl_cffi, or it's just a server error. Depending on your context, here are some general suggestions for future comers:

1. Try to see if this error was caused by proxies, if so, use better proxies.
2. Force http/1.1 mode.
3. See if the url works in your real browser.
4. Find a stable way to reproduce it, so we can finally fix, or at least bypass it.

@coletdjnz if you can still reproduce this, please continue to comment.

**Comment by airplane03** [comment]
@yifeikong  TKS for suggestion

Yup, this websit is protected with Akamai.

It works fine on my browser(http2, response with a redirect) and postman(http1.1, response a 400 bad requests page).   when I tried it with **curl_cffi** in http/1.1 mode, the requests time out,  acting like the python requests module.  So I guess the libcurl based on openssl is blocked by this website.  

I see the google's boringssl is in the dependency of curl ,  so I wonderd if I replace the libcurl.dll with a new one based on boringssl is feasible.

**Comment by yifeikong** [comment]
Akamai uses http2 fingerprints to detect browsers. This value was not changed for many chrome versions until 117, which curl_cffi does not support by now. It should be resolved by #163 

BoringSSL was compiled staticlly into the .so file, and it's not related to http2 fingerprints.

**Comment by gospider007** [comment]
> @yifeikong TKS for suggestion
> 
> Yup, this websit is protected with Akamai.
> 
> It works fine on my browser(http2, response with a redirect) and postman(http1.1, response a 400 bad requests page). when I tried it with **curl_cffi** in http/1.1 mode, the requests time out, acting like the python requests module. So I guess the libcurl based on openssl is blocked by this website.
> 
> I see the google's boringssl is in the dependency of curl , so I wonderd if I replace the libcurl.dll with a new one based on boringssl is feasible.

@airplane03  Your test method is wrong. The URL you mentioned requires cookies and headers to access. Of course, your browser can succeed if it has complete headers and cookies, but your test code does not have these.

**Comment by airplane03** [comment]
> > @yifeikong TKS for suggestion
> > Yup, this websit is protected with Akamai.
> > It works fine on my browser(http2, response with a redirect) and postman(http1.1, response a 400 bad requests page). when I tried it with **curl_cffi** in http/1.1 mode, the requests time out, acting like the python requests module. So I guess the libcurl based on openssl is blocked by this website.
> > I see the google's boringssl is in the dependency of curl , so I wonderd if I replace the libcurl.dll with a new one based on boringssl is feasible.
> 
> @airplane03 Your test method is wrong. The URL you mentioned requires cookies and headers to access. Of course, your browser can succeed if it has complete headers and cookies, but your test code does not have these.

That dosn't mater, the curl_cffi with impersonate  takes headers itself,  For cookies, the anonymous browser and postman do not have cookies either

**Comment by gospider007** [comment]
> > > @yifeikong TKS for suggestion
> > > Yup, this websit is protected with Akamai.
> > > It works fine on my browser(http2, response with a redirect) and postman(http1.1, response a 400 bad requests page). when I tried it with **curl_cffi** in http/1.1 mode, the requests time out, acting like the python requests module. So I guess the libcurl based on openssl is blocked by this website.
> > > I see the google's boringssl is in the dependency of curl , so I wonderd if I replace the libcurl.dll with a new one based on boringssl is feasible.
> > 
> > 
> > @airplane03 Your test method is wrong. The URL you mentioned requires cookies and headers to access. Of course, your browser can succeed if it has complete headers and cookies, but your test code does not have these.
> 
> That dosn't mater, the curl_cffi with impersonate takes headers itself, For cookies, the anonymous browser and postman do not have cookies either

I don’t know how you tested it. If I open this address directly in an incognito browser, I will be unable to access it. However, if I visit the homepage first and then visit the address you provided, I can access it. When I complete the browser Copy the headers and send the request to the address you provided, and the request library will run normally.

**Comment by airplane03** [comment]
> > > > @yifeikong TKS for suggestion
> > > > Yup, this websit is protected with Akamai.
> > > > It works fine on my browser(http2, response with a redirect) and postman(http1.1, response a 400 bad requests page). when I tried it with **curl_cffi** in http/1.1 mode, the requests time out, acting like the python requests module. So I guess the libcurl based on openssl is blocked by this website.
> > > > I see the google's boringssl is in the dependency of curl , so I wonderd if I replace the libcurl.dll with a new one based on boringssl is feasible.
> > > 
> > > 
> > > @airplane03 Your test method is wrong. The URL you mentioned requires cookies and headers to access. Of course, your browser can succeed if it has complete headers and cookies, but your test code does not have these.
> > 
> > 
> > That dosn't mater, the curl_cffi with impersonate takes headers itself, For cookies, the anonymous browser and postman do not have cookies either
> 
> I don’t know how you tested it. If I open this address directly in an incognito browser, I will be unable to access it. However, if I visit the homepage first and then visit the address you provided, I can access it. When I complete the browser Copy the headers and send the request to the address you provided, and the request library will run normally.

Tks, what an idiot i am, I got the response after taking a header and changing my IP，

**Comment by hxgevan** [comment]
Hi, I got the same problems, that the "curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)" Error always appears,  What Can I do that I can deal with it? please, is there a good idea?

**Comment by yerinNam** [comment]
> Hi, I got the same problems, that the "curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)" Error always appears, What Can I do that I can deal with it? please, is there a good idea?

Hi i'm fixed
```
        response = requests.get(
            url,
            headers = HEADERS,
            proxies={
                "http": proxy_url,
                "https": proxy_url
            },
            http_version=1,   # <- I Added that
            timeout=TOTAL_TIMEOUT,
            impersonate="chrome120",
            verify=False,  
            allow_redirects=True,  
            max_redirects=5,
        )
```

**Comment by robtapia** [comment]
I ran into this issue and after a lot of trial and error, it was fixed for me by adding the `impersonate` parameter to the request.
