### ISSUE TITLE
Unique TLS signatures or JA3 fingerprints with each request

### ISSUE THREAD

**Issue by codeman5000** [yifeikong/curl_cffi#169]
Hello,
i'm not really sure but i like to know if with each request it is possible to create a unique TLS signatures or JA3 fingerprints with the same impersonated browser.
i have this idea that bots after some time block requests if they detect the same fingerprints.
randomizing the available impersonations is not enough, when doing a lot of requests per minute on some sites.

Is it possible to use an impersonation of a browser, lets say Chrome 107 but have a unique fingerprint with each request made with this impersonate version

thx in advance.

**Comment by yifeikong** [comment]
You can create unique fingerprints for each request, but they won't be the same as what browsers use. As far as I know, randomized fingerprints won't work, since the number of known browsers is very limited. If you were a website owner, an allowlist mode makes more sense.

**Comment by yifeikong** [comment]
curl_cffi only help you with TLS fingerprints. For other fingerprints generated in the browser via JavaScript, I think you need to use other projects. One of such techniques is called anti-detect browsers.

**Comment by yifeikong** [comment]
Tracked in #194, closing this one.
