### ISSUE TITLE
Bug: Request header is 'application/x-www-form-urlencoded' but use json as request body

### ISSUE THREAD

**Issue by MagicalBomb** [yifeikong/curl_cffi#17]
Request header is 'application/x-www-form-urlencoded' but use json as request body when requests.post have both json and data parameter,

here are code
```python
requests.post("https://httpbin.org/post", data={"data": 1}, json={"json": 1}).json()
```

here are output
```json
{'args': {},
 'data': '',
 'files': {},
 'form': {'{"json": 1}': ''},
 'headers': {'Accept': '*/*',
  'Accept-Encoding': 'gzip, deflate, br',
  'Content-Length': '11',
  'Content-Type': 'application/x-www-form-urlencoded',
  'Host': 'httpbin.org',
  'X-Amzn-Trace-Id': 'Root=1-6401f15c-60b4e9a57970941f002fe1af'},
 'json': None,
 'origin': '103.116.72.5',
 'url': 'https://httpbin.org/post'}
```

**Comment by yifeikong** [comment]
Why would you use data and json together?

**Comment by MagicalBomb** [comment]
I know that everyone will not use it this way under normal circumstances, which is a little irrelevant. But this is still a strange phenomenon. Can I submit the repair?

**Comment by yifeikong** [comment]
Feel free to submit a PR is you think this should be fixed.
