### ISSUE TITLE
Improve wheel packaging for Windows and Linux

### ISSUE THREAD

**Issue by T-256** [yifeikong/curl_cffi#173]
Currently curl-cffi uses 3rd-parti tools to try include `libcurl` shared library in the wheels.
As there is only one library, I'd recommend put on the same path of `_wrapper.pyd`, so no need to use any patches on built-time (i.e. delvewheel/delocate).

Motivation here is make it easier for package bundlers (e.g. pyinstaller) to include platforms specified shared libraries.

Inspired by [pycairo on Vinayak's research](https://vinayak.io/2020/10/21/day-51-bundling-dlls-with-windows-wheels-the-package-data-way/#:~:text=different%20operating%20systems!-,pycairo,-%24%20unzip%20%2Dl%20pycairo)

**Comment by yifeikong** [comment]
What do you mean by 3rd party tool?

**Comment by T-256** [comment]
I mean delvewheel and delocate.
Actually, I must say `build-time 3rd party tools`.

**Comment by yifeikong** [comment]
They were used for removing `rpath` in so/dll files, and it's standard tools used by `cibuildwheel`.

**Comment by T-256** [comment]
Then I think I didn't understand well about how they actually works.
