### ISSUE TITLE
Installation of curl_cffi

### ISSUE THREAD

**Issue by goldenwww** [yifeikong/curl_cffi#18]
Hi, I am junior programmer of python with no experience of git,
I am geting the error of 

```
  LINK : fatal error LNK1181: cannot open input file 'curl-impersonate-chrome.lib'
  error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.35.32215\\bin\\HostX86\\x64\\link.exe' failed with exit code 1181
```

when I call `pip install --upgrade curl_cffi`
 may you kindly provide a step by step guideline on how to install curl_cffi, like installing curl-impersonate

my environment is x64 windows 10, with MSVC v143 installed, running python 3.10
many thanks!

**Comment by yifeikong** [comment]
Sorry, the latest Windows binary wheel is still not updated, I'm still working on it. In the meanwhile, you could try it in WSL.

**Comment by goldenwww** [comment]
thank you for your great work yifeikong, let me keep check of this to see when the windows binary is available!

**Comment by yifeikong** [comment]
Fixed.
