### ISSUE TITLE
Support TLS secured proxies

### ISSUE THREAD

**Issue by T-256** [yifeikong/curl_cffi#180]
Instead of raise error before making requests:
```py
(CurlError("Failed to perform, ErrCode: 35, Reason: 'error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER'"),)
```

We could wrap CurlError if proxy scheme is HTTPS, then show additional warning:
```py
     warning.warn(
        "You are using httpS proxy, we noticed proxy-server doesn't support HTTPS,"
        " try replace proxy protocol 'https://' with 'http://' and check if it's helping."
     )
```

_Originally posted in https://github.com/yifeikong/curl_cffi/pull/171#discussion_r1429055071_

**Comment by Velocidensity** [comment]
It's worth noting that NordVPN and Surfshark proxies use HTTPS (specifically their browser extension proxies, but they can be used with curl and everything else just fine).

**Comment by T-256** [comment]
FWIW, at here I also think TLS support for all proxies that curl support them:
AFAIK HTTP/SOCKS5[h]/SOCKS4[a]

**Comment by yifeikong** [comment]
Sure, they we should convert it into a warning.
