### ISSUE TITLE
Support `base_url` when initializing sessions

### ISSUE THREAD

**Issue by T-256** [yifeikong/curl_cffi#181]
**Describe alternatives you've considered**]
https://www.python-httpx.org/advanced/#other-client-only-configuration-options

**Comment by yifeikong** [comment]
Would you like to take on this?

**Comment by T-256** [comment]
Sure, but before doing this, I already have PR chains in https://github.com/yifeikong/curl_cffi/pull/178 that are broken to chunks for easier review.
Can we have done them first?
