### ISSUE TITLE
无法绕过腾讯云TencentEdgeOne[BUG]

### ISSUE THREAD

**Issue by klj218** [yifeikong/curl_cffi#184]
代码如下：
response = requests.get('https://gs.sac.net.cn/pages/registration/sac-publicity-report.html', impersonate="chrome101")
print(response.status_code)
print(response.text)

直接返回：
200
<script>var _0x49a6=['wyeCN','4|2|0|3|1','wQzOV','split','iTyzs','pCQRM','cookie','location.href=location.href.replace(/[?|&]tads/,\x20\x27\x27)','WTKkN','bOYDu','dtzqS'];(function(a,c){var b=function(b){while(--b){a['push'](a['shift']());}};b(++c);}(_0x49a6,0x147));var _0x649a=function(a,c){a=a-0x0;var b=_0x49a6[a];return b;};function a(){var a={'WTKkN':32681917,'bOYDu':28618321,'dtzqS':function d(a,b){return a+b;},'wyeCN':1624497290,'pCQRM':function e(a){return a();}};var b=0x0;b+=a[_0x649a('0x0')];b+=a[_0x649a('0x1')];b=a[_0x649a('0x2')](b,a[_0x649a('0x3')]);function c(){var b={'wQzOV':_0x649a('0x4'),'iTyzs':function e(a,b){return a+b;}};var c=b[_0x649a('0x5')][_0x649a('0x6')]('|'),d=0x0;while(!![]){switch(c[d++]){case'0':a+=0xd9;continue;case'1':return a;continue;case'2':a+=0xa4;continue;case'3':a=b[_0x649a('0x7')](a,0x1c0);continue;case'4':var a=0x0;continue;}break;}}return a[_0x649a('0x8')](c),b;}document[_0x649a('0x9')]='__tst_status='+a()+'#;';setTimeout(_0x649a('0xa'),0x4b0);</script>

**Comment by klj218** [comment]
我还参考了sample，使用如下代码去尝试：

**Comment by klj218** [comment]
第一个帖子是返回JS代码，应该是用来判断请求是否来自浏览器；第二种方式应该是命中了反爬虫策略。不知道还有没有办法可以绕过去？

**Comment by yifeikong** [comment]
这个库他只能帮你解决 tls 指纹的问题，js 逆向是解决不了的……

**Comment by klj218** [comment]
感谢，我已找到解决方法。

**Comment by xueyucod** [comment]
> 感谢，我已找到解决方法。

请问是如何绕过去的？我现在处于第一个帖子那样，一直得到JS代码
