### ISSUE TITLE
Merge preprocess scripts into Makefile

### ISSUE THREAD

**Issue by yifeikong** [yifeikong/curl_cffi#197]

**Comment by T-256** [comment]
With merge of #219 only `preprocess\generate_consts.py` remains. I noticed it does nothing. Could it be dropped?

**Comment by yifeikong** [comment]
I'm afraid not, this file generate the const.py file.

**Comment by T-256** [comment]
I noticed It does nothing in ci. Perhaps we could rename `preprocess` to `scripts` and remove it from Makefile?

**Comment by yifeikong** [comment]
Sure, go ahead.
