### ISSUE TITLE
CurlOpt.HTTPHEADER causes an error.

### ISSUE THREAD

**Issue by hairymanmex** [yifeikong/curl_cffi#2]
I have tried various inputs "all strings converted to bytes", but I get "Process finished with exit code 135 (interrupted by signal 7: SIGEMT)" each time I try to use CurlOpt.HTTPHEADER. 

eg. c.setopt(CurlOpt.HTTPHEADER, b'x-access-token: 123')

I believe regular pycurl takes an array as an input for HTTPHEADER. I don't know if that makes any difference.

**Comment by yifeikong** [comment]
See [here](https://github.com/yifeikong/curl_cffi/blob/master/tests/test_setopt.py#L63), the second param should be a list of bytes.

    c.setopt(CurlOpt.HTTPHEADER, [b"Foo: bar"])

You should try the high level `requests/httpx`-like interface first, it's easier to use.

BTW, this repos is mostly unfinished, I guess I could find some time during the Chinese New Year vacation working on it. Stay tuned!

**Comment by hairymanmex** [comment]
Thanks for the immediate response. 

This still give me a type error.

__init__.py", line 57, in setopt
    ret = _curl_cffi.lib.bind_curl_easy_setopt(self._instance, option, c_value)
TypeError: initializer for ctype 'void *' must be a cdata pointer, not list


The only tool left that can access the sites I'm interested in seems to be curl-impersonate lately. Thats how I found your project. I wish I understood a little more. 

Thanks for your work.

**Comment by yifeikong** [comment]
Hi, I just built and uploaded a new version(v0.2.1) on pypi, update your local copy by:

    pip install --upgrade curl_cffi

If you are on Linux or Intel macOS, the `libcurl-impersonate` binary is built-in, it should just work.

Feel free to reopen this issue if it does not work for you.
