### ISSUE TITLE
[BUG] Does not support requests_mock in pytest

### ISSUE THREAD

**Issue by mavic111** [yifeikong/curl_cffi#204]
**Describe the bug**

curl_cffi raise RequestsError when using requests-mock library with pytest.

**To Reproduce**
`conftest.py`
```
import pytest
import requests_mock


@pytest.fixture
def mock_api():
    with requests_mock.Mocker() as m:
        yield m

```

`test_requests.py`
```
import requests
from curl_cffi import requests as curl_cffi_requests

# Using requests library, PASSED
def test_simple(mock_api):
    mock_api.get('https://test.com', text='data')
    assert 'data' == requests.get('https://test.com').text

# Using curl_cffi, FAILED
def test_simple_2(mock_api):
    mock_api.get('https://test.com', text='data')
    assert 'data' == curl_cffi_requests.get('https://test.com').text

```

**Expected behavior**
Passing the test

**Versions**
 - OS: Windows 11 x64
 - curl_cffi version 0.6.0b7

**Additional context**
- https://requests-mock.readthedocs.io/en/1.11.0/pytest.html

**Comment by yifeikong** [comment]
I'm not sure we can make this ever work. From the project's docs:

> The [requests](https://requests.readthedocs.io/) library has the concept of [pluggable transport adapters](https://requests.readthedocs.io/en/latest/user/advanced/#transport-adapters). These adapters allow you to register your own handlers for different URIs or protocols.

> The requests-mock library at its core is simply a transport adapter that can be preloaded with responses that are returned if certain URIs are requested.

curl_cffi.requests is simply mimicing the interface of requests, not its internal designs.
