### ISSUE TITLE
Add 32-bit wheels for Linux and Windows

### ISSUE THREAD

**Issue by T-256** [yifeikong/curl_cffi#207]
Related:
- https://github.com/yifeikong/curl-impersonate/issues/17
- https://github.com/yifeikong/curl-impersonate/pull/18
- https://github.com/yifeikong/curl_cffi/pull/190
- https://github.com/yifeikong/curl_cffi/pull/192

**Comment by yifeikong** [comment]
Sorry, I was going to add it, but I don't have a x86 linux machine to figure out the parameters, which requires to read from `platform.uname`. It should be easy to add, just fill these entries like this:

```
        "system": "Linux",
        "machine": "x86_64",
        "pointer_size": 64,
        "libdir": "~/.local/lib",
        "sysname": "linux-gnu",
        "so_name": "libcurl-impersonate-chrome.so",
        "so_arch": "x86_64"
```

I will come back later when I have time to set up a qemu instance for that.
