### ISSUE TITLE
Is it possible to get ja3 fingerprint randomly?

### ISSUE THREAD

**Issue by pengyanbing84** [yifeikong/curl_cffi#21]

**Comment by yifeikong** [comment]
Yes, with the release of extension permutation in chrome 110, the ja3 fingerprint is already random if you set impersonate=chrome110.

If all you wish is only to set a different fingerprint in different requests, then it’s better to use a library like httpx, which is much more mature than curl_cffi.

However, AFAIK, most websites use an allowlist, not a blocklist to filter out bot traffic. So I don’t think random ja3 fingerprints would work in the wild.
