### ISSUE TITLE
[BUG] Proxy Timeout Error

### ISSUE THREAD

**Issue by yqchilde** [yifeikong/curl_cffi#210]
**Describe the bug**
设置代理报错
`curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 28, Reason: 'Connection timed out after 15012 milliseconds'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details`

**To Reproduce**
```
proxy_url = 'http://user-xxx-region-my:xxx@xxxxx.com'
proxies = {
    'http': proxy_url,
    'https': proxy_url,
}
resp = requests.get('https://ipinfo.io', proxies=proxies, timeout=15)
```

**Expected behavior**
正常使用代理，同样代码在requests上正常返回

**Versions**
 - OS: Windows x64
 - curl_cffi version: 0.6.0b7
 - Python version: 3.10
 - pip install curl_cffi --pre

**Comment by yifeikong** [comment]
Can you verify that this proxy works with other http client like requests?

**Comment by yqchilde** [comment]
Yes，这是使用requests包的返回结果

![image](https://github.com/yifeikong/curl_cffi/assets/36953759/20afb11b-99d2-4eb3-b100-0c9d24596f6d)

**Comment by T-256** [comment]
what's the result when using `http://ipinfo.io` as request url? (non-tls)

**Comment by yqchilde** [comment]
> what's the result when using `http://ipinfo.io` as request url? (non-tls)

Obtain the final landing IP of the proxy IP

**Comment by T-256** [comment]
> Obtain the final landing IP of the proxy IP

For clarification:
```py
proxy_url = 'http://user-xxx-region-my:xxx@xxxxx.com'
proxies = {
    'http': proxy_url,
    'https': proxy_url,
}
resp = requests.get('http://ipinfo.io', proxies=proxies, timeout=15)  # works on plain http host.
resp = requests.get('https://ipinfo.io', proxies=proxies, timeout=15)  # error on tls secured host.
```

We have two kinds of http proxy:
1. CONNECT method aka tunneling
2. full host address on first line of http request

by default curl using CONNECT method: https://everything.curl.dev/usingcurl/proxies/http#https-with-http-proxy
I think your proxy provider not accept CONNECT.

**Comment by jianmaikj** [comment]
same issue

**Comment by Kise1223** [comment]
一样的问题 而且对应的proxies是一样的 主要的区别在于全局环境VPN的不同(因为proxies需要全局海外环境) 
梯子节点1 使用requests正常 使用curl_cffi  超时 
另一家节点2 使用requests正常 使用curl_cffi 正常

![2](https://github.com/yifeikong/curl_cffi/assets/56550271/9a09cd98-579a-40a5-95ef-253937596806)

![1](https://github.com/yifeikong/curl_cffi/assets/56550271/984f6b47-4a08-4380-990c-177a6dc356ce)

如有需要可以协助复现

**Comment by yifeikong** [comment]
@Kise1223 请问用0.5.10有问题吗？

**Comment by Kise1223** [comment]
> @Kise1223 请问用0.5.10有问题吗？

0.5.10 0.6.0b7都试过了 不行 还是一样的结果

**Comment by yifeikong** [comment]
@Kise1223 方便私信发给我有问题的代理测试一下吗？

**Comment by outfielder** [comment]
I am also getting the same error

**Comment by 520Error** [comment]
> @Kise1223方便私信发给我有问题的代理测试一下吗？

注意，这有可能是多线程问题

我经常遇到的错误
ErrCode: 35, Reason: error:10000438: SSL routines: OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
ErrCode: 35, Reason: BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.com:443

查阅了一些资料，有可能是以下导致：
curl默认情况下有两个地方是线程不安全的, 需要特殊处理, 
1，是curl_global_init 这个函数必须单线程调用, 
2，是默认多线程调用https会莫名其妙的挂掉, 以下是网上的解决方案 https://curl.haxx.se/libcurl/c/opensslthreadlock.html https://curl.se/libcurl/c/threaded-ssl.html https://blog.csdn.net/jaylong35/article/details/6988690 https://www.jianshu.com/p/5b43cdd73d58 
3， curl_setopt(curl, CURLOPT_NOSIGNAL, 1L);

**Comment by yifeikong** [comment]
This issue can be caused by many reasons. One of the is curl may not work well with proxies which rotate using usernames. i.e.

```
http://user-XXX-region-my:xxx@xxxxx.com
```
will be different from
```
http://user-YYY-region-my:xxx@xxxxx.com
```
Note that only the username part of the url has changed.

I'm not sure, but it seems that `requests` will open a new connection upon username changes, but `libcurl` will reuse the old ones.

**Comment by yqchilde** [comment]
可能是因为本地Tun模式下的问题，换了个客户端开Tun已经没影响了
