### ISSUE TITLE
[BUG]ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate'.

### ISSUE THREAD

**Issue by Nongzhsh** [yifeikong/curl_cffi#211]
**Describe the bug**
`curl_cffi.curl.CurlError: Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.`

**To Reproduce**
```
session = requests.Session(impersonate='chrome101')
# success
resp1 = session.get('https://github.com')
# error
resp2 = session.get('https://www.tnslgb.com/main/index.do')
```

**Expected behavior**
'https://www.tnslgb.com/main/index.do' should be success

**Versions**
 - OS: WSL2 (Ubuntu 20.04.6 LTS)
 - curl_cffi version: 0.5.10

**Additional context**
- No special characters in the environment path.

**Comment by yifeikong** [comment]
The certificate of this site is invalid. Try open the URL in your browser to verify that. To bypass this, set `verify` to `False`.

```
resp2 = session.get('https://www.tnslgb.com/main/index.do', verify=False)
```

**Comment by Nongzhsh** [comment]
> The certificate of this site is invalid. Try open the URL in your browser to verify that. To bypass this, set `verify` to `False`.
> 
> ```
> resp2 = session.get('https://www.tnslgb.com/main/index.do', verify=False)
> ```

Thank you very much. It works very well.
