### ISSUE TITLE
[BUG] response is empty

### ISSUE THREAD

**Issue by airplane03** [yifeikong/curl_cffi#212]
**Describe the bug**
I requests a url and proxy it to Charles,  the curl_cffi's response is an empty string but the Chales shows that this response has  a content.  Do you have any idea how to solve this problem?

**Comment by yifeikong** [comment]
Could you please add a minimal reproducible code snippet with urls in it?

**Comment by yifeikong** [comment]
The most possible cause is that you are using Charles in mitm mode, i.e. Charles decrypt the https traffic by signing its own CA certificate. For using together with curl_cffi or any other http clients, you have to set `verify=False` to trust that self-signen cert.

Close as stale.
