### ISSUE TITLE
[Feature] New content encoding support (via `content_callback` ?)

### ISSUE THREAD

**Issue by novitae** [yifeikong/curl_cffi#214]
**Is your feature request related to a problem? Please describe.**
Today I tried to send a request that accepts `zstd` as encoding, and got an error telling me that `libcurl [only] understands deflate, gzip, br content encodings`.

<details>
    <summary>The error</summary>
    
    ```
    ---------------------------------------------------------------------------
    CurlError                                 Traceback (most recent call last)
    File /opt/homebrew/lib/python3.11/site-packages/curl_cffi/requests/session.py:929, in AsyncSession.request(self, method, url, params, data, json, headers, cookies, files, auth, timeout, allow_redirects, max_redirects, proxies, verify, referer, accept_encoding, content_callback, impersonate, default_headers, http_version, interface, stream, max_recv_speed)
        928 task = self.acurl.add_handle(curl)
    --> 929 await task
        930 # print(curl.getinfo(CurlInfo.CAINFO))

    CurlError: Failed to perform, ErrCode: 61, Reason: 'Unrecognized content encoding type. libcurl understands deflate, gzip, br content encodings.'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

    The above exception was the direct cause of the following exception:

    File ~/my_example/library/client.py:298, in Session.request(self, method, url, data, params, headers, no_auth, priority, accept_encoding)
        286 async def request(
        287     self,
        288     method: Literal["GET", "POST"],
    (...)
        296     accept_encoding: str = None,
        297 ):
    --> 298     return await self._client.request(
        299         method=method,
        300         url=url,
        301         params=params,
        302         data=data,
        303         headers=self.to_headers(url=url, data=data, no_auth=no_auth, priority=priority, headers=headers),
        304         accept_encoding=accept_encoding or "zstd, gzip, deflate",
        305         http_version=CurlHttpVersion.V2_0,
        306     )

    File /opt/homebrew/lib/python3.11/site-packages/curl_cffi/requests/session.py:934, in AsyncSession.request(self, method, url, params, data, json, headers, cookies, files, auth, timeout, allow_redirects, max_redirects, proxies, verify, referer, accept_encoding, content_callback, impersonate, default_headers, http_version, interface, stream, max_recv_speed)
        932     rsp = self._parse_response(curl, buffer, header_buffer)
        933     rsp.request = req
    --> 934     raise RequestsError(str(e), e.code, rsp) from e
        935 else:
        936     rsp = self._parse_response(curl, buffer, header_buffer)

    RequestsError: Failed to perform, ErrCode: 61, Reason: 'Unrecognized content encoding type. libcurl understands deflate, gzip, br content encodings.'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
    ```
</details>

**Describe the solution you'd like**
I would like to have more content decoders.

**Describe alternatives you've considered**
The main one I've considered is using the `content_callback` argument of the `request` method. However, I don't know how it works at all, and can't really understand based on the code (It would be very nice if you could explain what it is !), but I don't know if this method can read the `Content-Encoding` header from the response. If it can, and also read the body, then I have my solution.

**Comment by novitae** [comment]
I checked how `content_callback` works, but since we don't get the headers, it wouldn't work. Maybe there is a way to disable the automatic decoding of the response's body to avoid those issues, and then decompress it ourselves ? If it is possible, it could be interesting to move the decompression responsibility from libcurl to curl_cffi.

**Comment by yifeikong** [comment]
AFAIK, if you specify the `Accept-Encoding` header, by `headers={...}` or `default_headers=True`, libcurl will automatically decompress the content, there is no option to turn off that behavior.

`libcurl-impersonate` is built with gzip, zlib, brotli support only. If you need to support zstd, you will have to recompile curl-impersonate with zstd support.

This has nothing to do with `content_callback`, it's a callback function receiving the decompressed, but non-decoded raw bytes of the received response.
