### ISSUE TITLE
[Feature] Multipart integration

### ISSUE THREAD

**Issue by adiazma** [yifeikong/curl_cffi#217]
Hello, thank you so much for creating this library, I would like to ask if is there a way to add a Multipart request.

**Comment by yifeikong** [comment]
Do you mean uploading files?

**Comment by adiazma** [comment]
Sorry for the delay, it would be awesome to have an integration between this library and MultipartEncoder
```
from requests_toolbelt import MultipartEncoder
```
And well not just files, something like this with requests:
```
multi = MultipartEncoder({
      'file': (resume.name, resume.data, 'application/pdf'),
      'is_valid': 'true'
}, boundary=boundary)
request = Request('POST', url=url, headers=self.HEADERS, data=multi)
req = self._session.prepare_request(request)
res = self._session.send(req, verify=self.VERIFY, use_proxy=True).json()
```

**Comment by adiazma** [comment]
For example, I am a user of this (library)[https://github.com/FlorianREGAZ/Python-Tls-Client] and I cannot do something like this:

```
multi = MultipartEncoder({
      'file': (resume.name, resume.data, 'application/pdf'),
      'is_valid': 'true'
}, boundary=boundary)
res = session.get(url, headers=headers, data=multi)
```

Would be really awesome if this can be done.

**Comment by yifeikong** [comment]
Support is on the way, see #220 for more details.
