### ISSUE TITLE
如何带客户端证书发送请求

### ISSUE THREAD

**Issue by a2504028411** [yifeikong/curl_cffi#218]
requests代码如下

```
resp = requests.get(url=req_url, headers=_headers, proxies=self._proxies,
                            cert=("certificate/client.crt", "certificate/client.key"),
                            verify=False)
```

curl_cffi 是不支持还是参数名改了
unexpected keyword argument 'cert'

**Comment by yifeikong** [comment]
```
from curl_cffi import requests, CurlOpt

requests.get(url, curl_options={CurlOpt.SSLCERT: "cert", CurlOpt.SSLKEY: "key"})
```

**Comment by T-256** [comment]
Do we need documenting `curl_cffi.const` module? which has these namespaces:

- CurlOpt
- CurlInfo
- CurlMOpt
- CurlECode
- CurlHttpVersion
- CurlWsFlag

**Comment by yifeikong** [comment]
> Do we need documenting curl_cffi.const module?

Yes, and we should add some examples on how to lookup their meaning in curl docs and use them with curl_cffi.

**Comment by a2504028411** [comment]
> ```
> from curl_cffi import requests, CurlOpt
> 
> requests.get(url, curl_options={CurlOpt.SSLCERT: "cert", CurlOpt.SSLKEY: "key"})
> ```

请问能否像pyhttpx这样自定义jar3指纹的方式发送请求
session = pyhttpx.HttpSession(http2=True)
session.ja3 = "771,52393-52392-49195-49199-49196-49200-49161-49171-49162-49172-156-157-47-53-49170-10-4867-4865-4866,0-5-10-11-13-65281-18-43-51,29-23-24-25,0"
resp = session.get(url=req_url, headers=_headers, proxies=self._proxies,verify=False, timeout=60)

**Comment by yifeikong** [comment]
Added `cert` since v0.6.0b9.

```
r = requests.get(url, cert=(client.pem, key.pem))
```
