### ISSUE TITLE
How do I impersonate and add a custom header for a new browser version?

### ISSUE THREAD

**Issue by rjenk22** [yifeikong/curl_cffi#221]
Hello,

I opened an issue in your other repository because I want to impersonate the edge 120 browser. You closed it due to saying that just the user agent needs to match the new browser version as everything else stays the same. 

I wanted to have an impersonate="edge120" option for this project so that it would be easily done, but since you closed the other issue, how would it be possible to impersonate AND override the impersonate Edge header? Would I just impersonate edge101 then override with a new user agent after and it would persist for the whole session like below?

```
s = requests.Session(impersonate="edge101")
s.headers.update({'user-agent': 'edge 120 header here'})
```

**Comment by yifeikong** [comment]
Edge is based on the corresponding version of Chromium, so you should use chrome120 as a base.

```
s = requests.Session(impersonate="chrome120")
s.headers.update({'user-agent': 'edge 120 header here'})
```

**Comment by rjenk22** [comment]
> Edge is based on the corresponding version of Chromium, so you should use chrome120 as a base.
> 
> ```
> s = requests.Session(impersonate="chrome120")
> s.headers.update({'user-agent': 'edge 120 header here'})
> ```

Thank you for the reply. In that case I assume I will also need to update sec-ch-ua and sec-ch-ua-platform to match as well since those are different?

**Comment by yifeikong** [comment]
Yes.

**Comment by rjenk22** [comment]
Thank you very much for your help! Have a good evening.

**Comment by rjenk22** [comment]
@yifeikong I just got around to testing this and I am getting an error for the browser not being supported. I assume this is due to curl-impersonate not having an entry for chrome120. Should I just use 116 as a base and change the headers to match Edge 120 or does an entry need to be added for chrome120 to base edge120 off of?

Thanks

**Comment by Snusmumr1000** [comment]
@rjenk22 what library version are you using?

**Comment by rjenk22** [comment]
> @rjenk22 what library version are you using?

You mentioning that made me figure I needed the beta version. Updated to that and it worked. Thanks :)
