### ISSUE TITLE
[Feature]在async_session结束后继续使用该对象,需要报错

### ISSUE THREAD

**Issue by Mroldpeng** [yifeikong/curl_cffi#222]
```
async with curl_cffi.requests.AsyncSession() as c:
        r1=await c.get('https://www.baidu.com')
        print(r)
r2=await c.get('https://www.baidu.com')
```
在生成r2时, async_session已被关闭, 需要抛出会话已被关闭异常

**Comment by Snusmumr1000** [comment]
Well that's because after you exit the context session (r2 line), then AsyncSession.__aexit__ is called, and everything is being closed.

I think this is not a bug nor an enhancement, but just a misusage.

**Comment by Mroldpeng** [comment]
> 这是因为在你退出上下文会话（r2 行）后，该方法被调用，并且会话正在关闭。`AsyncSession.__aexit__`
> 
> 我认为这不是一个错误，也不是一个增强，而只是一个误用。
> 
> 但是，您可以使用来初始化会话，但它可能会导致忘记关闭它的情况，除非它是某些预期用途（例如，您想在类方法中共享此会话）`AsyncSession.__aenter__`

Although this is a misuse of the code, I think it is still necessary to issue a warning for this operation, otherwise the program will fall into an infinite loop and cannot exit

**Comment by Snusmumr1000** [comment]
So, you suggest throwing some error when one tries to reuse inactive session, do I get you correct?

**Comment by Snusmumr1000** [comment]
Crap, I see, there was some translation problem, now I see that you are suggesting exactly this thing, sorry

**Comment by Snusmumr1000** [comment]
Gotcha, then that's a good proposal, agreed
