### ISSUE TITLE
[BUG]线程安全问题

### ISSUE THREAD

**Issue by 520Error** [yifeikong/curl_cffi#226]
这有可能是多线程问题

我经常遇到的错误
ErrCode: 35, Reason: error:10000438: SSL routines: OPENSSL_internal:TLSV1_ALERT_INTERNAL_ERROR
ErrCode: 35, Reason: BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to xxx.com:443

查阅了一些资料，有可能是以下导致：
curl默认情况下有两个地方是线程不安全的, 需要特殊处理,
1，是curl_global_init 这个函数必须单线程调用,
2，是默认多线程调用https会莫名其妙的挂掉, 以下是网上的解决方案
https://curl.haxx.se/libcurl/c/opensslthreadlock.html
https://curl.se/libcurl/c/threaded-ssl.html
https://blog.csdn.net/jaylong35/article/details/6988690
https://www.jianshu.com/p/5b43cdd73d58
3， curl_setopt(curl, CURLOPT_NOSIGNAL, 1L);

**Comment by yifeikong** [comment]
> This function is thread-safe since libcurl 7.84.0

我们用的最低版本恰好是 7.84，所以 curl_global_init 应该没问题。

Session 中默认使用的是 thread_local 的 curl handle，应该也不会导致死锁吧。

NOSIGNAL 似乎是用来解决 DNS 问题的，你上边提到的错误跟这个无关。

如果有能稳定复现这些问题的代码，还请贴上来。

**Comment by yifeikong** [comment]
`TLSV1_ALERT_INTERNAL_ERROR` 这个错误可能跟你的目标站点的 TLS 配置有关，你可以试下更换不同的 impersonate 参数，看看哪个是有问题的。

**Comment by Nongzhsh** [comment]
> `TLSV1_ALERT_INTERNAL_ERROR` 这个错误可能跟你的目标站点的 TLS 配置有关，你可以试下更换不同的 impersonate 参数，看看哪个是有问题的。
> 
> 也有[文章](https://hyperzsb.io/posts/git-ssl-error/)指出，跟国内的互联网环境可能有关。

感觉大概率是网络问题，有时候本机开启Clash客户端也会影响。
