### ISSUE TITLE
[BUG]经常无响应

### ISSUE THREAD

**Issue by jifeilong9** [yifeikong/curl_cffi#232]
**Describe the bug**
经常在获取到数据后卡死在某个位置一直无响应，我可以看到r.text已经获取到网站的数据了，但是走到return html后失去响应，感觉时关闭http请求相关资源出了问题

**To Reproduce**
```
def get_html():
    url = "https://www.oocl.com/_catalogs/masterpage/AutoCompleteVesselTracking.aspx?type=vesselname&keyWord=oocl&scac=oolu"
    html = ''
    r = requests.get(
          url,
          impersonate="chrome110"
      )
    html = r.text
    return html
```

**Expected behavior**

**Versions**
 - OS: [e.g. windows11]
 - curl_cffi version [0.6.0b7]
 - `pip freeze` dump

**Additional context**
- Which session are you using? async or sync?
- 同步，在fastapi中使用
- If using async session, which loop implementation are you using?

**Comment by jifeilong9** [comment]
> > 我可以看到r.text已经获取到网站的数据了
> 
> ```
> html = r.text
> return html
> ```
> 
> 麻烦具体说一下什么叫「可以看到」，是打出来日志了？这两行你是卡在哪一行了？

就是网站已经返回数据了，但是调试走过return html就卡住了

**Comment by yifeikong** [comment]
那不应该吧，close 在 `requests.get` 返回的时候就调用了。

**Comment by yifeikong** [comment]
```
requests.get(url, proxy="http://user:pass@proxy.com:3128")
```
