### ISSUE TITLE
[BUG] 关闭 Response 报错

### ISSUE THREAD

**Issue by KKKKKKKEM** [yifeikong/curl_cffi#239]
**Describe the bug**
关闭 Response 报错

**Expected behavior**
请求完毕后尝试关闭 response 时报错

**Versions**
 - OS:  Mac
 - curl_cffi version 0.5.10

**复现代码**

```python
from curl_cffi import requests

url = "https://shopee.com.mx/api/v4/shop/rcmd_items?bundle=shop_page_category_tab_main&limit=100&offset=0&shop_id=796633299&sort_type=13&upstream=pdp"

response = requests.request("GET", url)

response.close()



```
![image](https://github.com/yifeikong/curl_cffi/assets/30348060/6b88bab6-f534-4dc3-933b-1ced6c2ea586)

**Comment by yifeikong** [comment]
Stream 模式的 response 才需要关闭，多此一举了……

**Comment by KKKKKKKEM** [comment]
感谢解答，不过我这边是为了保证逻辑一直进行封装的，所以没有考虑什么情况下才关闭

**Comment by yifeikong** [comment]
Fixed in v0.6.0, close for non-stream mode is a noop now.
