### ISSUE TITLE
No headers by default

### ISSUE THREAD

**Issue by tobias-talaj** [yifeikong/curl_cffi#242]
**Description of the bug**
If I understand correctly there should be some default headers if I'm supposed to impersonate a certain browser. However printing put `session.headers` or `response.request.headers` gives empty Headers object. When I uncomment `print("header lines", header_lines)` in session.py in line 281 it gives an empty list too.

**To Reproduce**
```
from curl_cffi import requests

session = requests.Session(impersonate="chrome110")

response = session.get('https://www.google.com/')
print(session.headers)
print(response.request.headers)
```

**Expected behavior**
I would expect to see some headers by default.

**Versions**
 - OS: Debian Bookworm x64
 - curl-cffi==0.5.10

**Additional context**
- Sync session

I hope this makes sense.
Thanks,
Tobiasz

**Comment by yifeikong** [comment]
The default headers are implemented on C side, i.e. in upstream `curl-impersonate`. They are added when `impersonate` is set automatically.
