### ISSUE TITLE
[ERROR] How to fix this problem?

### ISSUE THREAD

**Issue by suzo36** [yifeikong/curl_cffi#243]
I want to use this lib, but I get this error
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 77, Reason: 'error setting certificate verify locations:  CAfile: C:\Users\Силоренко Евгений\AppData\Roaming\Python\Python311\site-packages\curl_cffi\cacert.pem CApath: none'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
MyCode:
`from curl_cffi import requests

r = requests.get("https://www.cian.ru/sale/flat/295113174/", impersonate="chrome110")

print(r.json())
`

**Comment by yifeikong** [comment]
Use a pur ASCII path, other unicode characters like Russian will cause this problem.
