### ISSUE TITLE
Memory leak Session

### ISSUE THREAD

**Issue by hairymanmex** [yifeikong/curl_cffi#25]
I ran into a memory leak when using Session.

using tracemalloc I traced it to line 123 in `__init__.py`.

    func(ffi.buffer(binary_string.content, binary_string.size)[:])

Also found I could solve the issue by limiting the size of `self._write_callbacks`. around line 56.
I added this as a temporary measure.

```
if len(self._write_callbacks) > 4:
    del self._write_callbacks[0]
    self._write_callbacks.append((target_func, c_value))
else:
    self._write_callbacks.append((target_func, c_value))
```

not sure if there is more to it though.

**Comment by yifeikong** [comment]
Yes, it's indeed a bug. Will fix soon. Thanks for reporting!

**Comment by yifeikong** [comment]
This bug should be fixed now, I changed write callback to what it should be like in native curl. Please feel free to reopen this issue if it's still not working.
