### ISSUE TITLE
[BUG]ErrCode: 18, Reason: 'transfer closed with outstanding read data remaining'

### ISSUE THREAD

**Issue by imdly2022** [yifeikong/curl_cffi#252]
Traceback (most recent call last):
  File "C:\python\Lib\site-packages\curl_cffi\requests\session.py", line 812, in request
    c.perform()
  File "C:\python\Lib\site-packages\curl_cffi\curl.py", line 274, in perform
    self._check_error(ret, "perform")
  File "C:\python\Lib\site-packages\curl_cffi\curl.py", line 128, in _check_error
    raise error
curl_cffi.curl.CurlError: Failed to perform, ErrCode: 18, Reason: 'transfer closed with outstanding read data remaining'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\ad\Adcanny\adcanny6422.py", line 125, in <module>
    running()
  File "C:\ad\Adcanny\adcanny6422.py", line 51, in running
    respon = reqs.get(url=url)
  File "C:\python\Lib\site-packages\curl_cffi\requests\session.py", line 816, in request
    raise RequestsError(str(e), e.code, rsp) from e
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 18, Reason: 'transfer closed with outstanding read data remaining'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

**Comment by yifeikong** [comment]
Could you please provide the code and urls you were using?

**Comment by yifeikong** [comment]
@morganwu277 Could you please share some system info at least? like the OS, python, and curl_cffi version, are you using `async` or stream? If the url can be provided, it's even better.

**Comment by yifeikong** [comment]
Are you using proxy?

**Comment by yifeikong** [comment]
Then I guess what you found is the best solution for now. Thanks for posting it here!

`libcurl(-impersonate)` uses http/2 by default, especially when impersonating. The root cause can be bugs either in libcurl's http/2 implementation or the server's. Considering the binary nature and complexity of http/2, downgrading to http/1.1 is the last resort you can try.

For future viewers, here is how you use http/1.1 in `curl_cffi`:

```py
    from curl_cffi import requests, CurlHttpVersion

    r = requests.get("https://example.com", http_version=CurlHttpVersion.v1_1)
```
