### ISSUE TITLE
[BUG] session timeout does not work

### ISSUE THREAD

**Issue by 5j9** [yifeikong/curl_cffi#253]
**Describe the bug**
If you set timeout on session (e.g. `session = curl_cffi.requests.Session(timeout=1.0)`), it will have no effect when you call `session.request`, unless you pass the timeout again explicitly.

**To Reproduce**
```python
curl_cffi.requests.Session(timeout=0.001).get('https://google.com')  # works, but should fail

curl_cffi.requests.Session().get('https://google.com', timeout=0.001)  # fails as expected
curl_cffi.requests.Session(timeout=0.001).get('https://google.com', timeout=0.001)  # fails as expected
```

**Expected behavior**
Timeout set on session should be applied to individual requests when there is no explicit timeout set for them.

**Versions**
 - OS: windows 10 x64
 - curl_cffi version 0.6.0
 - `pip freeze` dump (too long, I don't think it's important, let me know if you need it though)

**Comment by yifeikong** [comment]
Fixed in 0.6.1
