### ISSUE TITLE
[BUG] This event loop is already running 

### ISSUE THREAD

**Issue by solo-xwz** [yifeikong/curl_cffi#254]
**Describe the bug**
get error '**This event loop is already running**' when using async session and runing it with `asyncio.run`, but it works normally with version 0.5.10

**To Reproduce**
```
# Minimal reproducible code, if possible.
# target websites, and request parameters.
```

**Expected behavior**

**Versions**
 - OS: Win11 & Ubantu
 - curl_cffi version: 0.6.0
 - `pip freeze` dump

**Additional context**
- Which session are you using? async

**Comment by yifeikong** [comment]
Fixed in 0.6.1
