### ISSUE TITLE
ErrCode: 6, Reason: 'Could not resolve host: www.amazon.com'

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#257]
Failed to perform, ErrCode: 6, Reason: 'Could not resolve host: www.amazon.com'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

**Comment by yifeikong** [comment]
It seems to be DNS issue. Does it work on other network connections?

**Comment by BhardwajAnshul** [comment]
The issue is not permanant. It used to work on the same network. but I am seeing this a lot now. 

Earlier it was able to resolve the DNS issue after few attemps.

**Comment by yifeikong** [comment]
Does it start to work immediately once after you restart the curl_cffi script?

**Comment by BhardwajAnshul** [comment]
If i run the script again, it does work i think. It doesnt work only when i restart the router without stopping the script.

**Comment by BhardwajAnshul** [comment]
<img width="439" alt="image" src="https://github.com/yifeikong/curl_cffi/assets/70947798/15788941-4866-41e9-8da1-f251d6b684f4">


Could the "Operation timed out" warning be related to the issue I'm experiencing? I've also noticed this warning appears shortly before the problem occurs.

**Comment by BhardwajAnshul** [comment]
Restarting the script is not a viable solution, as it is designed to run continuously for days without interruption. I cannot be present to manually restart the script each time this error occurs.

**Comment by yifeikong** [comment]
If you were restarting the router, of course the request will be timed out.

Does setting another DNS work?

**Comment by BhardwajAnshul** [comment]
The timeout errors are not related to restarting the router. Once a timeout error occurs, subsequent requests continue to experience this error as well. Typically, these errors are resolved automatically after several attempts, but lately, they have been persistent and continuous.

```
Failed to perform, ErrCode: 28, Reason: 'Operation timed out after 10006 milliseconds with 0 bytes received'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

The above error was for a request that timed out without receiving a single byte.

And is there a way to set DNS in curl_cffi?

**Comment by yifeikong** [comment]
You should set your DNS on the OS level. For Linux, it's something like `/etc/resolv.conf`, for macOS and Windows, you can do this via the GUI interface.
