### ISSUE TITLE
libcurl-impersonate download should check for libcurl release version 

### ISSUE THREAD

**Issue by bjia56** [yifeikong/curl_cffi#262]
Currently, libcurl-impersonate is downloaded into ~/.local on Linux, and the download is skipped if libcurl-impersonate.so already exists. This may be an issue if libcurl-impersonate is updated but the build runs on a system that already has an old library.

**Comment by bjia56** [comment]
With recent static linking changes, perhaps we can just download to a temp dir

**Comment by yifeikong** [comment]
I agree, we should download it to `tempfile.mkdtemp()`.
