### ISSUE TITLE
Bypassing Cloudflare

### ISSUE THREAD

**Issue by saajnn** [yifeikong/curl_cffi#266]
**Versions**
 - OS: [e.g. linux x64]
 - curl_cffi version [e.g. [v0.6.2]
 - pip install curl_cffi --upgrade --pre

**Additional context**
Using curl_cffi to fetch HTML content from site behind Cloudflare.
Worked well  at first, but only for a few days. Then the 500 error page started coming back as response. if changed impersonate="chromexxx" to impersonate="edgexxx" , but again, that only worked for a few more days.

**Comment by yifeikong** [comment]
Please read the [docs](https://curl-cffi.readthedocs.io/en/latest/faq.html#can-i-bypass-cloudflare-with-this-project-or-any-other-specific-site) before asking a question.

> Can I bypass Cloudflare with this project? or any other specific site.
> Short answer is: it depends.
> 
> TLS and http2 fingerprints are just one of the many factors Cloudflare considers. Other factors include but are not limited to: IP quality, request rate, JS fingerprints, etc.
> 
> There are different protection levels for website owners to choose. For the most basic ones, TLS fingerprints alone maybe enough, but for higher levels, you may need to find a better proxy IP provider and use browser automation tools like playwright.
> 
> If you are in a hurry or just want the professionals to take care of the hard parts, you can consider the commercial solutions from our sponsors:
> - [Scrapfly](https://scrapfly.io/?utm_source=github&utm_medium=sponsoring&utm_campaign=curl_cffi) is an enterprise-grade solution providing Web Scraping API that aims to simplify the scraping process
> 
> - [Yescaptcha](https://yescaptcha.com/i/stfnIO), captcha resolver and proxy service for bypassing Cloudflare.
> 
> - [ScrapeNinja](https://scrapeninja.net/?utm_source=github&utm_medium=banner&utm_campaign=cffi), Managed web scraping API.
> 
> For details, see the Sponsor section on front page.
