### ISSUE TITLE
[BUG] Install failed with Qinglong Docker image

### ISSUE THREAD

**Issue by sparezgw** [yifeikong/curl_cffi#272]
**Error occurred during installation in Docker Qinglong panel. Initially, it reported the absence of gcc. After installing gcc, the error message is as follows:**

`Looking in indexes: https://pypi.doubanio.com/simple/
Collecting curl_cffi
  Downloading https://mirrors.cloud.tencent.com/pypi/packages/0c/48/8c79ea18592590eaf49c051398c911dca43482bee22688516539251dcbb9/curl_cffi-0.6.2.tar.gz (122 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.3/122.3 kB 1.4 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: still running...
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Requirement already satisfied: certifi in /usr/local/lib/python3.10/site-packages (from curl_cffi) (2023.11.17)
Collecting cffi>=1.12.0
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/ee/68/74a2b9f9432b70d97d1184cdabf32d7803124c228adef9481d280864a4a7/cffi-1.16.0-cp310-cp310-musllinux_1_1_x86_64.whl (465 kB)
Collecting pycparser
  Using cached https://mirrors.cloud.tencent.com/pypi/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl (118 kB)
Building wheels for collected packages: curl_cffi
  Building wheel for curl_cffi (pyproject.toml): started
  Building wheel for curl_cffi (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error
  
  × Building wheel for curl_cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      .so files alreay downloaded.
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-cpython-310
      creating build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/_asyncio_selector.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/aio.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/const.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/__version__.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/__init__.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      copying curl_cffi/curl.py -> build/lib.linux-x86_64-cpython-310/curl_cffi
      creating build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/exceptions.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/errors.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/cookies.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/headers.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/session.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/__init__.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/websockets.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      copying curl_cffi/requests/models.py -> build/lib.linux-x86_64-cpython-310/curl_cffi/requests
      running egg_info
      writing curl_cffi.egg-info/PKG-INFO
      writing dependency_links to curl_cffi.egg-info/dependency_links.txt
      writing requirements to curl_cffi.egg-info/requires.txt
      writing top-level names to curl_cffi.egg-info/top_level.txt
      reading manifest file 'curl_cffi.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'curl_cffi.egg-info/SOURCES.txt'
      copying curl_cffi/libcurl-impersonate-chrome.so.4 -> build/lib.linux-x86_64-cpython-310/curl_cffi
      running build_ext
      generating cffi module 'build/temp.linux-x86_64-cpython-310/curl_cffi._wrapper.c'
      creating build/temp.linux-x86_64-cpython-310
      building 'curl_cffi._wrapper' extension
      creating build/temp.linux-x86_64-cpython-310/build
      creating build/temp.linux-x86_64-cpython-310/build/temp.linux-x86_64-cpython-310
      creating build/temp.linux-x86_64-cpython-310/ffi
      gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -Iinclude -Iffi -I/usr/local/include/python3.10 -c build/temp.linux-x86_64-cpython-310/curl_cffi._wrapper.c -o build/temp.linux-x86_64-cpython-310/build/temp.linux-x86_64-cpython-310/curl_cffi._wrapper.o
      In file included from build/temp.linux-x86_64-cpython-310/curl_cffi._wrapper.c:57:
      /usr/local/include/python3.10/Python.h:11:10: fatal error: limits.h: No such file or directory
         11 | #include <limits.h>
            |          ^~~~~~~~~~
      compilation terminated.
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for curl_cffi
Failed to build curl_cffi
ERROR: Could not build wheels for curl_cffi, which is required to install pyproject.toml-based projects`

**Comment by yifeikong** [comment]
Which variant are you using? Debian or Alpine? If you are using the default Alpine based image of QingLong, you need to use the latest beta:

```
pip install curl_cffi==0.6.3b1
```

**Comment by sparezgw** [comment]
Thank you, the issue has been resolved.
