### ISSUE TITLE
无法上传文件[BUG]

### ISSUE THREAD

**Issue by huxuyf** [yifeikong/curl_cffi#273]
```python
from curl_cffi import requests,CurlMime

url = "要上传的网页"
file_path = "D\\我的图片.jpg"
content_type = "image/jpeg"
mime = CurlMime()
mime.addpart(name='xxxx.jpg',content_type=content_type,filename='yyyy.jpg',local_path=file_path)
response = requests.request('POST', url, multipart=mime)
```
脚本比较简单，在运行到倒数第二行就报错了。
> 
![image_2024-03-13_21-24-01](https://github.com/yifeikong/curl_cffi/assets/7380710/fbe8d766-e094-49b7-9e9d-76fd87c97a58)

出错的代码在这个地方：
![image_2024-03-13_21-25-08](https://github.com/yifeikong/curl_cffi/assets/7380710/0a2059b3-4cde-4553-ac24-dbe962258a85)

`curl_mime_filedata(part,local_path)` 这个代码不知道还有什么条件？

另外，curl_cffi的requests为什么不跟requests一样支持files参数？

**Comment by yifeikong** [comment]
应该是不支持中文路径，你换个英文路径试试呢？requests 的 files 参数太乱了，好几种不同的 tuple，没法加类型注解，所以干脆自定义了一种格式。

**Comment by huxuyf** [comment]
> 应该是不支持中文路径，你换个英文路径试试呢？requests 的 files 参数太乱了，好几种不同的 tuple，没法加类型注解，所以干脆自定义了一种格式。

试了一下还真是如此，没有中文路径的情况下是可以构建mime了。不过，上传文件遇到中文路径应该比较常见的。还有之前看到路径已经encode了，根本没想到还会有问题。
