### ISSUE TITLE
Retrieving Full Cookie Attributes with curl_cffi for Chrome Driver

### ISSUE THREAD

**Issue by mobti100** [yifeikong/curl_cffi#280]
I am currently using the `curl_cffi` library to make HTTP requests in an asynchronous manner. My goal is to retrieve cookies from a response and then set them in a Chrome driver. The Chrome driver expects cookies in a specific format, which includes attributes such as `domain`, `expiry`, `httpOnly`, `name`, `path`, `sameSite`, `secure`, and `value`.

However, with `curl_cffi`, I am only able to retrieve the `name` and `value` of the cookies. I need to access the full set of cookie attributes as required by the Chrome driver.

I expect to be able to retrieve a complete set of cookie attributes (`domain`, `expiry`, `httpOnly`, `name`, `path`, `sameSite`, `secure`, `value`) after making a request with `curl_cffi`.

**Comment by deedy5** [comment]
See if this helps you - https://github.com/daijro/browserforge
But I haven't checked to see if it works

**Comment by coletdjnz** [comment]
you can use a cookiejar to get these values

`cookies` supports a cookiejar

https://docs.python.org/3/library/http.cookiejar.html#module-http.cookiejar
