### ISSUE TITLE
doesn't work in android[BUG]

### ISSUE THREAD

**Issue by krolaper** [yifeikong/curl_cffi#283]
**Describe the bug**
after packaging the application via buildozer and running it on Android 10, here is the log.
The test was carried out with versions 0.6.2 and 0.6.3b.

When I try to specify _cffi_backend before packaging, buildozer of course does not find and does not understand what kind of library it is.

**Logcat**
```
.buildozer/android/platform/build-arm64-v8a/build/python-installs/AIGodOSINT/arm64-v8a/curl_cffi/__init__.py", line 16, in <module>
03-31 08:57:18.455 28275 28335 I python  :  ModuleNotFoundError: No module named '_cffi_backend'
```

**Versions**
 - OS: [linuxmint 21.3]
 - curl_cffi version [0.6.2 and 0.6.3b1]

I am waiting and really hoping that you will be able to implement a working version for Android arm64. With workarounds it is very difficult to implement something working

**Comment by yifeikong** [comment]
Let's track this in #248
