### ISSUE TITLE
Pyinstaller Error

### ISSUE THREAD

**Issue by mstplm** [yifeikong/curl_cffi#29]
Pyinstaller Error in version 0.4.0: 
Traceback (most recent call last):
  File "lt1.py", line 8, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 540, in exec_module
  File "curl_cffi\__init__.py", line 39, in <module>
ImportError: DLL load failed while importing _wrapper:

**Comment by yifeikong** [comment]
Please see if this section in the [README](https://github.com/yifeikong/curl_cffi#pyinstaller-modulenotfounderror-no-module-named-_cffi_backend) helps.

**Comment by mstplm** [comment]
> Please see if this section in the [README](https://github.com/yifeikong/curl_cffi#pyinstaller-modulenotfounderror-no-module-named-_cffi_backend) helps.

Yes, I tried to package the program with this command: pyinstaller -F .\example.py --hidden-import=_cffi_backend --collect-all curl_cffi, but the problem still persists。

**Comment by yifeikong** [comment]
Could you please share more details so that I can try compile on my laptop?
