### ISSUE TITLE
[BUG]请求一段时间之后就会疯狂报错

### ISSUE THREAD

**Issue by irwinai** [yifeikong/curl_cffi#290]
**Describe the bug**
请求一段时间，跑个几分钟，只要频繁请求，就会大量报错
这看着不是个例，基本上用这个框架的人，都碰到这个现象，用requests怎么跑都没问题。
**To Reproduce**

<img width="1125" alt="image" src="https://github.com/yifeikong/curl_cffi/assets/4981449/01415f30-0abb-4b95-af2b-7798348a4407">

**Comment by yifeikong** [comment]
有可能是链接池开太大了，而且没有释放机制。另外，建议不要贴截图，这样有相同错误的人没法搜到这个问题，还有就是你这截图也不全啊，关键的 getaddrinfo 都没截全……

**Comment by WendyDReid1901** [comment]
我也遇到了，改dns可以解决吗？
