### ISSUE TITLE
[BUG] Duplicate GET parameters are dropped when the params kwargs is used

### ISSUE THREAD

**Issue by emv33** [yifeikong/curl_cffi#295]
Using curl_cffi 0.6.2

Easier to explain with an example.

```
>>> from curl_cffi import requests
>>> requests.get("http://localhost:8000/?a=1&a=2", params=dict(b=3))
<Response [200]>
```

On the web server we receive `GET /?a=2&b=3` (INCORRECT, missing first "a" parameter)

If using normal requests 2.31.0:

```
>>> import requests
>>> requests.get("http://localhost:8000/?a=1&a=2", params=dict(b=3))
<Response [200]>
```

On the web server we receive `GET /?a=1&a=2&b=3` (CORRECT)

**Comment by yifeikong** [comment]
Fix is on the way, in the meanwhile, you can encode the url with `urllib.parse` yourself, without using the params parameter.
