### ISSUE TITLE
change sslversion disable

### ISSUE THREAD

**Issue by ceaqw** [yifeikong/curl_cffi#30]
```python
_client = requests.Session(
            impersonate="chrome110",
)
_client.curl.setopt(CurlOpt.SSLVERSION, 6)
```
### Setting TLS 1.2 does not take effect.

**Comment by yifeikong** [comment]
Are you trying to ensure the version is no higher than TLS 1.2? Maybe you should use `CURL_SSLVERSION_MAX_TLSv1_2`, which means "The flag defines maximum supported TLS version as TLS v1.2.". `CURL_SSLVERSION_TLSv1_2` means "TLS v1.2 or later".

Also note that `impersonate` will change SSLVERSION if it's called after `setopt`.

**Comment by ceaqw** [comment]
Can `CURL_SSLVERSION_MAX_TLSv1_2` be set when enabling the `impersonate` mode?

**Comment by yifeikong** [comment]
Yes, just make sure you set `SSLVERSION` after calling `curl.impersonate`. Because `curl_easy_impersonate` will change this, see here: https://github.com/lwthiker/curl-impersonate/blob/main/chrome/patches/curl-impersonate.patch#L301
