### ISSUE TITLE
[Feature] Push latest github version as a beta

### ISSUE THREAD

**Issue by rjenk22** [yifeikong/curl_cffi#300]
Hello, can you please create the wheels for the latest github code that can support chrome123? I tried building this myself and keep getting errors and would like to be able to install it via poetry.

Thanks

**Comment by yifeikong** [comment]
Blocked by https://github.com/yifeikong/curl-impersonate/issues/62

**Comment by rjenk22** [comment]
> Blocked by [yifeikong/curl-impersonate#62](https://github.com/yifeikong/curl-impersonate/issues/62)

Ahh what a shame, chrome122 or 123 are very important for my project and I don't think you added 122 support and skipped it. 

Well thanks for the reply, cheers!
