### ISSUE TITLE
[Feature] 为 requests.request 添加 __enter__ 和 __exit__ 属性

### ISSUE THREAD

**Issue by yintian710** [yifeikong/curl_cffi#301]
**Is your feature request related to a problem? Please describe.**

当我使用原 `requests` 时, 是可以使用 `with` 的, 但是使用 `curl_cffi` 的 `requests` 时, 是不行的

**Describe the solution you'd like**

为 `requests.request` 添加 `__enter__` 和 `__exit__` 属性

**Additional context**
测试代码
```python
import requests as raw_requests
from curl_cffi import requests as cffi_requests
from loguru import logger

try:
    with raw_requests.request(
            method="GET",
            url="http://internal.com",
    ) as response:
        logger.info(response.status_code)
except Exception as e:
    logger.error(f'raw_requests error: {e}')

try:
    with cffi_requests.request(
            method="GET",
            url="http://internal.com",
    ) as response:
        logger.info(response.status_code)
except Exception as e:
    logger.error(f'cffi_requests error: {e}')


```

结果
![image](https://github.com/yifeikong/curl_cffi/assets/59188000/948c6b0b-d304-459a-aa50-edb34a22e53c)

**Comment by yintian710** [comment]
> 请问有相关文档吗？你这种用法我是第一次见
没找到什么文档, 其实就是添加几行代码实现一下这两魔法方法

![image](https://github.com/yifeikong/curl_cffi/assets/59188000/10cf99f5-b7b6-48d8-9f95-30644a47f961)

**Comment by yifeikong** [comment]
看了下 requests 的代码，这个 close 是释放链接到链接池里。在这里用 requests.get 的时候，压根没有链接池，所以这个操作是无意义的……
