### ISSUE TITLE
[Feature] Add option to specify SNI name or IP address of URL's host in curl_cffi.requests

### ISSUE THREAD

**Issue by hycxnas** [yifeikong/curl_cffi#312]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a limitation in the current functionality of `curl_cffi.requests`. When making a request using `curl_cffi.requests.get` or `curl_cffi.requests.post`, there is no built-in option to specify the SNI name or the IP address of the URL's host. This limitation can lead to errors when trying to force a request to connect to a specific IP address while setting the `Host` header to a different domain.

For example, the following code:
```python
req.get("https://1.0.0.1", headers={'Host': 'spotify.com'}, impersonate="safari15_3", verify=False)
```
results in a `CurlError` with the message "Failed to perform, curl: (35) BoringSSL: error:10000410:SSL routines:OPENSSL_internal:SSLV3_ALERT_HANDSHAKE_FAILURE."

**Describe the solution you'd like**
It would be greatly appreciated if you could consider adding an option to `curl_cffi.requests.get` and `curl_cffi.requests.post` that allows users to specify the SNI name or the IP address of the URL's host as a parameter. This would provide more flexibility and control over the requests made using `curl_cffi.requests`.

For example, the feature could be implemented as follows:
```python
req.get("https://spotify.com", dstip="1.0.0.1", impersonate="safari15_3", verify=False)
```
In this case, the `host` parameter would specify the IP address to connect to, while the `Host` header and the URL itself would still indicate the intended domain.

**Describe alternatives you've considered**
One alternative approach could be to modify the URL itself to include the IP address, but this may not be as clean or intuitive as having a separate parameter for specifying the host.

**Additional context**
The ability to specify the SNI name or IP address of the URL's host would be a valuable addition to `curl_cffi.requests`, as it would allow for more advanced testing scenarios and better emulation of real-world browser behavior. It would also help avoid potential errors that can occur when trying to connect to a specific IP address while setting a different `Host` header.

Thank you for considering this feature request. Please let me know if you need any further information or clarification.

**Comment by yifeikong** [comment]
It's already there, curl supports it natively, if I understand correctly.

With curl_cffi, use this:

```py
s = requests.Session()                                       
s.curl.setopt(CurlOpt.RESOLVE, ["google.com:8000:127.0.0.1"])
s.get(url)

# or

s.get(url, curl_options={CurlOpt.RESOLVE: ["google.com:8000:127.0.0.1"]})
```
