### ISSUE TITLE
[BUG] Default headers setting does not prevent capitalized headers in requests

### ISSUE THREAD

**Issue by hectorgarciatorres** [yifeikong/curl_cffi#315]
Description:

I am experiencing an issue with the curl_cffi library where setting default_headers to false still results in the request being sent with capitalized headers. This behavior is problematic because I need the headers to be sent with a 1:1 match to the specified case.

Steps to Reproduce:

    Configure a request using curl_cffi and set default_headers to false.
    Specify headers with lowercase letters.
    Send the request.

Expected Behavior:

The headers should be sent exactly as specified, without capitalization.

Actual Behavior:

The headers are sent with capitalization, even though default_headers is set to false.

Environment:

    curl_cffi version: latest
    Python version: 3.12
    Operating System: Ubuntu 22.04

Additional Information:

Is there a way to ensure that the headers are sent exactly as specified, without capitalization? This is crucial for my use case.

**Comment by hectorgarciatorres** [comment]
Specifically the Host header seems to be capitalized even when i send it as 'host'

**Comment by yifeikong** [comment]
Is it just the `Host` header or every other headers?

**Comment by hectorgarciatorres** [comment]
Only the Host header is affected; the other headers are sent correctly when default_headers is disabled.

**Comment by yifeikong** [comment]
The `Host` header was removed intentionally to bypass curl's cookie policies. I guess when curl re-add the `Host` header automatically, it's always capitalized.

To fix this, an option will be needed to turn it off.

https://github.com/yifeikong/curl_cffi/blob/4aa0c9f1562d90680c787ba30f3ca4f0123294e0/curl_cffi/requests/session.py#L339-L347

You can also try http/2, by which all headers are forced to be lower case as specified in the RFC.

**Comment by hectorgarciatorres** [comment]
I tried your solution by removing the recommended code, but I'm still encountering the same issue even with HTTP/2.

**Comment by yifeikong** [comment]
Could you please post your code and the target url here?

**Comment by hectorgarciatorres** [comment]
**Code Producing the Bug:**
```
import os
from curl_cffi.requests import Session
def test_request():
    session = Session(
        allow_redirects=False,
        default_headers=False,
        timeout=60,
        cookies=None,
        http_version=2
    )

    # Headers to test
    headers = {
        'host': 'api.test.com',
        'content-type': 'application/x-www-form-urlencoded',
        'accept': 'application/json',
        'accept-language': 'en',
        'accept-encoding': 'gzip, deflate, br',
        'content-length': '0',
        'user-agent': 'test user agent',
    }

    # Send the request to httpbin.org/post to inspect the raw request details
    request = session.post(url="http://192.168.1.69:8000", headers=headers)
    print(request.text)  # This will print the raw request details
    print("Test Complete")

if __name__ == "__main__":
    os.system('clear')
    test_request()
```
    
 **Server Code:**
```
import socket
import os
from quart import Quart, request, jsonify

app = Quart(__name__)

@app.route('/', methods=['GET', 'POST'])
async def index():
    # Capture the headers exactly as they are received
    headers = [(header, value) for header, value in request.headers.items()]

    print(headers)
    data = await request.data

    print("Received HTTP/2 Request Headers:")
    for header, value in headers:
        print(f"{header}: {value}")

    print("Received HTTP/2 Request Data:")
    print(data.decode('utf-8', errors='replace'))

    print("Raw HTTP/2 Request (hex):")
    print(data.hex())

    response_data = {
        "message": "Request received",
        "headers": {header: value for header, value in headers},
        "data": data.decode('utf-8', errors='replace')
    }
    return jsonify(response_data)

if __name__ == "__main__":
    import hypercorn.asyncio
    import hypercorn.config
    import asyncio

    os.system('clear')

    config = hypercorn.config.Config()
    config.bind = ["192.168.1.69:8000"]  # Use the specified local IP address
    config.alpn_protocols = ["h2"]  # Ensure HTTP/2 is used

    asyncio.run(hypercorn.asyncio.serve(app, config))
```
**Raw Request from the server:**
```
Received HTTP/2 Request Headers:
Remote-Addr: 192.168.1.69
Host: api.test.com
Content-Type: application/x-www-form-urlencoded
Accept: application/json
Accept-Language: en
Accept-Encoding: gzip, deflate, br
Content-Length: 0
User-Agent: test user agent
```

**Comment by hectorgarciatorres** [comment]
any updates ?

**Comment by yifeikong** [comment]
What you saw is caused by the server, not the client, the server alwasy capitalize header names.

```
╰─>$ curl http://localhost:8000 -H "user-agent: curl"
{"data":"","headers":{"Accept":"*/*","Host":"localhost:8000","Remote-Addr":"127.0.0.1","User-Agent":"curl"},"message":"Request received"}
```

However, in wireshark, the request was sent as specified.

<img width="1172" alt="image" src="https://github.com/yifeikong/curl_cffi/assets/1035487/6a7dcead-31d4-4fb1-a819-cf0166c76433">
