### ISSUE TITLE
[BUG]curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (35) Send failure: Broken pipe. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.

### ISSUE THREAD

**Issue by symboly** [yifeikong/curl_cffi#317]
**Describe the bug**
1. 该bug出现在用requests发送请求时会：SSLError的网站，当使用curl_cffi 的requests发送请求时，则能够正常获取数据
2. 在使用curl_cffi 的requests发送请求中加上proxies,则会出现以上报错, 如果不是SSLError的网站，就加代理和不加都是正常的，请教一下是不是加了代理后，导致无法模拟浏览器TLS指纹了？

**To Reproduce**
1. 复现代码
'''
url = 'https://ggzyjy.xuancheng.gov.cn/xcspfront/zwxx/043001/notice_common.html' # SSLError的网站
    #url = 'http://www.lxqrmyy.com/html/web/dynamic/bulletin/index.html' # 不会SSLError的网站

    headers = {
        'Accept': '*/*',
        # 'Host': 'ggzyjy.xuancheng.gov.cn',
        'Connection': 'keep-alive'
    }

    proxy_pool = ProxyPool()
    proxy = proxy_pool.get_proxy()

    if proxy is not None:
        proxies = {
            'https': f'https://{proxy.get_ip()}',
        }
        response = requests.get(url, headers=headers, proxies=proxies, impersonate="chrome110")
        print(response.text)
    else:
        response = requests.get(url, headers=headers, impersonate="chrome110")
        print("代理失败！")
        print(response.text)
'''

**Versions**
 - OS: [mac m1]
 - curl_cffi version [ 0.6.4]

**Comment by yifeikong** [comment]
代理的格式错了，参见 #6
