### ISSUE TITLE
Can it be used with eventlet/gevent?

### ISSUE THREAD

**Issue by adv-zl** [yifeikong/curl_cffi#32]
I'm using celery and replaced default requests library with your curl_cffi.

But after starting 100 threads it seems like executing one after one (like only 1 thread is active).

How can it be patched to use in multithreaded?

**Comment by yifeikong** [comment]
Are you using sessions? If so, did you use one session for all or one session per thread? And what kind of workers are you using with celery?

**Comment by adv-zl** [comment]
Eventlet, yes sessions,  one session per thread

**Comment by yifeikong** [comment]
Unfortunately, according to the celery [docs](https://docs.celeryq.dev/en/stable/userguide/concurrency/eventlet.html) , eventlet won’t work well with curl_cffi.

> Also note that some libraries, usually with C extensions, cannot be monkeypatched and therefore cannot benefit from using Eventlet.

If celery is a must, you can use traditional process based workers. If you are open to other coroutine based methods, I am trying to bring asyncio here.

**Comment by WhZzi** [comment]
It seems to have encountered the same problem. Currently, Gunicorn is used to run django in gevent mode, and django's internal function uses curl_ Cffi, when using thread pool concurrency, curl_ Cffi sends out requests one by one and at the same time blocks threads (or even processes).

**Comment by WhZzi** [comment]
> It seems to have encountered the same problem. Currently, Gunicorn is used to run django in gevent mode, and django's internal function uses curl_ Cffi, when using thread pool concurrency, curl_ Cffi sends out requests one by one and at the same time blocks threads (or even processes).

Currently, testing has found that this issue does not occur when running without Gunicorn/event mode.

**Comment by yifeikong** [comment]
Added support for eventlet/gevent on `feature/gevent` branch by running curl_cffi in a threadpool. Although curl can not run in green threads, it can run concurrently with native threads with eventlet/gevent's threadpool.

Basically, all you have to change is to add the `thread` argument:

```py
requests.get("http://192.168.64.5:8080/delay/2", thread="gevent")
// or 
requests.get("http://192.168.64.5:8080/delay/2", thread="eventlet")
```

You can find working examples [here](https://github.com/yifeikong/curl_cffi/tree/feature/gevent/tests/threads)

Can you try and see if it works? The wheel can be found in the CI build artifacts:

https://github.com/yifeikong/curl_cffi/actions/runs/4731954007
