### ISSUE TITLE
[BUG] multi-threaded requests, there will be certificate errors.

### ISSUE THREAD

**Issue by ham2530** [yifeikong/curl_cffi#321]
Failed to perform, curl: (35) BoringSSL SSL_connect: SSL_ERROR_SYSCALL 
When making multi-threaded requests, there will be certificate errors.

```py
response =requests.post(url, data=data_str, headers=headers, proxy=port,impersonate='chrome99',curl_options={CurlOpt.SSL_VERIFYHOST:1})
```

**Comment by yifeikong** [comment]
Are you on Windows with proxies? If so, there is no obvious solutions right now, see #229.

**Comment by ham2530** [comment]
感谢，看了文档，是底层的ssl库了

回头换个Ubu的环境试下

**Comment by ham2530** [comment]
测试了，并发超过3还是会报BoringSSL SSL_connect的问题，在Ubuntu环境

**Comment by yifeikong** [comment]
贴一下能复现的代码吧，我试一下

**Comment by ham2530** [comment]
没问题了,放在云服务器，丢包概率低

不能用python的thread多线程跑，改为subprocess的popen，后台开一个命令跑，并发5000没有问题
