### ISSUE TITLE
Unsupported Media Type: x-www-form-urlencoded

### ISSUE THREAD

**Issue by dumbled00r** [yifeikong/curl_cffi#322]
I want to make request to a website, and I use a session
Everything else works normally but if I want to post to a link in that website using this
```
await self.http.post(
                        url,
                        headers=self.headers,
                    )
```
the returning result is
```
{"statusCode":415,"code":"FST_ERR_CTP_INVALID_MEDIA_TYPE","error":"Unsupported Media Type","message":"Unsupported Media Type: x-www-form-urlencoded"}
```
I have provided all necessary fields, but it still not working.
What is the problem?

**Comment by yifeikong** [comment]
Do you have `Content-Type: x-www-form-urlencoded` in your headers?

**Comment by dumbled00r** [comment]
Yes, I did add it in, but the problem still persists.
![image](https://github.com/yifeikong/curl_cffi/assets/82684246/97403508-0595-46d7-9529-ad5c8622eae2)
![image](https://github.com/yifeikong/curl_cffi/assets/82684246/203a30e4-f2cc-4d7a-84d7-2e539a98ac9c)

**Comment by dumbled00r** [comment]
It works with postman, but it does not work here :(. I dont know the reason
![image](https://github.com/yifeikong/curl_cffi/assets/82684246/02d6120e-c34a-4be9-9538-363301350d06)

**Comment by yifeikong** [comment]
> Yes, I did add it in, but the problem still persists. ![image](https://private-user-images.githubusercontent.com/82684246/336127742-97403508-0595-46d7-9529-ad5c8622eae2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzA3MTgsIm5iZiI6MTcxNzQzMDQxOCwicGF0aCI6Ii84MjY4NDI0Ni8zMzYxMjc3NDItOTc0MDM1MDgtMDU5NS00NmQ3LTk1MjktYWQ1Yzg2MjJlYWUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE2MDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyNzgzOGExOGZkNWUwZTlmYzcxZjgyNjBiMGMwY2JjYmEzMDI0N2ZhZGNjZjJhMjc0Njg1ZWUyMmI5YzEyMjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iE6urlLYZmOUOyGHmbau61XxKVxY_WfDfBeomxUffS0) ![image](https://private-user-images.githubusercontent.com/82684246/336127796-203a30e4-f2cc-4d7a-84d7-2e539a98ac9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MzA3MTgsIm5iZiI6MTcxNzQzMDQxOCwicGF0aCI6Ii84MjY4NDI0Ni8zMzYxMjc3OTYtMjAzYTMwZTQtZjJjYy00ZDdhLTg0ZDctMmU1MzlhOThhYzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDE2MDAxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ0NGNjMWZjMWRiNTQzZDQ4ZjQ0YWFhNmE1ZWRkYWJlZWJkYTFkNjJmZDRmZWZlYTE0YmRmNjI5ZmVkNTcyYjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1nIAzPOdRfPt6GJ777blSKAz0Y4aEaMbn7hXtgUFwps)

You should omit it. The error clearly said this content-type is not supported. :P
