### ISSUE TITLE
Failed to perform, curl: (5) getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by dumbled00r** [yifeikong/curl_cffi#324]
I'm trying to run a curl-cffi script with AsyncSession and ~80 threads without any proxies

It performs well for a while, but then, all the threads encounter this error, and I have to restart the program to continue running it:

```
Failed to perform, curl: (5) getaddrinfo() thread failed to start. See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
```

Is there any problem with my side? Or it is the server side that having this problem ? I tried both proxy and non-proxy code, both produced this error!

**Comment by yifeikong** [comment]
Were you using ~80 coroutines or ~80 threads? Mixing threads and eventloops is not a great idea, generally. Try use processes instead.

Anyway, in the future, the upstream curl-impersonate will be built with c-ares by default, which should solve all the DNS resolution problems.

**Comment by dumbled00r** [comment]
Thanks for addressing it!

**Comment by dumbled00r** [comment]
I tried with 30 threads, but the same thing happened
```
async def main():
    tasks = []
    semaphore = asyncio.Semaphore(30)
    with open("ref_list_task_test.txt", "r") as f:
        ref_code_json_list = [line.strip() for line in f.readlines()]
    for ref_code_json in ref_code_json_list:
        ref_json = json.loads(ref_code_json)
        for name, ref_code in ref_json.items():
            if name in ["orbit"]:
                for _ in range(8):
                    tasks.append(process_tool(semaphore, ref_code))

    await asyncio.gather(*tasks, return_exceptions=True)
    
    ```
    Here is my main function. What should I modify? @yifeikong

**Comment by dumbled00r** [comment]
> Try to change the version

Use older version you meant?

**Comment by deedy5** [comment]
The problem is not the number of threads. And c-ares will not help here. 

It's just that your dns-server can't handle so many requests. 

The solution is simple: configure your system to use several fast dns-servers (1.1.1.1.1, 1.0.0.1, 8.8.8.8.8, 9.9.9.9.9, and so on).

**Comment by dumbled00r** [comment]
@deedy5 I did think about  that, but I tested on some Virtual Private Server, they ran exactly 510 lines then this error started happening (just as my main computer).

**Comment by dumbled00r** [comment]
I tested with Google DNS, and everything works well, for now :D.
Thank @deedy5 !

**Comment by WendyDReid1901** [comment]
> I tested with Google DNS, and everything works well, for now :D. Thank @deedy5 !

Not working...............

**Comment by WendyDReid1901** [comment]
> curl-impersonate

curl-impersonate,is this updated?

**Comment by 3215656174** [comment]
I have the same problem. Have you solved it?
