### ISSUE TITLE
[BUG] Connection failure with proxies that only support HTTP

### ISSUE THREAD

**Issue by jxlil** [yifeikong/curl_cffi#326]
**Describe the bug**

The `CONNECT` method is being used to establish a connection with proxies that only accept `HTTP` connections. This generate the following error since these proxies do not support the `CONNECT` method:

```
curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (56) CONNECT tunnel failed, response 400
```

---

**To Reproduce**

1. Make an HTTP request by setting a proxy that only accepts HTTP connections

```python
from curl_cffi.requests import request

request(
    method="GET",
    url="http://example.com",
    debug=True,
    headers={
        "Proxy-Authorization": "Bearer <auth_token>",
    },
    proxies={
        "https": "http://0.0.0.0:8080",
        "http": "http://0.0.0.0:8080",
    },
)
```

2. The request will fail since the connection cannot be established using the `CONNECT` method

```
WARNING: failed to open cookie file ""
  Trying 0.0.0.0:8080...
Connected to 0.0.0.0 (0.0.0.0) port 8080
CONNECT tunnel: HTTP/1.1 negotiated
allocate connect buffer
Establish HTTP proxy tunnel to example.com:80
CONNECT example.com:80 HTTP/1.1
Host: example.com:80
Proxy-Connection: Keep-Alive

HTTP/1.1 400 Bad Request
Server: x/0.0.0
Date: Thu, 13 Jun 2024 03:49:36 GMT
Content-Type: text/html
Content-Length: 163
Connection: close

CONNECT tunnel failed, response 400
Closing connection
```

---

**Expected behavior**

The `GET` method must be used to establish a connection with proxies that only accept `HTTP` connections. For example this is the same request using [curl-impersonate](https://github.com/lwthiker/curl-impersonate):

```shell
curl_chrome110 --proxy http://0.0.0.0:8080 http://example.com \
--header 'Proxy-Authorization: Bearer auth_token' \
--verbose
```

```
*   Trying 0.0.0.0:8080...
* Connected to 0.0.0.0 (0.0.0.0) port 8080 (#0)
> GET http://example.com/ HTTP/1.1
> Host: example.com
[...]
```

---

**Versions**
 - curl_cffi `0.7.0b4`

**Comment by yifeikong** [comment]
I see, we should not set [CURLOPT_HTTPPROXYTUNNEL](https://curl.se/libcurl/c/CURLOPT_HTTPPROXYTUNNEL.html) for http proxy.

**Comment by coletdjnz** [comment]
> The GET method must be used to establish a connection with proxies that only accept HTTP connections

This is not exactly true, you can have a CONNECT proxy for standard HTTP connections too. 

However, from what I've seen, it is commonplace to have http requests to use standard HTTP proxy and https use HTTP CONNECT. (Which is what we have manually configured curl_cffi to do in our project)

**Comment by jxlil** [comment]
> This is not exactly true, you can have a CONNECT proxy for standard HTTP connections too.

You're right, although the `CONNECT` method is commonly used for SSL connections, it can also be used with HTTP.

---

I will leave this manual solution here in case someone needs it:

```python
from curl_cffi import CurlOpt
from curl_cffi.requests import request

request(
    method="GET",
    url="http://example.com",
    debug=True,
    headers={
        "Proxy-Authorization": "Bearer <auth_token>",
    },
    proxies={
        "https": "http://0.0.0.0:8080",
        "http": "http://0.0.0.0:8080",
    },
    curl_options={
        CurlOpt.HTTPPROXYTUNNEL: 0,
    },
)
```

**Comment by yifeikong** [comment]
Is https://github.com/yifeikong/curl_cffi/commit/d1a64ff02d584dadbd32a636b26e482985f67420 what you are looking for?

**Comment by yifeikong** [comment]
Changed in v0.7.0b7.

**Comment by jxlil** [comment]
> Is [d1a64ff](https://github.com/yifeikong/curl_cffi/commit/d1a64ff02d584dadbd32a636b26e482985f67420) what you are looking for?

Thanks, this change solved the problem:

```
Connected to 0.0.0.0 (0.0.0.0) port 8080
GET http://example.com/ HTTP/1.1
Host: example.com
```
