### ISSUE TITLE
Tag 0.7.0 is gone?

### ISSUE THREAD

**Issue by drupol** [yifeikong/curl_cffi#327]
Hello,

Some maintainers of the Nix ecosystem noticed that the `0.7.0` tag is no longer available. We have a few requests and concerns regarding this:

1. Could you please provide some insight into why the `0.7.0` tag was deleted?
2. Would it be possible to tag a new `0.7.1` version?

Version `0.7.0` is necessary for us to build `duckduckgo-search`, and its absence is causing significant issues for our build process. Tags are crucial for our distribution as they directly impact the build and stability of our packages. Deleting tags can lead to substantial problems for downstream distributions like ours that depend on specific versions for consistency and reproducibility.

Understanding the reasons behind this change would be very helpful. Additionally, we kindly request that you avoid deleting tags in the future if possible. Maintaining these tags ensures that all downstream distributions can reliably build and depend on your project without unexpected breakages.

Thank you!

**Comment by yifeikong** [comment]
0.7.0 has never been released, the latest version is 0.7.0b4, which is a pre-release beta version. AFAIK, The DDGoSearch package now [depends](https://github.com/deedy5/duckduckgo_search/blob/main/pyproject.toml#L32) on `pyreqwest-impersonate`, not `curl-cffi` any more.

**Comment by drupol** [comment]
Thank you very much for your quick answer, going to update all of that in nix during the day.
