### ISSUE TITLE
[Feature] akamai detecting impersonate requests

### ISSUE THREAD

**Issue by erbhosting** [yifeikong/curl_cffi#329]
**Is your feature request related to a problem? Please describe.**
hi
i check and from yesterday morning akamai detecting requests
please check it and what is the problem

**Describe the solution you'd like**
i want bypass bot detection but i think is not possible now
please check it!!
thanks a lot

**Comment by yifeikong** [comment]
Although TLS and Akamai http2 fingerprints are important factors in many anti-bot services. this package is not guaranteed to be able to pass any specific site or protection.

What we are trying to achieve is only to impersonate the browser's fingerprints, there is nothing more.

**Comment by erbhosting** [comment]
thanks for answers
could u give me ur email or other social media id for contact with u?!

**Comment by yifeikong** [comment]
See my GitHub homepage, please.
