### ISSUE TITLE
Use more JA3 fingerprints from another repository

### ISSUE THREAD

**Issue by AnasBoujamaa** [yifeikong/curl_cffi#330]
**Is your feature request related to a problem? Please describe.**
I'm currently searching for a Python library capable of using the same JA3 fingerprints of the most important browsers to prevent Cloudflare from detecting my bots. I found your repository and another based on this one (https://github.com/rawandahmad698/noble-tls). The other allows me to impersonate very recent versions like chrome_124 or even using fingerprints of okhttp, which works for preventing the detection (old versions are blocked), and periodically that repository gets updated to include more fingerprints.

**Describe the solution you'd like**
However, I prefer using your repository because it has a nice syntax very similar to the requests library. Also, your repository works very good with files, but the other can't manage them. Since that repository is based on yours, it's possible for you to use it to upgrade your repository adding more fingerprints? Sincerely I didn't investigate how yours projects work exactly.

By the way, thank you for developing this project. You helped me a lot :)

Edit: Before while testing on a website protected with Cloudflare I noticed that if I enable using a random tls extension order (option available in the noble-tls project and in tls-client) I would be able to bypass the security, but if disabled, not. So maybe the solution for the problem I detected would be adding that option too, combined with allowing more JA3 fingerprints.

**Comment by yifeikong** [comment]
1. You can use Chrome 124 now, with the beta version 0.7.0b6. The release process was stalled by Windows build issues, which is resolved now.
2. As for as I know, this is the only project based on curl-impersonate. Most of other projects are based on golang tls-client. The most important differences is that curl-impersonate uses real world TLS library BoringSSL, which chrome uses, too.
3. Support for other customized fingerprints will be the next thing to implemente, once 0.7 is released.

**Comment by AnasBoujamaa** [comment]
Thank you!
