### ISSUE TITLE
[BUG]在django的中调用AsyncSession的close方法，会报警告 UserWarning: Curlm alread closed! quitting from process_data

### ISSUE THREAD

**Issue by wkz2003** [yifeikong/curl_cffi#332]
**Describe the bug**
我在django的异步视图里创建了一个AsyncSession，请求完后会提示“ UserWarning: Curlm alread closed! quitting from process_data”

**To Reproduce**
```
# 使用with上下文会报警告
async def get_token(request):
    async with rs.AsyncSession() as r:
        res = await r.get('https://course168.top')
        print(res.text)

# 手动创建并关闭也会报警告
async def get_token(request):
    client = rs.AsyncSession()
    res = await r.get('https://course168.top')
    await client.close()
    print(res.text)

# 这样就不会报警告
async def get_token(request):
    async with rs.AsyncSession() as r:
        res = await r.get('https://course168.top')
        await asyncio.sleep(0.6)
        print(res.text)
```

**Versions**
 - OS: window10 x64
 - curl_cffi version 0.6.4
 - Django: 4.2.6

**Additional context**
- 使用的是async
- 另外我发现如果在请求之后进行一次await asyncio.sleep(0.6)，就不会报警告
- 这个情况仅会出现一次，只要django不重新启动，后续的请求就不会再报这个警告。是因为django框架的事件循环和AsyncSession不是同一个吗？

**Comment by yifeikong** [comment]
感觉你这个用法不太对，如果你用在 web 框架里，session 应该是跨越请求的，而每个请求都创建一个 session，那和同步的请求还有什么区别？

**Comment by wkz2003** [comment]
> 感觉你这个用法不太对，如果你用在 web 框架里，session 应该是跨越请求的，而每个请求都创建一个 session，那和同步的请求还有什么区别？

我可能对异步还有循环这些不太了解。请教一下，我的这个服务就是个爬虫服务，客户端发送请求我就把cookie转发到对应目标服务器，原来的代码我一直用的curl_cffi的同步session，没有什么问题，但是我的逻辑又有sleep来防止目标服务器反爬，就想着要不试下异步看看有没有性能提升。那我应该在全局共用一个session实例吗？

**Comment by yifeikong** [comment]
你试试呢？我觉得 session 应该放在全局共享的变量里，就像是数据库链接的 handle 一样。
