### ISSUE TITLE
Send websocket text frame

### ISSUE THREAD

**Issue by Cataphract89** [yifeikong/curl_cffi#337]
How do I send not binary data but text data over the websocket, similar to the original library?
When I send messages through curl_cffi in binary formattai I get the error "Invalid frame type", but when I send through the original  library there is no such error

**Comment by yifeikong** [comment]
What do you mean by original library? Can you please post you code here?

**Comment by Cataphract89** [comment]
I mean "websocket" library (ws = websocket.WebSocketApp(url, on_message=self.on_message})
In a function "on_message" when I get a message, I respond to it ws.send('some text') And everything works fine, I get the correct response. 
But when I connect to the websocket via "curl_cffi" and respond with ws.send('some text'). I get an error that the message must be in binary format. I convert to binary, the code works fine, but the server tells me that I am sending the wrong frame

**Comment by Cataphract89** [comment]
I fix that, my bad
