### ISSUE TITLE
[BUG] ValueError: too many file descriptors in select()

### ISSUE THREAD

**Issue by luanon404** [yifeikong/curl_cffi#338]
possible fix, change from asyncio.SelectorEventLoop into asyncio.ProactorEventLoop, when i set ProactorEventLoop loop, i got 
```

Traceback (most recent call last):
  File "F:\pythonxxx\src\a.py", line 343, in _generate_mail
    async with AsyncSession(**session_params) as session:
  File "F:\pythonxxx\.venv\Lib\site-packages\curl_cffi\requests\session.py", line 994, in __aexit__
    await self.close()
  File "F:\pythonxxx\.venv\Lib\site-packages\curl_cffi\requests\session.py", line 999, in close
    await self.acurl.close()
  File "F:\pythonxxx\.venv\Lib\site-packages\curl_cffi\aio.py", line 155, in close
    await self._checker
RuntimeError: Task <Task cancelling name='Task-318' coro=<Test.run.<locals>.worker() running at F:\pythonxxx\src\a.py:416> cb=[as_completed.<locals>._on_completion() at D:\Python\Python312\Lib\asyncio\tasks.py:618, gather.<locals>._done_callback() at D:\Python\Python312\Lib\asyncio\tasks.py:767]> got Future <Task cancelling name='Task-2183' coro=<AsyncCurl._force_timeout() running at F:\pythonxxx\.venv\Lib\site-packages\curl_cffi\aio.py:176>> attached to a different loop

```

**Comment by luanon404** [comment]
Im using Windows so should use ProactorEventLoop instead of SelectorEventLoop

**Comment by yifeikong** [comment]
From the traceback, it seems that you switched loop implementation from the middle. You use select loop as early as possible.

**Comment by luanon404** [comment]
> From the traceback, it seems that you switched loop implementation from the middle. You should select loop as early as possible.

yes, because on windows, SelectorEventLoop limit amount of pipe can open, so they made ProactorEventLoop, i dont know can i use ProactorEventLoop instead of SelectorEventLoop? or change something in the code?

**Comment by luanon404** [comment]
i tried pass ProactorEventLoop loop into session class to bypass the limit, but its say the future waited in different loop

**Comment by luanon404** [comment]
so i wonder that u not use same loop for all code

**Comment by yifeikong** [comment]
If you want to use ProactorLoop, you don’t need to do anything, since it’s the default one.

**Comment by luanon404** [comment]
> If you want to use ProactorLoop, you don’t need to do anything, since it’s the default one.

but i got this when run like 700 threads, 
```
Exception in thread Tornado selector:
Traceback (most recent call last):
  File "D:\Python\Python312\Lib\threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "D:\Python\Python312\Lib\threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "F:\python\MicrosoftOutlook\.venv\Lib\site-packages\curl_cffi\_asyncio_selector.py", line 201, in _run_select
    rs, ws, xs = select.select(to_read, to_write, to_write)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many file descriptors in select()
```
still use SelectorEventLoop , so its not default ProactorEventLoop ?

**Comment by luanon404** [comment]
i dont know why but i solved by add time.sleep(0.01) before select command, 
![image](https://github.com/yifeikong/curl_cffi/assets/71830807/2f314481-ae82-4df2-9dd5-77f63b604f9b)

**Comment by luanon404** [comment]
maybe its running too fast before it data coming
