### ISSUE TITLE
[BUG]In version 0.7.0, if http_version=CurlHttpVersion.V1_1 is specified, akamai and ja3 custom configurations will become invalid.

### ISSUE THREAD

**Issue by ZZhangQihang** [yifeikong/curl_cffi#349]
**Describe the bug**
In version 0.7.0, if http_version=CurlHttpVersion.V1_1 is specified, akamai and ja3 custom configurations will become invalid.

**To Reproduce**
```
from curl_cffi import CurlHttpVersion, requests

url = "https://tls.browserleaks.com/json"

okhttp4_android10_ja3 = ",".join(
    [
        "771",
        "4865-4866-4867-49195-49196-52393-49199-49200-52392-49171-49172-156-157-47-53",
        "0-23-65281-10-11-35-16-5-13-51-45-43-21",
        "29-23-24",
        "0",
    ]
)

okhttp4_android10_akamai = "4:16777216|16711681|0|m,p,a,s"

extra_fp = {
    "tls_signature_algorithms": [
        "ecdsa_secp256r1_sha256",
        "rsa_pss_rsae_sha256",
        "rsa_pkcs1_sha256",
        "ecdsa_secp384r1_sha384",
        "rsa_pss_rsae_sha384",
        "rsa_pkcs1_sha384",
        "rsa_pss_rsae_sha512",
        "rsa_pkcs1_sha512",
        "rsa_pkcs1_sha1",
    ]
    # other options:
    # tls_min_version: int = CurlSslVersion.TLSv1_2
    # tls_grease: bool = False
    # tls_permute_extensions: bool = False
    # tls_cert_compression: Literal["zlib", "brotli"] = "brotli"
    # tls_signature_algorithms: Optional[List[str]] = None
    # http2_stream_weight: int = 256
    # http2_stream_exclusive: int = 1

    # See requests/impersonate.py and tests/unittest/test_impersonate.py for more examples
}


r = requests.get(
    url, ja3=okhttp4_android10_ja3, akamai=okhttp4_android10_akamai, extra_fp=extra_fp, http_version=CurlHttpVersion.V1_1
)
print(r.json())
```

**Expected behavior**
Can output akamai_hash akamai_text normally

**Versions**
 - OS: window 11
 - curl_cffi: 0.7.0

**Comment by yifeikong** [comment]
Akamai fingerprints are for http2, being invalid is expected if you use http1.1. As for ja3, it does not change on my machine.

**Comment by ZZhangQihang** [comment]
> Akamai 指纹适用于 http2，如果使用 http1.1，则无效。至于 ja3，在我的计算机上它没有变化。

When I use V2_0 and configure the browser's ja3 and Akamai text, an error message appears: curl_cffi.requests.errors.RequestsError: Failed to perform, curl: (56) Failure writing output to destination, passed 13 returned 0. See https://curl.se/libcurl/c/libcurl-errors.html first for more details. However, when I use V1_1, it is normal. Is this a problem with the proxy quality or other reasons?

**Comment by yifeikong** [comment]
It may be related to the specific akamai fingerprint you were using. Please post your code that can reproduce the error here.

**Comment by ZZhangQihang** [comment]
It seems to have nothing to do with configuring Akamai parameters. When I don't configure Akamai and ja3, I get the same error when I set V2_0. It works only when I set it to V1_1. But then I can't use the custom Akamai and ja3 functions.

**Comment by yifeikong** [comment]
Sorry, but I can not reproduce your problem with the first comment.
