### ISSUE TITLE
Import problem(for real)

### ISSUE THREAD

**Issue by Jeremyyen0978** [yifeikong/curl_cffi#351]
![image](https://github.com/user-attachments/assets/3118d143-774d-452a-8606-ff48deb89518)

I accidently deleted the "Session" file's containing codes, but when I put it back and run the code again, it still couldn't work.

**Comment by yifeikong** [comment]
Why not just uninstall and reinstall?

**Comment by Jeremyyen0978** [comment]
I did what you said, and it output this.
![image](https://github.com/user-attachments/assets/72f5eded-36d6-470c-8136-2b3a07bba182)

**Comment by yifeikong** [comment]
From the image you posted, it's another package `PyCAI` which was not found.
