### ISSUE TITLE
[Feature]

### ISSUE THREAD

**Issue by lyy077** [yifeikong/curl_cffi#357]
`with requests.get(task['url'], stream=True, timeout=60, proxies=proxies,
                                      headers=DEFAULT_HEADERS, verify=False) as response:`
报错：stream参数不存在。是目前不支持这种流式读取吗？什么时候能支持呢？

**Comment by yifeikong** [comment]
Read the docs: https://github.com/yifeikong/curl_cffi/blob/main/examples/stream.py
