### ISSUE TITLE
TypeError: cannot pickle 'LockType' object

### ISSUE THREAD

**Issue by WhZzi** [yifeikong/curl_cffi#43]
在对session.cookies进行deepcopy时遇到的报错：TypeError: cannot pickle 'LockType' object

    backup_cookies = copy.deepcopy(session.cookies)
  File "/usr/lib64/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.8/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
  File "/usr/lib64/python3.8/copy.py", line 270, in _reconstruct
    state = deepcopy(state, memo)
  File "/usr/lib64/python3.8/copy.py", line 146, in deepcopy
    y = copier(x, memo)
  File "/usr/lib64/python3.8/copy.py", line 230, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
  File "/usr/lib64/python3.8/copy.py", line 161, in deepcopy
    rv = reductor(4)
TypeError: cannot pickle 'LockType' object

**Comment by yifeikong** [comment]
不用 copy，直接

```py
from curl_cffi.requests.cookies import Cookies

new_cookies = Cookies(old_cookies)
```

就行了

**Comment by WhZzi** [comment]
> 

十分感谢！快速且有效的解答 👍 
有时候会有将当前session的cookies给序列化到本地保存的需求，用到的函数是pickle.dumps(new_cookies)，仍然会受阻，对于这种会有有效的方法吗？

**Comment by yifeikong** [comment]
Cookies 是直接从 httpx 抄过来的，看[这个](https://github.com/encode/httpx/issues/895#issuecomment-611156308)就行了

```py
import pickle
# import httpx
from curl_cffi import requests

def save_cookies(client):
    with open("cookies.pk", "wb") as f:
        pickle.dump(client.cookies.jar, f)

def load_cookies():
    if not os.path.isfile("cookies.pk"):
        return None
    with open("cookies.pk", "rb") as f:
        return pickle.load(f)

# client = httpx.Client(cookies=load_cookies())
client = requests.Session(cookies=load_cookies())
save_cookies(client)
```

**Comment by WhZzi** [comment]
好的,十分感谢您的解答

**Comment by paigeman** [comment]
> Cookies 是直接从 httpx 抄过来的，看[这个](https://github.com/encode/httpx/issues/895#issuecomment-611156308)就行了
> 
> ```python
> import pickle
> # import httpx
> from curl_cffi import requests
> 
> def save_cookies(client):
>     with open("cookies.pk", "wb") as f:
>         pickle.dump(client.cookies.jar, f)
> 
> def load_cookies():
>     if not os.path.isfile("cookies.pk"):
>         return None
>     with open("cookies.pk", "rb") as f:
>         return pickle.load(f)
> 
> # client = httpx.Client(cookies=load_cookies())
> client = requests.Session(cookies=load_cookies())
> save_cookies(client)
> ```

根据您指示的原帖，似乎这个jar仍然是不可pickle的

但是原帖的下面给出了[可以运行的例子](https://github.com/encode/httpx/issues/895#issuecomment-970689380)
