### ISSUE TITLE
Contribution clarification

### ISSUE THREAD

**Issue by nicoandmee** [yifeikong/curl_cffi#45]
@yifeikong  Hi, I am interested in contributing to this project. For clarification, I see we are parsing the curl's `.h` file declarations. We have some of them, but not the `#define` directives or enums for example. Is it correct, that we want these as well? I was thinking of putting this additional parsing logic in https://github.com/yifeikong/curl_cffi/blob/master/preprocess/generate_consts.py

Let me know if it sounds right

**Comment by nicoandmee** [comment]
> Yes, the `const.py` is generated by `generate_consts.py`. Actually, this file should be called when building the wheel to generate `const.py`, and `const.py` should not stay in the source. However, due to limitations on Windows, `const.py` is kept for convenience.

Ah yes I got that. But I'm wondering, if there is more work to be done in `generate_consts.py.`. For example- You have a TODO mentioned referring to `CURL_ERROR_SIZE`. This is declaration is inside `curl.h`:
```c
#define CURL_ERROR_SIZE 256
```
It seems we get it by parsing all `#define` declarations. What do you think about this?

**Comment by yifeikong** [comment]
You can export as many as you like, I don’t see any side effect here. Just make sure they are grouped in the correct category.
