### ISSUE TITLE
[BUG] "ImportError: DLL load failed while importing _wrapper: The specified module could not be found." - PyInstaller issue

### ISSUE THREAD

**Issue by sc0ned** [yifeikong/curl_cffi#48]
Hey again! So I was just trying to obfsucate & pack my app using pyarmor & pyinstaller and cant seem to get past this error on the final .exe:
```
┌─────────────────────────────── Traceback (most recent call last) ────────────────────────────────┐
│ in <module>:3                                                                                    │
│ in <module>:37                                                                                   │
│                                                                                                  │
│ in exec_module:495                                                                               │
│ in <module>:1                                                                                    │
│ in <module>:18                                                                                   │
│                                                                                                  │
│ in exec_module:495                                                                               │
│                                                                                                  │
│ in <module>:33                                                                                   │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
ImportError: DLL load failed while importing _wrapper: The specified module could not be found.
[13380] Failed to execute script 'main' due to unhandled exception!
```

I've tried following the instructions in the readme about using the hidden-import/collect-all options but can't seems to get it to work - any idea what could be happening?

Also, using the "collect all" option introduces another warning message:
`WARNING: file already exists but should not: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI146482\curl_cffi\_wrapper.pyd`

The machine I'm trying to compile on is a 2016 windows server
Python version: 3.9.6
curl_cffi version: 0.5.5 (seems like you fixed most of the previous issues I had, so thanks!)
cffi version: 1.15.1
my pyinstaller string is super long with a bunch of hidden imports and stuff due to my app being large but I'm using one-file mode, if that makes any difference. I could try and make a sample app if needed, just lmk!

Thanks in advance as usual

**Comment by yifeikong** [comment]
Could you please provide a minimal reproducible set of files? I can only fix it if I can reproduce it. Thanks.

**Comment by sc0ned** [comment]
> Could you please provide a minimal reproducible set of files? I can only fix it if I can reproduce it. Thanks.

Hey, so after some more testing with the basic script in the readme, I think I figured it out! After looking in the pyinstaller logs I realized that it was having trouble finding the libcurl dll, so I just included that as an "--add-data" option and it seems to work! I also realized that it wasn't necessary to use "collect-all" and that I could use "collect-submodules" instead and avoid the "file already exists" warning (and that I didn't need to add the _cffi_backend hidden import for it to work)

So, just for clarification in case anyone else runs into this issue, this was my final pyinstaller string:
```
pyinstaller --noconfirm --onefile --console --paths "C:/Users/Administrator/AppData/Local/Programs/Python/Python39" --add-data "C:/Users/Administrator/AppData/Local/Programs/Python/Python39/Lib/site-packages/curl_cffi.libs/libcurl-cbb416caa1dd01638554eab3f38d682d.dll;." --collect-submodules "curl_cffi"  "C:/Users/Administrator/Desktop/test_script.py"
```
