### ISSUE TITLE
发送请求时无法控制请求头顺序

### ISSUE THREAD

**Issue by dream2333** [yifeikong/curl_cffi#49]
部分网站如cloudflare会检测到headers的默认顺序，从而识别爬虫，curl_cffi无法将请求头按照dict的顺序排列，这个是curl的问题吗？

**Comment by yifeikong** [comment]
确实无法控制，之前也有人提过这个问题，但是我试了下，和 Chrome 应该是一致的，参见 #28 。

**Comment by yifeikong** [comment]
> except this is being added:
> Http2-Settings: AAEAAQAAAAIAAAAAAAMAAAPoAAQAYAAAAAYABAAA

Curl tries to establish a http2 connection by default, if you do not like this, you can disable it. However, I havn't exposed the corresponding constants from `curl.h` for that, for now, you can just look up curl docs, and use the magic numbers instead.

For the `sec-*` headers, I believe it's the same as browser as shown in #28. If not, it might be fiddler's issue.
