### ISSUE TITLE
curl_cffi sends payloads incorrectly

### ISSUE THREAD

**Issue by CheerfulNag** [yifeikong/curl_cffi#68]
curl_cffi is designed to be similar to the Requsts library, but unfortunately it struggles to process payload the same way. 

When sending dict with data=payload(the way firefox shows it when you're checking content in the formatted mode) - it may not accept it properly, not converting to regular string as Requests does(same site). Gladly it works if it's formatted as a string in the code. 

More important: 
When sending dict with json=payload - it struggles too. I'm yet to figure out why, but again - Requests library sends it just fine and only curl_cffi is provoking server error. 

Would be great if there would be some note about differences, so that it could be looked up.

**Comment by yifeikong** [comment]
Could you please give me some examples? So I can reproduce and fix them.

**Comment by CheerfulNag** [comment]
I was wrong, it wasn't a problem with json in my "More important" part. 

The problem is content-type header that library tries to add when detects json in the payload. It does it in "if json" in sessions file If I'm not mistaken. 

If I remove content-type header from headers I'm applying, or if I'll remove line in the library that adds same header - it works.

**Comment by yifeikong** [comment]
It seems that requests, since v2.4.2, also adds `Content-Type: application/json` header per the standard. Which version of requests are you using?

**Comment by CheerfulNag** [comment]
```
Name: requests
Version: 2.28.2
Summary: Python HTTP for Humans.
Home-page: https://requests.readthedocs.io
Author: Kenneth Reitz
Author-email: me@kennethreitz.org
License: Apache 2.0
Location: /usr/lib/python3.11/site-packages
Requires: idna, urllib3
Required-by: moddb, ProtonUp-Qt, steam
```
I guess it ads it somehow differently cause no such problem with it.
