### ISSUE TITLE
Unable to import curl_cffi

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#69]
```
Python 3.10.8 (main, Nov 15 2022, 02:01:06) [Clang 10.0.0 (clang-1000.10.44.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from curl_cffi import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/curl_cffi/_init_.py", line 4, in <module>
    from ._wrapper import ffi, lib  # type: ignore
ImportError: dlopen(/usr/local/lib/python3.10/site-packages/curl_cffi/wrapper.abi3.so, 2): Symbol not found: ___chkstk_darwin
  Referenced from: /usr/local/lib/python3.10/site-packages/curl_cffi/.dylibs/libunistring.5.dylib (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /usr/local/lib/python3.10/site-packages/curl_cffi/.dylibs/libunistring.5.dylib
```

**Comment by yifeikong** [comment]
Are you using macOS 10.x?

**Comment by BhardwajAnshul** [comment]
Yes

On 6/26/23, Yifei Kong ***@***.***> wrote:
> Are you using macOS 10.x?
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/yifeikong/curl_cffi/issues/69#issuecomment-1606356455
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
[image: logo]
*Anshul Bhardwaj*
Mobile: +918871841674, +918824525151
***@***.***

**Comment by yifeikong** [comment]
Unfortunately, the binaries are built on [macOS 11 machines](https://github.com/yifeikong/curl_cffi/blob/master/.github/workflows/build.yaml#L21), it's unlikely that this lib is backported to macOS 10.x. If you really need to run on macOS 10, you will have to compile it yourself.
