### ISSUE TITLE
Add Chrome 107

### ISSUE THREAD

**Issue by OEvans117** [yifeikong/curl_cffi#7]
107	107.0.5304.107	Windows 10	chrome107	curl_chrome107

**Comment by yifeikong** [comment]
Sorry, this project is simply a wrapper around the precompiled binaries from [here](https://github.com/lwthiker/curl-impersonate/releases) and [here](https://github.com/depler/curl-impersonate-win/releases). If they do not update, you will need to compile it yourself. In the future, we should add the compile steps in our `.github/workflows`. You are welcome to contribute to that.

**Comment by yifeikong** [comment]
Updated to latest upstream version.
