### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by BhardwajAnshul** [yifeikong/curl_cffi#71]
RequestsError(Failed to perform, ErrCode: 60, Reason: 'SSL certificate problem: unable to get local issuer certificate')
 
 Getting the above error when trying to use a certificate using verify option.
 
 Same certificate works fine with requests and requests_html.

**Comment by yifeikong** [comment]
`curl_cffi` uses the bundled `cacert.pem` by default, which should be recent enough for most sites. If you are facing any missing certs or using your self-signed certs, try to use the certificate `requests` uses, which should probabaly be something like `/etc/ssl/certs/ca-certificates.crt`.

There is no option to set the cert path in `Session` now, which should be added. In the meanwhile, you can use something like this.

```python
from curl_cffi import Curl, requests

curl = Curl(cacert="/path/to/your/cert")
session = requests.Session(curl=curl)
```

**Comment by yifeikong** [comment]
Close as stale
