### ISSUE TITLE
再下载图片时遇到错误

### ISSUE THREAD

**Issue by pengyanbing84** [yifeikong/curl_cffi#75]
错误信息：Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 1 was not closed cleanly before end of the underlying stream'

请求url：：： ['https://img.kwcdn.com/product/Fancyalgo/VirtualModelMatting/dc49321e685566e937b3e6f3793b636b.jpg']
========================请求报错： Failed to perform, ErrCode: 92, Reason: 'HTTP/2 stream 1 was not closed cleanly before end of the underlying stream'

**Comment by yifeikong** [comment]
首先，这应该是和底层 curl 相关的问题，你可以搜对应的 curl 92 错误码和报错信息，看看能不能解决。
其次，有些站的 h2 确实支持不好，后续会添加一个强制 http11 的开关。

**Comment by yifeikong** [comment]
Duplicate of #19
