### ISSUE TITLE
MacOs M2芯片 pip install error

### ISSUE THREAD

**Issue by zhajingwen** [yifeikong/curl_cffi#8]
ERROR: Command errored out with exit status 1:
   command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-wheel-fbgk2w9a
       cwd: /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.9-universal2-cpython-39
  creating build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  copying ./test_curl.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  copying ./cffi_build.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  copying ./__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  copying ./_const.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  copying ./example.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
  running build_ext
  generating cffi module 'build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c'
  creating build/temp.macosx-10.9-universal2-cpython-39
  building 'curl_cffi._curl_cffi' extension
  creating build/temp.macosx-10.9-universal2-cpython-39/build
  creating build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39
  creating build/temp.macosx-10.9-universal2-cpython-39/include
  clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Iinclude -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c -o build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.o
  build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c:50:14: fatal error: 'pyconfig.h' file not found
  #    include <pyconfig.h>
               ^~~~~~~~~~~~
  1 error generated.
  error: command '/usr/bin/clang' failed with exit code 1
  ----------------------------------------
  ERROR: Failed building wheel for curl-cffi
  Running setup.py clean for curl-cffi
Failed to build curl-cffi
Installing collected packages: curl-cffi
    Running setup.py install for curl-cffi ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/setup.py'"'"'; __file__='"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = [f.read](http://f.read/)().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-record-82gum57w/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/shixiaolong/Library/Python/3.9/include/python3.9/curl-cffi
         cwd: /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/
    Complete output (26 lines):
    running install
    /Users/shixiaolong/Library/Python/3.9/lib/python/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
      warnings.warn(
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-universal2-cpython-39
    creating build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    copying ./test_curl.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    copying ./cffi_build.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    copying ./__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    copying ./_const.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    copying ./example.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
    running build_ext
    generating cffi module 'build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c'
    creating build/temp.macosx-10.9-universal2-cpython-39
    building 'curl_cffi._curl_cffi' extension
    creating build/temp.macosx-10.9-universal2-cpython-39/build
    creating build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39
    creating build/temp.macosx-10.9-universal2-cpython-39/include
    clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Iinclude -I/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -c build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c -o build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.o
    build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._curl_cffi.c:50:14: fatal error: 'pyconfig.h' file not found
    #    include <pyconfig.h>
                 ^~~~~~~~~~~~
    1 error generated.
    error: command '/usr/bin/clang' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Developer/CommandLineTools/usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/[setup.py](http://setup.py/)'"'"'; __file__='"'"'/private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-install-qc26puko/curl-cffi_964d697b07704e03b434331373194977/[setup.py](http://setup.py/)'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = [f.read](http://f.read/)().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-record-82gum57w/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /Users/shixiaolong/Library/Python/3.9/include/python3.9/curl-cffi Check the logs for full command output.

**Comment by zhajingwen** [comment]
another error

  error: subprocess-exited-with-error
  
  × Building wheel for curl_cffi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [107 lines of output]
      /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-build-env-zqkkdkyo/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-10.9-universal2-cpython-39
      creating build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/build.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/__init__.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/_const.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/headers.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/requests.py -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      running egg_info
      writing curl_cffi.egg-info/PKG-INFO
      writing dependency_links to curl_cffi.egg-info/dependency_links.txt
      writing requirements to curl_cffi.egg-info/requires.txt
      writing top-level names to curl_cffi.egg-info/top_level.txt
      reading manifest file 'curl_cffi.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'curl_cffi/cacert.pem'
      warning: no files found matching 'curl_cffi/*.dll'
      adding license file 'LICENSE'
      writing manifest file 'curl_cffi.egg-info/SOURCES.txt'
      /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-build-env-zqkkdkyo/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'curl_cffi.include' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'curl_cffi.include' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'curl_cffi.include' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'curl_cffi.include' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      /private/var/folders/j6/4jxhrj8161xg60h5v_ssfk000000gn/T/pip-build-env-zqkkdkyo/overlay/lib/python3.9/site-packages/setuptools/command/build_py.py:202: SetuptoolsDeprecationWarning:     Installing 'curl_cffi.include.curl' as data is deprecated, please list it in `packages`.
          !!
      
      
          ############################
          # Package would be ignored #
          ############################
          Python recognizes 'curl_cffi.include.curl' as an importable package,
          but it is not listed in the `packages` configuration of setuptools.
      
          'curl_cffi.include.curl' has been automatically added to the distribution only
          because it may contain data files, but this behavior is likely to change
          in future versions of setuptools (and therefore is considered deprecated).
      
          Please make sure that 'curl_cffi.include.curl' is included as a package by using
          the `packages` configuration field or the proper discovery methods
          (for example by using `find_namespace_packages(...)`/`find_namespace:`
          instead of `find_packages(...)`/`find:`).
      
          You can read more about "package discovery" and "data files" on setuptools
          documentation page.
      
      
      !!
      
        check.warn(importable)
      copying curl_cffi/cdef.c -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      copying curl_cffi/shim.c -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi
      creating build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include
      copying curl_cffi/include/shim.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include
      creating build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/Makefile.am -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/curl.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/curlver.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/easy.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/header.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/mprintf.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/multi.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/options.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/stdcheaders.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/system.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/typecheck-gcc.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      copying curl_cffi/include/curl/urlapi.h -> build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/include/curl
      running build_ext
      generating cffi module 'build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._wrapper.c'
      creating build/temp.macosx-10.9-universal2-cpython-39
      building 'curl_cffi._wrapper' extension
      creating build/temp.macosx-10.9-universal2-cpython-39/build
      creating build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39
      creating build/temp.macosx-10.9-universal2-cpython-39/curl_cffi
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Icurl_cffi/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._wrapper.c -o build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._wrapper.o
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -arch arm64 -arch x86_64 -Werror=implicit-function-declaration -Icurl_cffi/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c curl_cffi/shim.c -o build/temp.macosx-10.9-universal2-cpython-39/curl_cffi/shim.o
      clang -bundle -undefined dynamic_lookup -arch arm64 -arch x86_64 -Wl,-headerpad,0x1000 build/temp.macosx-10.9-universal2-cpython-39/build/temp.macosx-10.9-universal2-cpython-39/curl_cffi._wrapper.o build/temp.macosx-10.9-universal2-cpython-39/curl_cffi/shim.o -L/Users/runner/work/_temp/install/lib -lcurl-impersonate-chrome -o build/lib.macosx-10.9-universal2-cpython-39/curl_cffi/_wrapper.abi3.so
      ld: warning: directory not found for option '-L/Users/runner/work/_temp/install/lib'
      ld: library not found for -lcurl-impersonate-chrome
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for curl_cffi
Failed to build curl_cffi
ERROR: Could not build wheels for curl_cffi, which is required to install pyproject.toml-based projects

**Comment by yifeikong** [comment]
还没打二进制包，需要在 Apple Silicon 下用的话，现在需要自己编译。

**Comment by w37fhy** [comment]
> 还没打二进制包，需要在 Apple Silicon 下用的话，现在需要自己编译。

能否指点下如何自己编译？从来没编译过。有点懵逼~谢谢了！

**Comment by zhajingwen** [comment]
> 还没打二进制包，需要在 Apple Silicon 下用的话，现在需要自己编译。

OK

**Comment by w37fhy** [comment]
> > 还没打二进制包，需要在 Apple Silicon 下用的话，现在需要自己编译。
> 
> OK

你好，请问你知道怎么编译么？能否教教我，特别需要这个库。或者编译好以后能不能给我发一份直接用？

**Comment by zhajingwen** [comment]
> > > 还没打二进制包，需要在 Apple Silicon 下用的话，现在需要自己编译。
> > 
> > 
> > OK
> 
> 你好，请问你知道怎么编译么？能否教教我，特别需要这个库。或者编译好以后能不能给我发一份直接用？

抱歉，这个我也没有弄呢，在忙其他的事情

**Comment by yifeikong** [comment]
我在本地 build 了一份传到 pypi 上了，试试能不能用。但是因为别的都是 github actions 自动打包的，这个得我手动打包，所以更新可能会有延迟。

```py
pip install curl_cffi=0.3.1
```

**Comment by zhajingwen** [comment]
> ```python
> pip install curl_cffi=0.3.1
> ```

should be `pip install curl_cffi==0.3.1`

**Comment by w37fhy** [comment]
> > ```python
> > pip install curl_cffi=0.3.1
> > ```
> 
> should be `pip install curl_cffi==0.3.1`

可以使用！非常非常非常感谢！！
