### ISSUE TITLE
请求参数异常

### ISSUE THREAD

**Issue by 77bw** [yifeikong/curl_cffi#81]
```
data =  {
    "action": "next",
    "messages": [
        {
            "id": "aaa20609-94fd-4079-b129-7a8e75e3b99d",
            "author": {
                "role": "user"
            },
            "content": {
                "content_type": "text",
                "parts": [
                    "aaaa"
                ]
            },
            "metadata": {}
        }
    ],
    "parent_message_id": "aaa19e4f-061d-4645-a6a1-e1d88a568784",
    "model": "gpt-4",
    "timezone_offset_min": -480,
    "history_and_training_disabled": False,
    "arkose_token": '2061771724a103cd9.8893533702|r=us-west-2|meta=3|metabgclr=transparent|metaiconclr=%23757575|guitextcolor=%23000000|pk=35536E1E-65B4-4D96-9D97-6ADB7EFF8147|at=40|sup=1|rid=57|ag=101|cdn_url=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc|lurl=https%3A%2F%2Faudio-us-west-2.arkoselabs.com|surl=https%3A%2F%2Fclient-api.arkoselabs.com|smurl=https%3A%2F%2Fclient-api.arkoselabs.com%2Fcdn%2Ffc%2Fassets%2Fstyle-manager'
}
```
请求结果为：：：
{"detail":[{"loc":["body"],"msg":"value is not a valid dict","type":"type_error.dict"}]}
422

**Comment by yifeikong** [comment]
这个是典型的 FastAPI 报错，你的请求里是不是缺少 body 参数？

**Comment by yifeikong** [comment]
Close as stale.

**Comment by D4Vinci** [comment]
@perkfly  I'm experiencing the same issue with the FastAPI server. The issue can be produced by using this format:
```python
curl_cffi.post('http://0.0.0.0:8000/', headers=headers, json=json_data, impersonate="chrome", default_headers=False)
```
I turned off the default headers because I thought it was the reason behind the issue, but it wasn't. The issue can be produced by just enabling `impersonate`, and FastAPI won't be able to see the body of the request. Disabling `impersonate` solves the issue, but I need it enabled to help bypass protections

**Comment by lexiforest** [comment]
@D4Vinci Have you compared the packets? It can be really helpful.

**Comment by D4Vinci** [comment]
> [@D4Vinci](https://github.com/D4Vinci) Have you compared the packets? It can be really helpful.

Do you recommend a specific tool, or should I go with Wireshark?

**Comment by D4Vinci** [comment]
> [@D4Vinci](https://github.com/D4Vinci) Have you compared the packets? It can be really helpful.

Hey @lexiforest, I don't know what fields you are looking for exactly, so here's the full data for both packets from Wireshark. The one on the right is with impersonate set to `chrome` and the one on the left without it. The same exact request is sent to the FastAPI server.

I used `curl_cffi.post('http://scrapling.requestcatcher.com/', headers=headers, json=json_data, impersonate="chrome", verify=False)`
and `curl_cffi.post('http://scrapling.requestcatcher.com/', headers=headers, json=json_data, verify=False)`

Note: using `data=json.dumps(json_data)` produces the same error.

<img width="2488" height="1172" alt="Image" src="https://github.com/user-attachments/assets/da17dbdf-c7ba-410f-beba-f434001b8a02" />

I think the problemt might be that the server is seeing the request with impersonate as a request from the browser so it treats it like a GET request somehow so it doesn't see the body. That's just a guess.

**Comment by lexiforest** [comment]
Which one works? You can try limiting the http version to 1.1 by `http_version="v1"`.

**Comment by D4Vinci** [comment]
> Which one works? You can try limiting the http version to 1.1 by `http_version="v1"`.

The one without `impersonate="chrome"` is one that's working

**Comment by lexiforest** [comment]
It's probably related to h2, can you try:

> curl_cffi.post('http://scrapling.requestcatcher.com/', headers=headers, json=json_data, impersonate="chrome", verify=False, http_version="v1")

**Comment by D4Vinci** [comment]
> It's probably related to h2, can you try:
> 
> > curl_cffi.post('http://scrapling.requestcatcher.com/', headers=headers, json=json_data, impersonate="chrome", verify=False, http_version="v1")

Yes, it worked with `v1`!
