### ISSUE TITLE
Your browser sent a request that this server could not understand

### ISSUE THREAD

**Issue by mavic111** [yifeikong/curl_cffi#87]
I'm using client = Session(impersonate='chrome110')

This error raised when i'm doing POST request without data, while other request like GET and POST with data are working normally. 

```bash
<HTML><HEAD>
<TITLE>Bad Request</TITLE>
</HEAD><BODY>
<H1>Bad Request</H1>
Your browser sent a request that this server could not understand.<P>
Reference&#32;&#35;7&#46;4a1d770&#46;1689773281&#46;2509c458
</BODY>
</HTML>
```

Then i change to httpx, with client = Client(http2=True), it works. 
But i want to keep using curl_cffi because some of time they block my httpx request. I've read on the internet that the error is because the headers content is too large. I can't give reproduction code because it needs a login. Is there a way to modify the headers using Session?

**Comment by mavic111** [comment]
requests.post(url)

**Comment by yifeikong** [comment]
Any particular headers or cookies are you using? It would be very helpful if you could use Charles or Fiddler to capture the 400 request and successful request and post them here.

**Comment by mavic111** [comment]
The response is HTTP 411 : Length Required.

I already fixed it by adding 'Content-Length': '0' to the header. I think  curl_cffi not generating Content-Length header in the POST request without data, while httpx does.

Thanks for the reply, i'll close this. :)

**Comment by yifeikong** [comment]
Thanks for reporting back your findings, I will add that header for empty bodies.
