### ISSUE TITLE
使用asyncio时会报错

### ISSUE THREAD

**Issue by kali0134** [yifeikong/curl_cffi#89]
![image](https://github.com/yifeikong/curl_cffi/assets/111333222/a4748cd4-15b6-4dce-95d7-cdf56a865310)
上面是代码
这是啥情况呀
下面报错
![image](https://github.com/yifeikong/curl_cffi/assets/111333222/5da6b0b9-be88-4dc6-bd7c-d4c21c0b92fb)

![image](https://github.com/yifeikong/curl_cffi/assets/111333222/28361597-26bc-4642-9a84-a4d086a87369)

**Comment by yifeikong** [comment]
请查看 [FAQ](https://curl-cffi.readthedocs.io/en/latest/faq/) 最后一条

**Comment by yifeikong** [comment]
这个是设置使用啥 Loop 的，你得在事件循环开始之前设置吧？把 set_event_loop_policy 放到 main 外边来试试呢

**Comment by kali0134** [comment]
哇靠，可以了 太谢谢你哈哈

**Comment by yifeikong** [comment]
对，因为浏览器的指纹就是固定的，Python/Go/curl 等工具的指纹也是固定的。tls 防护有两种方法，要么是白名单，只允许浏览器指纹，要么是黑名单，封掉 Python 等的默认指纹。现实情况中，显然是白名单更多一点。如果你需要随机指纹的话，直接用 httpx，改支持的 extension 等等就可以了。

**Comment by kali0134** [comment]
这个改支持的扩展我不太理解是什么意思， 是手动更改chrome浏览器里面的扩展程序吗， 如果是用代码自动改的话能提供一个httpx修改扩展的示例吗

**Comment by yifeikong** [comment]
https://www.cnblogs.com/Eeyhan/p/15681207.html

**Comment by kali0134** [comment]
![image](https://github.com/yifeikong/curl_cffi/assets/111333222/babeb124-ee54-4e50-a624-db3ae73a4fc5)

大佬这个又是什么问题呀， 是对方开启了http2.0的指纹校验什么的吗

**Comment by yifeikong** [comment]
看看这个 #19

**Comment by kali0134** [comment]
![image](https://github.com/yifeikong/curl_cffi/assets/111333222/6c3f8210-b13c-4cf6-b1e6-12e5c753025d)
大佬 我又遇到了一个问题， 我只设置了两个并发还是会这样

**Comment by yifeikong** [comment]
同样的代码，你把 url 改成百度或者知乎这种大站试试呢？如果也不行，那就是你代码有问题或者 bug，你把代码贴上来。如果可以，那就是你这个站限制，那没办法……
