### ISSUE TITLE
http2指纹可以过吗？

### ISSUE THREAD

**Issue by zhajingwen** [yifeikong/curl_cffi#9]
这个是不是ja3和http2的指纹一块过了；

**Comment by yifeikong** [comment]
curl-impersonate 可以就可以啊，我试了下 chrome104 在 https://kawayiyi.com/tls 是可以的。

**Comment by zhajingwen** [comment]
> curl-impersonate 可以就可以啊，我试了下 chrome104 在 https://kawayiyi.com/tls 是可以的。

OK
