### ISSUE TITLE
利用软件设置了全局代理之后，再使用该模块请求时会绕过代理使用真实ip去请求

### ISSUE THREAD

**Issue by xilingdong** [yifeikong/curl_cffi#90]
最近我利用该模块去请求一个网站的时候发现返回的数据和浏览器返回不一致，经过排查，是该模块在请求的时候使用了真实ip，由于该测试网站不同ip返回的结果不同，我也才发现了这个问题，请问一下作者，这种情况该怎么办呢？我请求的网站是epic游戏详情页面，详情页面的价格会随着ip变化

**Comment by xilingdong** [comment]
headers = {
        'accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.7',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36 Edg/114.0.1823.67',
    }
response = requests.get(
                url,
                headers=headers,
                impersonate="chrome101",
                timeout=10
            )

**Comment by yifeikong** [comment]
这得看你怎么设置的全局代理啊。Windows 还是 macOS 还是 Linux？环境变量还是系统设置？实在不行可以直接使用 proxies 参数传进去。

**Comment by xilingdong** [comment]
我用的是windows的v2rayn软件设置的全局代理，我用正常的requets模块也试过了，是能正常用开的代理去访问的，而用你这个模块去访问的时候却用的不是v2软件设置的代理访问，所以我才来问你这个问题。请问你有什么思路吗？

**Comment by yifeikong** [comment]
简单查了下，Windows 上的「系统代理」是配置在注册表里了，requests 有这块的逻辑，所以能读取到，参考[这里](https://stackoverflow.com/questions/65931275/python-requests-module-does-it-use-system-level-on-windows-proxy-settings)；libcurl 本身是不支持的，参见[这里](https://github.com/curl/curl/issues/3965)，所以这里需要你自己把代理传进去。

当然，欢迎提交 PR 支持这个功能。

**Comment by xilingdong** [comment]
好的好的，谢谢作者的回答，这段时间我也去查找了解过了，和你了解的差不多一致。得到的结论就是windows的requests比较智能，其他的urllib模块等以及其他系统下的requests都是得自己传入代理参数的，再次感谢作者的回答
