### ISSUE TITLE
Duplicate Header when post data repeat

### ISSUE THREAD

**Issue by pscj** [yifeikong/curl_cffi#92]
首次post数据超时，再次尝试post时，会得到http 400,和返回的数据： Duplicate Header content-type detected。100%复现，主要代码如下

<code>
 while True:
    proxy = {
      "https":  'xxx',
    }  
    try:
      resp = session.get(url=url,verify=False, timeout=15, impersonate='chrome110')
      break
    except Exception as err:
      time.sleep(timeSleep)
</code>
超时随机出现，很难服务器抓包。不确定只是content-type重复，还是默认header都会重复添加

**Comment by yifeikong** [comment]
Thanks for reporting, this is a bug, will fix soon.
