### ISSUE TITLE
curl_cffi.requests.errors.RequestsError: Failed to perform, ErrCode: 35, Reason: 'BoringSSL SSL_connect: SSL_ERROR_SYSCALL in connection to api.willhaben.at:443 '

### ISSUE THREAD

**Issue by justtempusername** [yifeikong/curl_cffi#94]
I use impersonate="safari15_5" and  async with requests.AsyncSession() as sess

curl_cffi==0.5.7

**Comment by RandomStrangerOnTheInternet** [comment]
What did you do in order to resolve this?, I'm getting the same issue
