### ISSUE TITLE
Feature request: Add requests-like debug logging

### ISSUE THREAD

**Issue by Velocidensity** [yifeikong/curl_cffi#98]
Established HTTP libraries, such as requests/urllib3 and httpx, provide debug logging with (at least) URL and status code of every request, which helps to quickly catch failures. curl_cffi seems to be missing anything similar.

Examples:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): example.com:443
DEBUG:urllib3.connectionpool:https://example.com:443 "GET / HTTP/1.1" 200 648

DEBUG:httpx._client:HTTP Request: GET https://example.com "HTTP/1.1 200 OK"
```

**Comment by yifeikong** [comment]
Actually, the debug functionality has been exposed on [master branch](https://github.com/yifeikong/curl_cffi/blob/master/curl_cffi/requests/session.py#L146), however, it's **not** uploaded to PyPI yet due to some bugs. If you want to enable it now, you can use something like this:

```
from curl_cffi import requests, CurlOpt, CurlInfo, lib
s = requests.Session()
s.curl.setopt(CurlOpt.VERBOSE, 1)
lib._curl_easy_setopt(self._curl, CurlOpt.DEBUGFUNCTION, lib.debug_function)
```

**Comment by Velocidensity** [comment]
Thanks, I will wait until the release. I did try your example code, but it doesn't appear to be working. Executes correctly without error, but doesn't print anything during a request. I assume `self._curl` is supposed to be `s.curl._curl`, judging from [this](https://github.com/yifeikong/curl_cffi/blob/122063421bcbb44bd591db066d28c021c7e0ddcf/curl_cffi/curl.py#L97) line.

**Comment by yifeikong** [comment]
The curl-native debug info has been exposed several versions ago. requests-like debugging info is not planned.
